### ISSUE TITLE
No sé por qué no funciona el botón interno (atmega)

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#10]
Hola, llevo horas intentando pero el botón interno no funciona (y aún no consigo aluminio para probar el otro, pero al juntar los caimanes no pasa nada). Mi código debiese estar bien, lo analizé y re-analizé 1000 veces (definir entradas, pullup, if(blablabla) i++), pero el contador (i) no aumenta al apretar el botón correcto y verlo en el display. ¿hay alguna posibilidad de que el botón esté malo o qué puedo estar haciendo mal?(ya probé comentando el debouncing para verificar que el código no se quede atrapado ahí).

**Comment by felipesanchezvaras** [comment]
@diegomarusic 
¿Puedes subir tu código a tu repositorio de Github para poder mirarlo ? Es posible que tengas un error y es mejor observarlo. Sino, existe también la posibilidad que el botón esté malo (en ese caso deberíamos hacer un cambio, lo que podemos hacer hasta hoy viernes 18:30 hrs), pero primero revisemos que no estés haciendo algo mal en tu código. 

Espero tu respuesta,
Saludos

**Comment by diegomarusic** [comment]
subido! https://github.com/IEE2463/laboratorio-2-diegomarusic
