### ISSUE TITLE
Duda sobre distinguido de portabilidad

### ISSUE THREAD

**Issue by Incruen** [IEE2463/classroom#10]
Hola!

Me comentaron que hacer un código portable para ambos micro-controladores "valía por dos" (distinguido en cada uC), pero quería saber si algún ayudante del curso me lo puede confirmar.

Jorge

**Comment by akaminetzkyp** [comment]
Hola Jorge!

Debes realizar otro distinguido aparte del código portable.

Saludos!

**Comment by akaminetzkyp** [comment]
Retiro mi comentario anterior. En la pauta no se dice explícitamente que deben ser dos distinguidos, así que hacer un código portable es suficiente.

**Comment by Incruen** [comment]
Gracias!
