### ISSUE TITLE
requisitos implícitos lab 2

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#10]
¿Es aceptable que algunos led del display "parpadeen" unos milisegundos entre un número y otro? (me pasa que los led que tienen que apagarse, se demoran 100ms mas que los led que tienen que encenderse al pasar de un numero a otro)

**Comment by fffonceca** [comment]
Quizás es un error de código, probablemente el cambio no se está ejerciendo en el momento que lo aprietas, sino en el que sueltas el botón. (como lo especifica el lab).
Hazle un repaso a tu código y fíjate precisamente en eso.
