### ISSUE TITLE
Problema al usar el DAC y TFT

### ISSUE THREAD

**Issue by sebapulgar** [IEE2463/classroom#100]
hola! al graficar la sinusoide en la TFT e intentar prender un LED por medio del DAC pareciera que una comunicación interfiriera sobre la otra, ya que al graficar sola la sinusoide no existe ningún problema y al hacer oscilar el LED por separado tampoco, sin embargo al juntar ambos códigos no responde a ninguna comunicación por la terminal.
No sabemos si es problema de memoria u otro tipo, tienen alguna idea de que puede ser? o como arreglarlo?
muchas gracias!

**Comment by felipesanchezvaras** [comment]
¿Cómo están graficando la sinusoide en la TFT ? Puede ser que tengan ambos códigos en whiles separados y no permite que se salga de uno u otro. Estructuren el problema y vean si desean alternar entre ambas comunicaciones o hacer una y luego la otra. 

Recuerden que la TFT es solo output y además esta tiene un buffer propio, por lo que una opción sería gráficar la Sinusoide en la pantalla y luego comenzar a enviar la sinusoide al DAC. 

En cuanto al tamaño del archivo, vean el tamaño del archivo .elf o de los posibles warnings que aparecen al compilar.
