### ISSUE TITLE
Entrega 2 Proyecto

### ISSUE THREAD

**Issue by PamelaRomero** [IEE2463/classroom#101]
Hola a todos! hoy le pregunté al profe si la segunda entrega del proyecto podría ser el viernes 17 en vez del miércoles 15 para tener un poco más de tiempo y me dijo que creara una issue para saber si están de acuerdo o no?¿ lo están?¿

**Comment by danielauu** [comment]
Lo estoy Pame! Sugiero apoyar esta issue con un like a tu anuncio 😀

**Comment by gonzalezconstanza** [comment]
sii, yo estoy de acuerdo:)

**Comment by josetroncosoz** [comment]
Buena idea! Estoy de acuerdo

**Comment by RafaelOrmazabal** [comment]
Estoy de acuerdo

**Comment by diegognaez** [comment]
Estoy de acuerdo

**Comment by belenardoo** [comment]
Estoy muy de acuerdo!!

**Comment by IsabelJamett** [comment]
Estoy de acuerdo :blush:

**Comment by simone1919** [comment]
De acuerdo

**Comment by Yairdv** [comment]
apoyo

**Comment by itserrano** [comment]
Estoy de acuerdo 😄
