### ISSUE TITLE
Proyecto: Tetris

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#104]
Avances y dudas relacionadas con Tetris

**Comment by belenardoo** [comment]
Hola!

Quería preguntar con qué debe cumplir la jugabilidad mínima.

Es suficiente que el juego tenga una pantalla de bienvenida, aparezcan piezas aleatorias que caen y se puedan rotar y mover horizontalmente para completar el esquema?
Tenemos las colisiones verticales solucionadas pero aún algunas complicaciones con las horizontales, debemos solucionar esto ahora o lo dejamos para la segunda entrega?
También está establecida la condición de perder, la que al cumplirse indica que se ha perdido y reinicia el juego
