### ISSUE TITLE
Retornar error config UART LAB 4

### ISSUE THREAD

**Issue by eaanais** [IEE2463/classroom#11]
Buenas, tengo una duda con respecto al error que debe generar la config del UART al no ser una entrada válida, se debe enviar un mensaje de error por UART a la consola? de ser así me imagino que debemos seleccionar una configuración por default para enviarla (por ejemplo 9600_8N1) o es otro tipo de mensaje? gracias de antemano

**Comment by akaminetzkyp** [comment]
Hola!

Como bien mencionas, si se ingresa una configuración no válida, esta no puede ser usada para enviar información. Para desplegar el mensaje de error, una opción es enviarla con una configuración predeterminada. También podrías hacer que el programa no pueda ser compilado si detecta un error.

Saludos!

**Comment by Incruen** [comment]
Hola!

Otra alternativa válida en caso de ingresar parámetros que provoquen un error en el USART_Init() podría ser el deshabilitar el transmisor a través de alguno de los registros del uC? por ejemplo con el bit TXEN0  de la AVR.

Jorge

**Comment by akaminetzkyp** [comment]
Eso también puede ser una opción. Sin embargo, igual se debe avisar que hay un error (prendiendo un LED, por ejemplo).
