### ISSUE TITLE
Subir códigos al repositorio

### ISSUE THREAD

**Issue by itserrano** [IEE2463/classroom#11]
Hola!
Al subir los códigos utilizados en el lab 1 se debe subir la carpeta completa que crea Atmel Studio o basta con subir solo el main.c con un nombre descriptivo?

Muchas gracias!

**Comment by fffonceca** [comment]
Los otros archivos son irrelevantes, solo los que contengan contenido académico como los .c, los .h y cualquier otro que se especifique en los laboratorios respectivos. Saludos!
