### ISSUE TITLE
LAB 02 - Dudas Code Composer Studio

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#11]
Espacio para las dudas relacionadas con la instalación y utilización de CCS. 

En caso de requerir ayuda con macOS, favor etiquetar a Agustin @aamacaya

**Comment by angelux666** [comment]
Hola tengo un problema al correr el programa de prueba "hello world" me aparece el error "could not open file"

**Comment by aamacaya** [comment]
@angelux666  Te recomiendo crear un nuevo proyecto en CCS (recuerda selecionar la MSP430F5529 al configurar el proyecto). Después copia y pega el código de ejemplo de "hello world" en el main. FInalmente tienes que conectar la placa a tu computador, compilar y subir el programa a la placa.

**Comment by angelux666** [comment]
@aamacaya acabo de hacer todo lo que me dijiste pero aparece el mismo error: "Load program error.   Encountered a problem loading file:prueba1 Could not open file"

**Comment by fffonceca** [comment]
@angelux666 Este problema puede pasar por muchos motivos. @aamacaya mencionó la variante donde uno no trabaja en el workspace correspondiente, por favor verifica con no sea eso. Otro de los problemas que provoca este tipo de respuesta es el hecho de que tengas espacios en los nombres intermedios de las carpetas. Algunas veces code composer no se identifica bien con espacios. Prueba creando un proyecto en otra carpeta (una que no tenga un PATH con espacios) Por ejemplo:

- [ ] `PATH:  C:\Documentos\Mejor Ramo\SEP\Proyectos` 
- [x] `PATH:  C:\Documentos\Mejor_Ramo\SEP\Proyectos`

**Comment by mapendola** [comment]
Hola, tengo dos problemas con CCS:

1- Desde ayer estuve intentando probar mi código en assembly pero CCS me arroja muchos errores extraños, incluso con el ejemplo que enviaron. Con todo lo que es C no tengo problemas pero si con proyectos en assembly. El principal error parece ser este: 
Description	Resource	Path	Location	Type
mklib: gmake error during rts430x_sc_sd_eabi.lib build null: mklib: gmake error during rts430x_sc_sd_eabi.lib build	pruebaAsm		 	C/C++ Problem

2- Intente actualizar la versión de CCS, actualmente es 9.1, pero no puedo porque al parecer detecta el antivirus activo aun cuando está desactivado y cancela el procesos de instalación.

Mi sospecha es que pudo haber ocurrido un error en la instalación, volví a instalar CCS v9.1 y me di cuenta que esta versión igual detecta el antivirus activo, pero me deja instalarlo de todas formas (de aquí mis sospechas de algún posible error en la instalación, quizás falta algún paquete). 

Espero que me puedan ayudar, gracias!

**Comment by fffonceca** [comment]
@mapendola Hola! Acabo de ver esta issue, pudiste resolver tu problema? Cuando ocurre esto, la solución más efectiva es como tu hiciste... Instalarlo de nuevo en el disco C preferentemente en una carpeta sin espacios para evitar problemas con el PATH. Yo tuve un problema similar y tuve que formatear el computador (algo severo, pero me funcionó).

**Comment by mapendola** [comment]
@fffonceca Hola, si lo pude solucionar, por alguna razón faltaba un archivo del compilador, me di cuenta al instalarlo en otro PC, asique extraje el archivo de ese PC y lo agregué en la carpeta que correspondía.
