### ISSUE TITLE
Lab 02: Task 3, caso en que se seleccione el mismo color seguido.

### ISSUE THREAD

**Issue by JoaquinVilla** [IEE2463/classroom#12]
Hola! Cuando se seleccionan los 4 colores, en el caso que son distintos se puede ver la transición de uno a otro, pero cuando un color se repite se vería como un continuo. Importa esto? O es necesario que entre cada transición de color el led este apagado?

**Comment by fffonceca** [comment]
Recomendamos intercalar un tiempo muerto entre cada color. Saludos!
