### ISSUE TITLE
Cambio de frecuencias con el botón

### ISSUE THREAD

**Issue by cefernandez1** [IEE2463/classroom#12]
Hola. En el bonus en el que se debe cambiar la frecuencia con la que brilla el led con el botón ¿Es necesario que haya más de dos frecuencias a las que funcione el dispositivo? y de ser así ¿Se puede asumir que el botón debe mantenerse presionado por un período de tiempo o la respuesta debe ser instantánea?

**Comment by fffonceca** [comment]
Hola! Te explico: Es un bonus, y por ende este puntaje agregado será otorgado a las personas que puedan ejercer dominio de código y que entiendan lo que hacen. La forma en la que se implemente no importa, siempre y cuando el resultado sea atractivo y merecedor de la bonificación.
Primera pregunta) pueden ser 2 o más.
Segunda pregunta) Queda a criterio de la persona.
