### ISSUE TITLE
CCS linking Error

### ISSUE THREAD

**Issue by nrrobles** [IEE2463/classroom#12]
Hola! Estoy teniendo problemas con CCS al linkear los archivos USART_implement_me. El debugger arroja el siguiente error:
error #10056: symbol "USART_Transmit_char" redefined: first defined in "./USART_implement_me.obj"; redefined in "./main.obj"
error #10056: symbol "USART_Init" redefined: first defined in "./USART_implement_me.obj"; redefined in "./main.obj"
Donde supuestamente se están redefiniendo las funciones llamadas, pero solamente se estan llamando desde el código principal. Este error solo se presenta en CCS y no en Atmel Studio (al menos en mi caso)

**Comment by akaminetzkyp** [comment]
Hola! Tienes tu código subido a tu repo? Avísame para poder revisarlo y ver si pillo algo. :)

**Comment by nrrobles** [comment]
El código ya esta en la repo. Muchas gracias

**Comment by akaminetzkyp** [comment]
En tu archivo `USART_1.c` deberías importar `USART_implement_me.h` en vez de `USART_implement_me.c`. Prueba arreglando eso y me cuentas. :)

En general, se importan los _headers_ del otro archivo y se compilan ambos códigos `.c`.
