### ISSUE TITLE
Problemas con ATmega328p

### ISSUE THREAD

**Issue by Tomas-Mondaca** [IEE2463/classroom#13]
Hola, 
Estaba intentando programar un código para probar el PWM en el microcontrolador (https://www.electroschematics.com/9941/avr-pwm/ el que sale en esa página) y cuando intenté "leer " el dispositivo en  "Device information" me lanzó el siguiente error:
Failed to enter programming mode. ispEnterProgMode: Error status received: Got 0xc0, expected 0x00 (Command has failed to execute on the tool)

Unable to enter programming mode. Verify device selection, interface settings, target power, security bit, and connections to the target device.

Probé volviendo a correr el "blink led" y el testeo de pines pero me sale el mismo error :c.
Quería saber si será un problema con mi pc o con el microcontrolador , no he tenido la oportunidad de probar en otro pc aún pero es para ver si me puedo conseguir uno.
Saludos

**Comment by CamilaTurrieta** [comment]
@Tomas-Mondaca En Material de apoyo -> Tutoriales, subimos a principio de semestre un tutorial de cómo solucionar el error que mencionas y cómo evitarlo.

[https://github.com/IEE2463/classroom/blob/master/Material%20de%20apoyo/Tutoriales/Soluciones_AVR.pdf](url)

**Comment by CamilaTurrieta** [comment]
@Tomas-Mondaca 

En Material de apoyo -> Tutoriales , a principios de semestre se subió una guía de cómo solucionar el problema que mencionas y cómo evitarlo.

[https://github.com/IEE2463/classroom/blob/master/Material%20de%20apoyo/Tutoriales/Soluciones_AVR.pdf](url)
