### ISSUE TITLE
Valores Struct

### ISSUE THREAD

**Issue by Destloch** [IEE2463/classroom#13]
Hola!
Ya avanzado el código de la Task 2(MSP430), me doy cuenta que estoy fallando en los valores asignados en de los Struct. Creo un nuevo proyecto lo más básico posible solo para ver este punto,  los valores que se suponen que deberían tener las variables de mi struct no coinciden cuando hago el debug. 
Según yo los valores deberían ser: 
x=1,            y=2,     z=2 
y no:
x=17422     y=0 ,    z= 129
Según lo que muestra el debug :(

![b06d77cc1b6c0c17c2588a49c43bec31](https://user-images.githubusercontent.com/48366013/56465370-fb778080-63c9-11e9-85d0-90a587241125.png)

Foto: [https://i.gyazo.com/a85e345835566cfb7237c1be09a8222b.png](url)

**Comment by xDanman** [comment]
Hola!  Avanzaste con el debug a la linea donde iniciaste tu variable struct? Normalmente se actualiza cuando pasas la ejecución. De todas maneras yo tengo el mismo problema cuando se ejecuta UART_Init(...config), los valores de config se cambian arbitrariamentesiendo que debieran ser los mismos de la variable que tomo como argumento, aunque a la hora de las operaciones dentro de la función, se respetan los valores originales(en tu caso {1,2,3}), por lo que no debería haber problema.

**Comment by Destloch** [comment]
Hola!
Tienes razón, guardé las variables del Struct en otras variables (int valorX = variable.x) y lo guarda con los valores que corresponden.
