### ISSUE TITLE
git

### ISSUE THREAD

**Issue by JavieraSanMartin** [IEE2463/classroom#13]
Espero que estén bien. 

Escribo porque no puedo subir desde git el archivo del laboratorio al repositorio. 
Me sitúo en la carpeta donde tengo el archivo. git init, git add Hello_world_atmega.c (así se llama mi archivo .c),  git remote add origin https://github.com/IEE2463/laboratorio-01-JavieraSanMartin.git,  git push -u origin master y con esta última linea me tira un error (failed to push some refs to  https://github.com/IEE2463/laboratorio-01-JavieraSanMartin.git') Me podrian ayudar por favor?

Me quedo atenta.
Saludos
Javiera

**Comment by fffonceca** [comment]
Hola Javiera, te comento: a ti se te fue asignado un repositorio el cual debes clonar con el comando.
`git clone link_de_repositorio`
Ese repositorio es (como lo dice el nombre) una clonación del repositorio online que está en github, y por lo tanto, no es necesario usar el código INIT (que inicia un nuevo repositorio local).
Posterior a esto, en esta clonación debes usar los códigos normales para subir un archivo (add, commit, push) el push debe ser: git push origin master (prueba con eso).
Espero que esto te ayude, nos vemos!.
