### ISSUE TITLE
Entrada a un If

### ISSUE THREAD

**Issue by jnopazo** [IEE2463/classroom#13]
hola, tengo una duda. Si tengo "if(P4IN & BIT0)" significa esto "//P4.0=1" (según el ejemplo de la clase), pero mi duda es ¿Qué condición debería poner para tener esto  "//P4.0=0" ?. Mi duda radica principalmente en que no sé cómo dar una condición sólo cuando el botón es presionado. Cabe destacar que cuando el botón no esta presionado el programa siempre entra en esta condición "if(P4IN & BIT0)".

**Comment by vicentebelgeri** [comment]
Prueba con if ( !(P4IN & BIT0)), que vendría siendo el negado (cuando se presiona)

**Comment by jnopazo** [comment]
gracias, ahi funciono
