### ISSUE TITLE
Duda con respecto a usar códigos encontrados online

### ISSUE THREAD

**Issue by RafaelOrmazabal** [IEE2463/classroom#14]
Si encuentro en google como hacer una lista de datos, se puede usar esa linea de código? Aun no me queda claro que cosas que encontremos en internet podemos usar y cuales no.

**Comment by porellanau** [comment]
Hola!

Cualquier código que presentes será válido siempre y cuando entiendas su funcionamiento. Si vas a usar código que encontraste en Internet recuerda referenciarlo en alguna parte de tu programa :)

Saludos!

**Comment by RafaelOrmazabal** [comment]
Muchas gracias.
