### ISSUE TITLE
largo de string 

### ISSUE THREAD

**Issue by vaalvarado** [IEE2463/classroom#15]
el largo del string el cual se debe enviar y posteriormente recibir desde el terminal no sale especificado en el enunciado. Comprendo que la idea es generar una linked list para que podamos recibir un string de tamaño indefinido, pero segun el main que se nos subio debe para en un momento de recibir y transmitirlo diciendo "I received this line: ". como fijamos eso ?

**Comment by akaminetzkyp** [comment]
Hola!

Estás en lo correcto. El string que recibes es de largo indefinido. Podrías marcar el fin de tu string enviado con un salto de línea (`\n`). Cuando tu microcontrolador reciba ese caracter, sabrá ya recibió todo.

Saludos!
