### ISSUE TITLE
Duda con respecto a tipos de variables

### ISSUE THREAD

**Issue by RafaelOrmazabal** [IEE2463/classroom#15]
Estaba viendo un tutorial en youtube y en este se menciona que se recomienda declarar los números expresados en hexadecimal como una unsigned char variable y no como int. Saben porque es asi?

**Comment by fffonceca** [comment]
Hola Rafa. El motivo principal es el uso y la cantidad de espacio que toman estas variables. Te recomiendo ver la cantidad de espacio que usa cada una de estas variables para que hagas la comparación justa, esto es importante, ya que las variables utilizan espacio en la RAM que es necesaria después. El tema de unsigned o signed es si es positivo o negativo, sin embargo, insisto en que veas documentación al respecto para que te quede más claro.

**Comment by RafaelOrmazabal** [comment]
Muchas gracias, tienes alguna recomendación de donde partir investigando?

**Comment by fffonceca** [comment]
Yo partí por esta página que ayuda bastante:
https://www.tutorialspoint.com/cprogramming/index.htm
