### ISSUE TITLE
Linked list a string

### ISSUE THREAD

**Issue by fnberrios** [IEE2463/classroom#16]
Hola! La idea de la función USART_Receive_String es ir recibiendo cada carácter y luego con ellos formar una lista enlazada, para luego retornar un string formado por la lista, no?

**Comment by akaminetzkyp** [comment]
Hola! Cuando se llama `USART_Receive_String`, el microcontrolador debe recibir caracteres hasta que detecte el fin del string (con un `\n`, por ejemplo). Los caracteres que se reciban deben ser almacenados en una lista ligada.

La función `USART_Receive_String` podría retornar el puntero del primer nodo de la lista ligada. De esta manera, puedes entregarle ese puntero a la función que transmite el string.

**Comment by aamacaya** [comment]
Hola!  y cuando transmitimos el string tenemos que ir vaciando la lista ligada? si es asi, el priceso de vaciar la lista tiene que ir dentro de la funcion USART_Transmit_String(string);?

**Comment by Slothzilla328p** [comment]
Si el mensaje es información que no utilizarás más tarde, eliminarla mediante "popeos" es una opción.
