### ISSUE TITLE
Especificaciones para escala de luz 

### ISSUE THREAD

**Issue by DiegoRobinoSchutze** [IEE2463/classroom#16]
Estimado (a):
En el task 2, ¿es necesario que el LED sea más brillante cuando más luz le llega al fotorresistor? ¿Podría ser al revés, es decir, que cuanto más oscuro esté el fotorresistor, más brillara el LED?

Gracias de antemano.

**Comment by CamilaTurrieta** [comment]
@DiegoRobinoSchutze la respuesta a la primera pregunta es un sí; y esto sale en la parte de los requerimientos del task 2. Adjunto foto: 
![image](https://user-images.githubusercontent.com/48395528/64481606-5c52fa00-d1ad-11e9-8909-1c11275c6858.png)
