### ISSUE TITLE
Grupos LAB 05 

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#16]
Hola a todos, 
Pueden utilizar esta Issue para unirse en grupos aquellos que aún no lo han hecho. 

Saludos !

**Comment by Kullak** [comment]
Hola mi nombre es Sebastian Kullak y busco para pareja para el laboratorio 5 y eventualmente para el proyecto. Mi mail es smkullak@uc.cl .

**Comment by JoseAlvarez123** [comment]
Holaa, me llamo Jose Alvarez y busco grupo para el Lab 5. Espero que no sea demasiado tardee. Aqui dejo mi correo: jjalvarez@uc.cl, Saludos!

**Comment by Kullak** [comment]
Te mandé un mail
