### ISSUE TITLE
Malloc no encuentra memoria libre

### ISSUE THREAD

**Issue by Destloch** [IEE2463/classroom#17]
Hola!
Estoy trabajando con la MSP430. Al momento de guardar lo leído por el Rx en una Linked List, solo me funciona como para 15 lecturas/caracteres.  El Malloc luego de eso no encuentra más memoria, siendo que la tarjeta tiene 128KB y el programa ocupa cerca de 1,5KB. 
¿A alguien le ha pasado lo mismo? ¿Como lo solucionaron?

**Comment by fffonceca** [comment]
A mi me ha pasado lo mismo, y me di cuenta que el funcion PUSH está mal, osea la funcion malloc no asigna información después de cierta cantidad de carácteres, para mi fueron 20. La solucion creo que lamentablemente es ir limpiando esta linked list despues de haber encontrado 20 y seguir asi hasta completar el char completo.

**Comment by Destloch** [comment]
Me surgió una duda. Si vas limpiando la Linked List, estos valores se pierden o los almacenas de alguna forma? se supone que ya no hay memoria. La solución sería transmitirlos de inmediato pero no permitiría la recepción de texto casi indefinido para luego transmitirlo.

**Comment by fffonceca** [comment]
Exacto, la idea de limpiar la linked list es practicamente tomar cada nodo y borrarlo de la memoria. Eso si no me equivoco es la función free(node). Eso limpia toda la estructura.

**Comment by mscuturrufo** [comment]
Holaa, creo tener el mismo problema. Si van limpiando la linked list, cómo guardan los valores para no perderlos?

**Comment by Slothzilla328p** [comment]
**En teoría**, no debería haber problemas con la cantidad de caracteres recibidos en la linked list. Honestamente desconozco el comportamiento de la MSP430, pero es raro que eso suceda. Probablemente el problema resida en la asignación de memoria/data a la linked list, o en las funciones de push y pop implementadas.
