### ISSUE TITLE
Problema con Timers en MSP430

### ISSUE THREAD

**Issue by EnzoBH** [IEE2463/classroom#17]
Estimados,

En la task 1 usé el MSP430. Tengo el ADC modulando la PWM de uno de los timers correctamente. El problema es que cuando pruebo otro timer no funciona. Me funciona el TA2.1 únicamente. Revisé los pines, la configuración del timer, etc. No sé qué más intentar o qué estoy omitiendo.

**Comment by CamilaTurrieta** [comment]
@EnzoBH no se si ya solucionaste el problema.... pero si aún no e ir cachando qué podría estar pasando y entenderte mejor.... ¿Probaste haciendo funcionar las PWM de los 3 timers por separado ? (esto es como para saber si el problema te ocurre al juntarlos) o ¿Sólo logras modular la PWM con el ADC para sólo un timer (sea juntos o por separado)? ¿Que timers estas tratando de usar (¿cuáles son los que no funcionan? )?

**Comment by EnzoBH** [comment]
Lo solucioné. Gracias por la respuesta. Si hay algún interesado era por la forma en que definía el duty cycle (los TAxCCRy).
