### ISSUE TITLE
LAB 02 - Dudas enunciado

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#17]
Espacio para dudas relacionadas con el enunciado y entrega.

**Comment by CamilaTurrieta** [comment]
Hola @IEE2463/estudiantes, había un pequeño error con el número de los task del enunciado. Las instrucciones son las mismas solo se le sumo 1 al número de cada task. A modo de recordatorio las fechas de entrega para cada uno respectivamente son: 

![image](https://user-images.githubusercontent.com/48395528/92667969-d8fa4600-f2e3-11ea-8bb6-7257d085f801.png)

Espero esta información no haya traído demasiados problemas. 

Ánimo con el lab!

**Comment by Eduxardo** [comment]
No me quedó claro ¿el task 2 son los que antes eran los dos 1 y el 3 el que
era el task 2 ?

**Comment by CamilaTurrieta** [comment]
Hola @Eduxardo! es bien confuso pero el cambio es el siguiente: 

| Antes | Ahora | Breve descripción del Task |  
| ------------- | ------------- |------------- |
| Task 1 | Task 2 | Secuencia RGB en assembly y en C |

| Antes | Ahora | Breve descripción del Task |    
| ------------- | ------------- |------------- |
| Task 2 | Task 3 | Secuencia RGB con botones |

Por eso es como un +1 al número del task.  Entonces, lo que deben entregar es el task 2 (16 de septiembre) y task 3 (5 de octubre).

**Comment by angelux666** [comment]
En la parte visualización de arreglo se refiere que la primera vez que se muestre la secuencia los led status deben estar apagados, luego la segunda vez que se muestre la secuencia el led 2 se encenderá y así sucesivamente como dice la tabla?

**Comment by GutiJos** [comment]
@angelux666 exacto!

**Comment by angelux666** [comment]
@GutiJos ya gracias
