### ISSUE TITLE
Lab 5: Frecuencia de 400kHz

### ISSUE THREAD

**Issue by Arturovidalr** [IEE2463/classroom#17]
¿Es necesario que la frecuencia del I2C sea exacta de 400kHz? 
Lo digo porque, como la fuente es SMCLK (~1MHz), con el baud rate puedo dividirlo por un número entero:
- ~333kHz, si elijo baud rate de 3.
- ~500kHz si elijo baud rate de 2.

En caso de ser necesario, ¿cómo lo puedo implementar?

**Comment by felipesanchezvaras** [comment]
@Arturovidalr 
Para complementar a Alvaro, dejandolo en 333 kHz, debería estar bien. 

Saludos,
