### ISSUE TITLE
MSP no responde

### ISSUE THREAD

**Issue by DiegoRobinoSchutze** [IEE2463/classroom#18]
Estimado (a):
Haciendo las arreglos finales de mi código, cuando ejecutaba el comando _flash_, la placa repentinamente se apagó. He desconectado todos los cables, pero al conectarla al computador ésta no se reconoce. Adjunto los errores que han aparecido. Considerar que ya he probado otros cables, computador, etc. Lo que pienso es que el programa cargado se guardó mal, tal vez haya una manera de resetear la tarjeta a fábrica.

![image](https://user-images.githubusercontent.com/53894054/64495011-ac43c680-d26a-11e9-9f04-fe4e9b3d09de.png)

![image](https://user-images.githubusercontent.com/53894054/64495004-959d6f80-d26a-11e9-8722-5b4bab33a53c.png)

**Comment by felipesanchezvaras** [comment]
@DiegoRobinoSchutze 

Puedes intentar el reset que te aparece ahí. Lo que llama la atención, es que dice que has excedido los límites del puerto, al conectar el MSP, se enciende alguna luz en la placa? Porque puede ser también de que se haya producido un corto circuito.
