### ISSUE TITLE
Pasar de Receive_String() a Transmit_String()

### ISSUE THREAD

**Issue by tomasladrix** [IEE2463/classroom#18]
Hola! Tengo un problema y es que no logro enviar el string por medio de mi función USART_Transmit_String() que funciona recibiendo como argumento un string normal (como en el lab pasado). Ya tengo lo que se recibe en una linked list pero no me resulta pasarlo a un array de char y luego usarlo como argumento para USART_Transmit_Char(). De hecho, me envía sólo el primer elemento del array. ¿Algúna idea en qué estoy haciendo mal o cómo hacer para mandar el array completo?
Gracias de antemano

**Comment by Destloch** [comment]
Hola!
En mi caso particular no fue necesario pasar los datos a un array , los puedes enviar directamente desde el nodo. Revisa esta URL, a mi me sirvio bastante
[https://www.geeksforgeeks.org/linked-list-set-2-inserting-a-node/](url)

**Comment by tomasladrix** [comment]
Pero para que eso sirva modificaste la función USART_Transmit_String() para que recorriera todos los nodos o no? Entonces no podrías ingresarle un string normal para que lo transmita?

**Comment by Destloch** [comment]
No, esa la deje para poder enviar mensajes en la consola y saber hasta donde se ejecutaba el codigo. Hice otra funcion para poder enviar el data de los nodos.

**Comment by tomasladrix** [comment]
Ah ya perfecto. Al final me resultó pasando del linked list a un array pero tuve que utilizar un doble puntero para poder modificarlo dentro de la función USART_Receive_String(). Gracias de todas maneras!
