### ISSUE TITLE
Tutorial AVR

### ISSUE THREAD

**Issue by cefernandez1** [IEE2463/classroom#18]
Hola, donde se encuentra el tutorial AVR(por Marcelo Guarini)?. Gracias de antemano.

**Comment by porellanau** [comment]
Hola!

El tutorial se encuentra en Canvas, en la sección de archivos.

Saludos!

**Comment by RafaelOrmazabal** [comment]
![Capture](https://user-images.githubusercontent.com/61999738/77209581-55526000-6add-11ea-8966-add4a2ed6474.PNG)

**Comment by RafaelOrmazabal** [comment]
No veo la sección de archivos

**Comment by mfbarahona** [comment]
Hola, revisa el Material Complementario en Módulos.

Saludos

**Comment by Jbijit** [comment]
Hola, en que parte? lo acabo de buscar y no lo encuentro. No hay ningún archivo con el nombre de tutorial AVR.

Saludos.

**Comment by mfbarahona** [comment]
@Jbijit GuiaAVR = Tutorial AVR

Saludos

**Comment by Jbijit** [comment]
@mfbarahona 

Tengo abierto Canvas y en la sección de módulos y no hay ningún archivo con ninguno de los 2 nombres.

Saludos

**Comment by porellanau** [comment]
Hola!

¿Podrías mandarme un pantallazo de la sección de módulos? Está al final! :smiley:

Saludos!

**Comment by Jbijit** [comment]
Acabo de actualizar la pagina de nuevo y me aparecieron los nuevos archivos!

Muchas gracias!!
Saludos!
