### ISSUE TITLE
Función wait_for_complete

### ISSUE THREAD

**Issue by Arturovidalr** [IEE2463/classroom#19]
Hola! Todavia no me queda claro para qué es la función I2C_wait_for_complete.
¿Qué es, específicamente lo que debe esperar? ¿Cuales son las interrupciones que me pueden servir?

**Comment by aolivares12** [comment]
Hola!

Como su nombre indica, el wait for complete es una función que permite esperar que terminen las operaciones que realizamos al momento de transmitir I2C. Como esta es un método de comunicación serial, se van mandando bits de forma secuencial, donde cada bit tiene un significado. Por ello, es necesario esta función para verificar que una función termine antes de empezar la otra. 

Como recomendación, te recomiendo leer los diagramas de tiempo que contiene el manual de usuario acerca de I2C, a su vez como todos los registros que contienen y que ayudan a generar esta verificación de término de instrucción. En la ayudantía también se habló de eso, por lo que te recomiendo echarle una mirada!

Saludos, y estoy atento a más dudas.
