### ISSUE TITLE
ERROR : Assignment from incompatible pointer type

### ISSUE THREAD

**Issue by fnberrios** [IEE2463/classroom#19]
Hola, tengo mi código desarrollado ya y subido en Git Hub, pero al momento de compilarlo me aparece este error "Assignment from incompatible pointer type" en algunas lineas especificas, he buscado como solucionarlas pero no ha sido efectivo. Saben que puede ser?

**Comment by fffonceca** [comment]
No sale en que posición específica del código tienes el error? podría ser facilmente un error de tipeo, donde le otorgas un tipo de variable distinto a una función o a un return.

**Comment by fnberrios** [comment]
En el USART_implement_me.c son 3 lineas, la 150,133 y 120

**Comment by fffonceca** [comment]
no soy ayudante asi que no estoy seguro si puedo acceder a tu código, pero es probable que le estés dando a una función una variable que no le pertenece, para ser más precisos con punteros incorrectos. algunas veces tus funciones van a recibir un puntero, o podrían recibir el puntero de un puntero y necesiten otra forma de manejarlo (y de darle parámetros). Fijate bien los valores que les das a las funciones y las que retornan y ve si coinciden los type

**Comment by fnberrios** [comment]
Gracias!
