### ISSUE TITLE
Articulo de medium 404

### ISSUE THREAD

**Issue by vextraz** [IEE2463/classroom#2]
Buenas, en el link incluido en el pdf del Lab 0, 

> https://medium.com/@randerson112358/how-to-run-c-program-in-command-prompt-e435186cd16

sale un 404

**Comment by felipesanchezvaras** [comment]
Hola ! 
Ya está solucionado, el link correcto es 
https://medium.com/@randerson112358/how-to-run-c-program-in-command-prompt-e435186cd162
