### ISSUE TITLE
Entrega de circuito tinkercad

### ISSUE THREAD

**Issue by cefernandez1** [IEE2463/classroom#20]
Hola, lleve a cabo la actividad principal del laboratorio y el bonus en circuitos distintos. ¿Puedo poner los dos link en el google form que se publicó o debo hacer que el bonus funcione en el mismo circuito?

**Comment by jdiaztoledo** [comment]
Hola, 

De preferencia, dado que la actividad principal del laboratorio es solo prender el led de la placa, sería mejor que estuviese todo en un solo link (bonus y actividad principal), sin embargo, tampoco hay problemas si subes ambos links por separado. Recuerda subir ambos códigos a Github.

Saludos :)
