### ISSUE TITLE
Proyecto: duda con tamaño del tablero

### ISSUE THREAD

**Issue by NikiHV** [IEE2463/classroom#20]
Hola!
Tenemos una duda con lo que se indica en el enunciado del proyecto, respecto al tamaño del tablero. Se dice que "El tamaño mínimo del tablero es de 5×5, pudiendo expandirse", ¿esto significa que el tamaño del tablero es fijo y cada grupo lo define con requisito de que sea mínimo de 5x5? ¿o significa que el tamaño es variable y que debe haber una opción en el juego que permita expandir el tamaño del tablero?

**Comment by mwoolvett** [comment]
Hola!
Basta con que el tamaño del tablero sea fijo de mínimo 5 de ancho y alto
