### ISSUE TITLE
Manejar variables globales desde interruptores

### ISSUE THREAD

**Issue by fffonceca** [IEE2463/classroom#20]
Quiero manejar una variable global que pueda manejar tanto la funcion MAIN como un #pragma vector de los interruptores. Como defino la variable? Me han dicho que la debo manejar como volatile, sin embargo, no consigo muchos resultados o me falta manejo con la declaración de variable. Alguien ha hecho alguna aplicación o sabe alguna fuente para manejarme(BBB)?

**Comment by Destloch** [comment]
Yo la definí antes del main() y me sirvió para lo mismo que quieres. No fue necesario definirla como volatile en mi caso.

**Comment by fffonceca** [comment]
ponte tu.... hiciste un:
int value = 0;
void main(void){
...
}
#pragma vector = ..
__interrupt...
switch(case)
    case X:  value++;

**Comment by Destloch** [comment]
Si
