### ISSUE TITLE
LAB 02 - Espacio colaborativo.

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#20]
Este es un espacio para colaborar con ideas que podrían ser útiles para todos.

## Assembly
En el caso de Assembly, los siguientes links contienen buenos ejemplos y pueden ser una guía para abordar el problema.

MSP430 assembly part 1: Blinking LED hello world
https://blog.dexterhaslem.com/msp430-assembly-part-1-blinking-led-hello-world

launchpad msp430 assembly language tutorial
http://robotics.hobbizine.com/asmlau.html

## C

Resource Explorer & TI Cloud
https://dev.ti.com/

**Comment by contranton** [comment]
Hola, encontré esta serie de cursos/workshops diseñados por TI para la MSP430 en particular. Si tienen tiempo, se ve súper completo y didáctico y viene con videos y un workbook en pdf (de 600+ páginas, pero está lleno de imágenes y ejercicios).

- [MSP430 Workshop Series](https://training.ti.com/msp430-workshop-series)
- [Course Workbook (pdf)](http://software-dl.ti.com/trainingTTO/trainingTTO_public_sw/MSP_Design_Workshop/MSP_Design_Workshop.pdf)

Demás que también será súper útil para los siguientes labs :D
