### ISSUE TITLE
Lab 4 duda sobre distinguido

### ISSUE THREAD

**Issue by vzmunoz** [IEE2463/classroom#21]
Hola! tengo una duda de enunciado, en la guía sale: _"Para optar a distinguido en este laboratorio debe realizar dos ideas distintas entre si y respecto a laboratorios anteriores."_

Con esto, entiendo que hay que hacer un distinguido distinto en cada placa, pero la parte de _"respecto a laboratorios anteriores"_ se arrefiere a relacionarlo con labs anteriores o que sea distinto de lo que se considero distinguido en labs anteriores?

**Comment by CamilaTurrieta** [comment]
Hola @vzmunoz, correcto la primera parte; las ideas para distinguido deben ser distintas para ambas placas. Y además, que sea distinto de lo que se ha considerado distinguido anteriormente. La idea es que realmente representante un trabajo adicional o un modo diferente de usar los conceptos.
