### ISSUE TITLE
Lab6 primer mensaje "Please send some..."

### ISSUE THREAD

**Issue by aamacaya** [IEE2463/classroom#21]
El primer mensaje que se envía desde la placa por default:

USART_Transmit_String("Please send some characters from your terminal.\r\n\r\n");

Debe ser enviado por medio de interrupciones también? o no es necesario y puede ser enviado como en los labs anteriores?

**Comment by fnberrios** [comment]
Hola, si mal no recuerdo en Task 1.2 te piden implementar interrupciones para las funciones USART, entonces supongo que tendrás que usar las nuevas funciones y bueno si logras implementarlas supongo que te conviene usarlas, pues si usas USART_Transmit_String de los labs anteriores deberás tener 2 funciones Transmit en el USART_implement_me.c

**Comment by fffonceca** [comment]
Creo que no tiene sentido darle una connotación de linked list a esta parte, porque si quieres escribir practicamente eso desde tu uC deberás de alguna forma guardar esa informacion en la linked list y despues recorrerla para poder mostrarla posteriormete, que seria lo mismo que solamente mandarlo con un USART_Transmit_String("...."); incluso peor porque guardas más información y es muy ineficiente.
