### ISSUE TITLE
Aclaración con respecto a interrupciones task 1.1

### ISSUE THREAD

**Issue by fffonceca** [IEE2463/classroom#22]
Una consulta con respecto a las interrupciones de la task 1.1:

Tanto el apretado como el soltar del boton nos deben conducir a la interrupcion misma? o solamente una acción de apretar el boton debe accionar la interrupcion y dentro de esta algun algoritmo para imprimir las cosas pedidas?

**Comment by loky32** [comment]
Hola, eso depende de tu implementación, lo que debe ocurrir si o si es que al presionar el boton se active la interrupción de pin, dentro de ella puedes hacer lo que estimes conveniente para gatillar la interrupción de comunicación. En ese sentido puedes hacer que el apretar o soltar llame a la interrupción de pin y el tipo de estado en el que estés puedes guardarlo en alguna variable y dependiendo de esa variable que activa tu interrupción de comunicación puedes escoger el mensaje "presionado" o "soltado".
