### ISSUE TITLE
Mostrar 3 dígitos al mismo tiempo con 7 segmentos

### ISSUE THREAD

**Issue by Incruen** [IEE2463/classroom#23]
Hola!

Tengo una duda sobre cómo usar los 3 dígitos del display al mismo tiempo. Todas las soluciones que he visto por internet funcionan usando un delay corto. ¿Es válida esta solución aunque en el task 2 se prohíba el uso de delays para hacer el debouncing? 

Además, mostrar los 3 dígitos con este delay influiría en la precisión del timer que debemos programar cierto?

Jorge

**Comment by felipesanchezvaras** [comment]
Jorge, 

Lo que se hace para mostrar los 3 dígitos al "mismo tiempo", es producir un efecto visual que al observarlo con nuestros ojos, permite pensar que están los 3 encendidos al mismo tiempo, aunque esto no sea así. Tanto en el Task 1 como en el Task 2 está **prohibido** el uso de funciones nativas de delays, como `__delay_ms(100);` ó `for(i = 10000; i>0; i--);` o similares.

Debes pensar que solicitamos desplegar la imagen en el display, realizar el debouncing y mostrar el tiempo, estas 3 actividades deben ser coordinadas por Interrupciones de timers. Es tu decisión si las realizas con solo 1 timer o decides utilizar más de uno (dependiendo de cada uC, es la cantidad de Timers que tienen). Por lo que esto no debería afectar la precisión del timer, ya que como mencioné más arriba, **no puedes** utilizar funciones nativas de delays.

Felipe

**Comment by Incruen** [comment]
Entendido, gracias!

**Comment by felipesanchezvaras** [comment]
Mantendremos esta Issue abierta ya que contiene información útil para otros alumnos.
