### ISSUE TITLE
Duda timers- contadores

### ISSUE THREAD

**Issue by Michel1297** [IEE2463/classroom#24]
Hola, se me hace un poco dificil crear contadores de tiempo usando los timers. No se por donde partir jajaaja ¿ Alguien tiene o ha visto algún material bueno para aprender a usar los timers? saludos!

**Comment by fjhuanca** [comment]
@Michel1297 Hola Michel, mira la verdad es que si manejas algo de inglés vas a encontrar en YouTube videos muy claros y específicos para el Atmega 328p. Si no es así, también hay en español pero a mi parecer menos claros y mucho menos cantidad que en inglés, por lo que en ese caso acudiría a una búsqueda en Google. Saludos y éxito.

**Comment by Michel1297** [comment]
gracias!! ya encontré algunos buenos !
