### ISSUE TITLE
LAB7: Formato de tiempo Task2.2

### ISSUE THREAD

**Issue by LucasMaulen** [IEE2463/classroom#24]
Cuando se dice que si el tiempo es inferior a 1 segundo se debe mostrar el formato 999. se refiere a que se debe mostrar la cantidad de milisegundos en que el botón se mantuvo presionado (por ejemplo si se mantuvo medio segundo mostrar un 500.), o solo se debe mostrar el mensaje 999. en el display siempre que el tiempo sea inferior a 1 segundo?

**Comment by felipesanchezvaras** [comment]
Se refiere a que debe mostrar el tiempo en milisegundos, el formato se refiere principalmente a donde está ubicado el punto, a modo de ejemplo, si se presionó  el mensaje por 435 ms, debe mostrar

![screenshot (1)](https://user-images.githubusercontent.com/7042467/57549528-c65baf80-7331-11e9-8f20-ae629c388e1d.png)

Por otra parte, si se presionó por 82 ms, debe mostrar

![screenshot (2)](https://user-images.githubusercontent.com/7042467/57549545-d2477180-7331-11e9-890c-8a5f018f93cb.png)

Ahora, si el tiempo es mayor a 1 seg, perderemos la resolucion de ms, para darle prioridad al tiempo en segundos y usar al menos 2 decimales, por ejemplo, si el tiempo que mediste es 1,487 seg, truncas el último dígito y debes mostrar 

![screenshot (3)](https://user-images.githubusercontent.com/7042467/57549607-06229700-7332-11e9-9cc4-2cd27d9ea5dd.png)

Saludos, 
Felipe
