### ISSUE TITLE
Duda con respecto a referencias

### ISSUE THREAD

**Issue by RafaelOrmazabal** [IEE2463/classroom#25]
Si aprendi a usar una función del micontrolador, tal como iterrupciones o timers de un fuente de internet, pero aplique lo que aprendí de otra forma o para otro proposito, de todas formar tengo que citar la fuente? Pregunto esto porque me parece que este tipo de información es esencial para desarrollar cualquier trabajo de este ramo, y no estoy seguro si necesito citar o no la fuente. Finalmente, en caso de que si tenga que citar, basta con incluir el link de la fuente o tenemos que usar formato APA?

**Comment by fffonceca** [comment]
Basta con incluir el link, y justificar apropiadamente cada línea de código que utilizas de este.
