### ISSUE TITLE
Archivos para MSP430

### ISSUE THREAD

**Issue by Destloch** [IEE2463/classroom#25]
Hola!
Seria posible que suban o tienen  los archivos de Task 1 y Task 2 para la MSP430? 

Si se quiere ocupar la MSP430 no basta con modificar las librerías propias y encabezados de archivos, hay que cambiar los archivos que están en PetiteFatFilesystem. Sino para empezar directo con la ATmega.

**Comment by felipesanchezvaras** [comment]
Hola!
Lamentablemente no tenemos los archivos de ambas Task para el MSP430, pero eres libre de intentar modificar los archivos de forma que sea posible usar este microcontrolador.

Saludos,
Felipe
