### ISSUE TITLE
Problemas con MSP

### ISSUE THREAD

**Issue by carlafonfach** [IEE2463/classroom#26]
![F6F743D5-D466-4CC8-90DF-830A4CDB37B3](https://user-images.githubusercontent.com/48355990/66443516-cdd4d100-ea15-11e9-93b6-6adb812b167c.JPG)
Hola!... no se que problema tengo, intente cargar algo muy básico para revisar como funciona la placa, ya que tuve problemas en cargar códigos en el laboratorio 4

**Comment by felipesanchezvaras** [comment]
@carlafonfach 
¿qué métodos has probado ? 
En estos casos puede ser útil probar con la tarjeta de algún compañero para descartar si el problema es con tu computador o no. 

Dejar configuración por defecto de CCS, podría ser útil también.

**Comment by felipesanchezvaras** [comment]
Se procede a cambiar microcontrolador
