### ISSUE TITLE
TASK1 LAB8

### ISSUE THREAD

**Issue by CamilaTurrieta** [IEE2463/classroom#26]
A alguien le pasó que al realizar el task 1 sólo se queda el terminal en lo siguiente:

> Hello! This is the SD card test.
>                                                
>                                  Trying to mount the SD card's file system:  

 ???
Según yo tengo bien inicializado los módulos de spi, el uart sé que esta correcto y las conexiones también creo que están correctas.  Si alguien me puede ayudar sería genial :D

**Comment by xDanman** [comment]
Tiene que ver con tu recieve del SPI. Tienes que considerar una característica principal de la recepción de datos por SPI, el slave no puede iniciar la comunicación.

**Comment by CamilaTurrieta** [comment]
Toda la razón ! Gracias :D Problema resuelto 💃

**Comment by Destloch** [comment]
Me pasó lo mismo y no entendí como solucionarlo :c

**Comment by CamilaTurrieta** [comment]
Básicamente lo que ocurre es que el slave no puede iniciar la comunicación. Entonces, cuando realizas tu función recieve spi, necesitas que se genere, por ejemplo, un clock que active la comunicación, para luego recibir un dato del slave al master. Entonces, la idea es que a la hora de recibir, se mande un primer dato por spi del master al slave, y luego se comience la recepción. Espero me hayas entendido. :D
