### ISSUE TITLE
Comunicación serial

### ISSUE THREAD

**Issue by martingallegos11** [IEE2463/classroom#27]
Hola, tengo un problema con la comunicación serial, estoy habilitando bien el UCA1 en sus registros y ocupando la misma función para transmitir datos ocupada en la ayudantia y no se porque en el RealTerm no muestra los caracteres que envio. Llevo mucho rato intentando y no se que podria estar mal, hasta intente con otro terminal serial y aun así no funciona, si alguien me pudiese dr una pista de que podria estar fallando

**Comment by LucasTorneria** [comment]
Hola, a mi me pasaba algo similar, tal vez es el mismo. El problema que tenía era que tenia los jumpers mal configurados en la MSP430, es decir:
![imagen](https://user-images.githubusercontent.com/81485729/121450710-42d67780-c96a-11eb-9558-cf022a5ef58b.png)
Y para que funcione la comunicación tiene que estar en RXD y TXD, así:
![imagen](https://user-images.githubusercontent.com/81485729/121450782-5d105580-c96a-11eb-8b29-0a73940ea06d.png)

**Comment by martingallegos11** [comment]
Te pasaste! Muchas gracias ahora funciona perfecto!
