### ISSUE TITLE
Animales Espirituales

### ISSUE THREAD

**Issue by fffonceca** [IEE2463/classroom#27]
Llevo como 3 horas pensando en qué animales le corresponden a cada ayudante y todavía no cacho cuales asignar. El mono y el pescado están difíciles, ideas?

**Comment by CamilaTurrieta** [comment]
Llevas demasiado poco tiempo pensando. Mínimo debes pensar como 27 hrs en eso para asignar bien los animales de cada ayudante. Y buscar muuuuchaaa información!

**Comment by felipesanchezvaras** [comment]
@fffonceca 
![tumblr_omd7h45Ums1w73ry4o1_400](https://user-images.githubusercontent.com/7042467/58138941-81275f80-7c06-11e9-9d9f-463db987873f.jpg)
