### ISSUE TITLE
string enviado en el SDcardtest (Task 1)

### ISSUE THREAD

**Issue by ngsuarez** [IEE2463/classroom#28]
En el final de la prueba SDcardtest, hay que escribir y enviar un string por medio del USART, hay alguna condicion para el largo de este string o puede ser una palabra nada más?(ej: "hola")

**Comment by Destloch** [comment]
Hola!
Lograste hacer escribir algo que enviaste a traves de USART en la SD?
Si te fijas en el codigo del main, sale que:
`USART_Receive_String(message, strlen(message));`
Por lo que no estaría recibiendo a traves del USART, estaria ocupando el vector:

**Comment by ngsuarez** [comment]
A mi me funciona bien, solo que se sobreescribe el string de writeme2 con lo que yo le mande por USART. Por ejemplo, si envio "Este es un string de prueba ", el archivo queda sobreescrito así :
"Este es un string de prueba ear in your text file, you failed..."
Pensaba que había un requisito para que tan largo es el string que hay que enviar desde el terminal. (algo más largo que el vector antes definido).

**Comment by felipesanchezvaras** [comment]
Hola!
@Destloch , lo que tú dices acerca de que se sobre escriben caracteres es correcto, el mensaje no te estaba apareciendo completo por lo mismo, realizaré una modificación a esos archivos con más “#” .

@ngsuarez , respecto al largo mínimo que solicitamos por enviar a través de UART es algo que no especificamos en el enunciado, por lo mismo queda a criterio de ustedes, siempre y cuando nos informen cuál es el largo máximo que podamos enviar. Por ejemplo podrías definir que el largo sea de 30 y ese será el que probaremos. 

Saludos, 
Felipe

**Comment by Destloch** [comment]
@felipesanchezvaras  Hola! Tengo una duda. Para enviar el mensaje mediante USART tengo que modificar el SDcardtest.c? crear alguna interrupción esperando este mensaje?

Mi pregunta va a que en el archivo dado, el mensaje se escribe con pf_write el cual tiene como entrada "message" que es un vector ya definido. Y la parte en que se ocupa USART_Receive_String no influye en la escritura. Además, todo se ejecuta en secuencia hasta entrar a un loop infinito, sin esperar ninguna entrada por la consola.

**Comment by felipesanchezvaras** [comment]
Hola ! @Destloch 
En el task 1 no es necesario modificar el SDcardtest.c, en la línea 123 donde dice `USART_Receive_String(message, strlen(message));` aquí está utilizando message como el buffer de entrada para recibir los caracteres que le deseas enviar, finalizado por un *enter* ( `\n` ).  Lo que puedes hacer es que la función USART_Receive_String funcione de esta forma o como tú dices, implementar una interrupción. 

Lo que se revisará es que seas capaz de leer el archivo `SEPtest.txt` y desplegar su contenido, escribir el archivo `writeMe.txt` con el mensaje que aparece y que en el archivo `writeMe2.txt` seas capaz de escribir un mensaje en él enviado por UART, el cómo tu realices UART es decisión tuya, ya sea con interrupciones o esperando en un while hasta que llegue algún mensaje por consola.

Saludos,
Felipe
