### ISSUE TITLE
LAB 03 - Timers

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#28]
Espacio para las dudas relacionadas con la configuración y uso de Timers

**Comment by JavieraSanMartin** [comment]
Hola;

Espero que se encuentren bien. Les escribo porque estoy un poco confundida con el vector de interrupciones de timers. No entiendo a que hace referencia cada numero que aparece aquí

```
#pragma vector=TIMER0_A1_VECTOR
__interrupt void TIMER0_A1_ISR(void)
```

Ojalá puedan guiarme un poco. Me quedo atenta. Gracias de antemano. Saludos

**Comment by fffonceca** [comment]
Hola @JavieraSanMartin . Te explicaré cada parte, en la primera línea cuando se dice:

`#pragma vector=TIMER0_A1_VECTOR`

Estamos diciéndole al compilador que crearemos un vector de interrupciones, que será posteriormente unido o relacionado (linked) a la función que viene a continuación. Ya que, el compilador no tiene como saber como afectará las interrupciones a tu programa, por esto creamos un vector de interrupciones y lo unimos a su respectiva función para ser llamada en el momento de la interrupción. Es la forma especial que tiene para llamar las interrupciones la MSP430 con el lenguaje C y el compilador. También debo agregar que `TIMER0_A1_VECTOR` es efectivamente el vector de interrupciones del Timer A1 de la MSP430F5529.
En la segunda línea de código:

`__interrupt void TIMER0_A1_ISR(void)`

Creamos la función a la que entrará la interrupción y la llamamos de la forma que sea, por ejemplo: `TIMER0_A1_ISR()`, aunque la podríamos llamar de otra forma perfectamente, como: 

`__interrupt void foca_interrupcion(void)`

Espero esto te haya ayudado. UwU

**Comment by JavieraSanMartin** [comment]
Muuuuchas gracias :D me ayudó mucho

**Comment by tomaspinochetv** [comment]
Hola, estoy teniendo problemas con el timer A0, cuando intento hacer una interrupción con el, interrumpe pero nunca entra a la rutina por lo que nunca se limpia y quedo en un trap. Me tinca que quizas estoy usando mal el vector TIMER0_A0_VECTOR y no he logrado encontrarlo en ningún manual. ¿cual es el vector que tiene que usar? ¿El A0 tiene alguna maña especial para hacer interrupciones?
De antemano muchas gracias!!!

**Comment by tomaspinochetv** [comment]
Para complementar lo anterior, uso en buzzer  interrupciones con A1 y quiero poner interrupciones con A0 en el main.

**Comment by fffonceca** [comment]
Hola @tomaspinochetv . Te comparto mi experiencia. Cuando se cae en el trap es usualmente cuando no configuras bien los registros. Fíjate muy bien en el datasheet que estés configurando bien cada registro que necesita la interrupción y el timer. Fíjate también  en el modo que estás usando y trata de usar los registros pertinentes a ese modo.

No te puedo decir cuáles son los registros, pero el problema radica ahí. Avísame cómo te va con eso. Ánimo con la programación!

**Comment by JavieraSanMartin** [comment]
Hoola otra vez!

Espero que estén bien. Estoy intentando usar los registros TA1CCTL3 y TA1CCR3 y CCS me dice que no están definidos. No entiendo que estoy haciendo mal. Existen estos registros? según yo sí D:

**Comment by contranton** [comment]
@JavieraSanMartin 
Resulta que ese timer en particular sólo llega hasta CCR2. Revisa la páginas 65 a 68 del [datasheet](https://www.ti.com/lit/ds/symlink/msp430f5529.pdf) de la MSP, ahí puedes ver que TA0 llega hasta CCR4, TA1 llega hasta CCR2, TA2 llega hasta CCR2, y TB0 llega hasta CCR6.
