### ISSUE TITLE
Animales espirituales LAB 8

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#28]
Porque una sola foto no es suficiente, agregue aquí su animal espiritual para hacer una revisión más divertida :D 

![cat](https://user-images.githubusercontent.com/7042467/66969132-bec9d080-f05e-11e9-8cfa-0d18e66c2b49.jpg)

**Comment by loky32** [comment]
![perrito](https://user-images.githubusercontent.com/18247196/67168660-d796f680-f37c-11e9-8591-f753a5ab9e80.jpeg)
Yeei!
