### ISSUE TITLE
link de tinkercad

### ISSUE THREAD

**Issue by sebapulgar** [IEE2463/classroom#28]
hola muy buenas, tengo una duda sobre donde mandar el link de tinkercad ya que las instrucciones decía que había que enviarlo por el formulario google, pero no encuentro ningún formulario. Debo enviarlo mañana por el chat de google meet? o lo subo a mi repositorio personal?

**Comment by felipesanchezvaras** [comment]
El link se encuentra en Canvas, Semana 3. De todas formas lo puedes encontrar aquí. https://forms.gle/ZB7JECxRwSRb9gKYA

Saludos !
