### ISSUE TITLE
Problemas AVR

### ISSUE THREAD

**Issue by jdiaztoledo** [IEE2463/classroom#29]
Hola!,
Estaba trabajando en el laboratorio 8, y había logrado que los dos task a revisar funcionaran por separado, la cosa es que al momento de juntarlos y subir la solución a la placa me arroja el error del punto 3 del tutorial subido. Aun siguiendo lo que indica el tutorial como solución y lo que se sugiere en la issue https://github.com/IEE2463/classroom/issues/15, me sigue saliendo este error al reiniciar el debug: 

![image](https://user-images.githubusercontent.com/42197110/68066232-8dfec200-fd13-11e9-8bdc-b3b966fa2ba3.png)

Llevo mucho rato intentando arreglarlo, y estoy preocupado de que la placa tenga algún problema mayor:(

Cualquier ayuda para solucionar este problema lo agradecería.

Saludos!

**Comment by felipesanchezvaras** [comment]
@jdiaztoledo Te enviamos un correo, revisaremos la placa y consideraremos el cambio.
