### ISSUE TITLE
Task 2: Pasa nada con la TFT

### ISSUE THREAD

**Issue by Destloch** [IEE2463/classroom#29]
Hola!

Logro que el código se ejecute a través de USART pero no sucede nada con la TFT, solo que esté prendido el backlight. 
He hecho las modificaciones mencionadas abajo. Si se me pasó algo no logro encontrar qué. Si tienen alguna idea de lo que puede ser, se los agradecería :)

En "displaytest.c"
1. Agregar la iniciación del SPI.
2. Agregar la iniciación de ST7735.

En "SPI_implement_me.c"
1. Mantener el pin TFT_SC "low", que seria activado para la TFT.
2. Definir el puerto D/C según el valor del boolean en la función para transmitir. Siendo coherente con "SPI_implement_me.h". 

En "ST7735_commands.c"
1. Me asegure que el PIN de reset corresponda en software y hardware.

Saludos

**Comment by felipesanchezvaras** [comment]
Hola!
Asumiendo que lograste hacer funcionar de forma correcta la SD, la lógica para la pantalla se mantiene igual, solamente que agregando el puerto D/C controlado por el Boolean o según la función a transmitir.  ¿En “SPI_implement_me.c”, el valor de TFT_SC se mantiene siempre en “low” ? Tal vez lo que te está fallando tenga relación con eso. 

Está demás decir que revises que la conexión de cables esté bien hecha y que las asignaciones sean congruentes con lo que tienes en software y hardware.

Saludos,
Felipe

**Comment by LucasMaulen** [comment]
Un consejo (hrs perdidas por eso):
Aparte de lo que te indicó Felipe, recuerda configurar siempre el pin PB2 como salida (aun cuando no lo ocupes), ya que al parecer, cuando habilitas SPI en los registros de control respectivos, dicho pin toma automaticante el rol del SS complemento, por lo que al tener todo configurado para funcionar en Master mode, si no configuras ese pin como salida, puede tomar valores indeseados lo que enventualmente manda todo a la basura. Adjunto extracto del User Guide de AVR explicando lo anterior:
If SS is configured as an output, the pin is a general output pin which does not affect the SPI system. Typically, the pin will be
driving the SS pin of the SPI slave.
If SS is configured as an input, it must be held high to ensure master SPI operation. If the SS pin is driven low by peripheral
circuitry when the SPI is configured as a master with the SS pin defined as an input, the SPI system interprets this as
another master selecting the SPI as a slave and starting to send data to it. To avoid bus contention, the SPI system takes the
following actions:
1. The MSTR bit in SPCR is cleared and the SPI system becomes a slave. As a result of the SPI becoming a slave,
the MOSI and SCK pins become inputs.
2. The SPIF flag in SPSR is set, and if the SPI interrupt is enabled, and the I-bit in SREG is set, the interrupt routine
will be executed.

**Comment by Destloch** [comment]
@felipesanchezvaras  Logré que la SD funcionara correctamente. Con respecto al PIN TFT_CS, he visto otros ejemplos en la web donde incluso lo conectan directamente este PIN a GND ¿crees que hay que poner en HIGH este PIN(inhabilitar la TFT) en algún momento?  Las conexiones y asignaciones las he revisado bastante.

@LucasMaulen Lo tenia considerado pero no es eso, gracias de todas maneras.

**Comment by felipesanchezvaras** [comment]
@Destloch En algún momento deberás unir la SD con la pantalla, ambos dispositivos comparten la linea de MISO y MOSI del SPI, por lo que si siempre está en LOW el pin TFT_CS, estará constantemente recibiendo información por SPI, a pesar de que le mandes comandos a la SD por ejemplo. Por lo mismo, recomiendo que esta habilitación del pin TFT_CS se realice solo en el momento que le vas a enviar datos, así después volver a ponerlo en HIGH para deshabilitarlo cuando no estés en el proceso de comunicación.

**Comment by Destloch** [comment]
@felipesanchezvaras Entiendo pero eso seria para la Task 3. 
En el Task2 entiendo que no debería influir ya que no se ocupa la SD . Incluso sus PINs podrian estar desconectados ¿o no?

**Comment by ngsuarez** [comment]
@Destloch Si! Para efectos de testeo de la pantalla puedes no usar el pin correspondiente a sd (dejarlo desconectado ) y debería funcionar igual. (yo lo probé así primero)

**Comment by Destloch** [comment]
Ya lo solucioné. Por si le sirve a alguien:
Prueben los PINs de la placa tanto como HIGH o LOW. En mi caso, UN solo PIN se podía poner como OUTPUT HIGH pero no OUTPUT LOW...

**Comment by akaminetzkyp** [comment]
Qué bueno que lo solucionaste! Voy a dejar la issue abierta para que los demás puedan verla.

**Comment by aamacaya** [comment]
Hola! yo estoy con el problema que la pantalla me muestra ruido una vez se inicia todo (es siempre el mismo ruido).

Alguien tiene alguna idea de por qué se produce eso? todavía no logro saber si es problema de mi librería spi (que no debería ser ya que funcione bien en el task1 o si es problema de la función de inicialización del ST7735_comands.c o si es problema del displaytest.c

Cualquier pista para saber dónde probablemente está el problema se agradece!
