### ISSUE TITLE
Conexión display 7 segmentos

### ISSUE THREAD

**Issue by mlibarra** [IEE2463/classroom#29]
Hola, 
Al conectar los 3 display de anódo común, simulando el display de 3 dígitos del kit del curso, ¿La idea es que todos los segmentos estén encendidos si los conecté bien? o deben estar todos apagados? Me refiero a sin poner ninguna señal en los segmentos, sólo conectando alimentación.
Saludos

**Comment by fffonceca** [comment]
Si alimentaste las 7 señales de cada segmento y los 3 ánodos deberían estar todos prendidos siempre y cuando la polaridad sea correcta (recuerda que son leds, osea diodos los que manejas), si quieres investigar más a fondo debes ver documentación online y datasheets. Te quedará más claro viendo esto. Suerte en lo poco que queda!.
