### ISSUE TITLE
Code Composer Studio [debbuging]

### ISSUE THREAD

**Issue by tefuentealba** [IEE2463/classroom#3]
Hola, 
Tengo un problema al tratar de subir el código
 a el microcontrolador, al apretar "flash" como se indica en la guía obtengo el error de que no se puede abrir el archivo .out .Dentro de los errores que podian ser era que el archivo no se creara pero revise la carpeta donde esta el código y el archivo .out si existe.

![Captura](https://user-images.githubusercontent.com/53878538/63464290-f0426900-c42c-11e9-910e-84bf75a104f6.PNG)

**Comment by felipesanchezvaras** [comment]
Tomas, 
Una posible causa de que Code Composer no lo logre encontrar el archivo es porque tu nombre de usuario en el computador "Tomás" tiene un tilde en la "á", intenta guardar el archivo en alguna otra carpeta de forma que la dirección no contenga tildes. 

Junto con lo anterior, que otras posibles causas investigaste y posibles soluciones intentaste ? 

Felipe

**Comment by tefuentealba** [comment]
Felipe,
Si el problema era el tilde en el nombre del usuario, al crear uno nuevo funcionó inmediatamente.

Gracias!
