### ISSUE TITLE
LAB 01 - Planilla Readme

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#3]
@IEE2463/2021-i-estudiantes 

Como fue informado, para la revisión se les pedirá completar un README en sus repositorios. Este lo pueden completar hasta el día lunes 12 de abril a las 17:00 hrs. Cabe señalar que la entrega de código sigue manteniéndose para las 9:59 hrs y solo se permitirá actualizar el Readme del repositorio. 

# Completar la siguiente planilla

# Laboratorio 01

Nombre estudiante:   nombre apellido
Nro alumno: 123456j
Sistema operativo utilizado: Windows 10, macOS Big Sur, etc.
Compilador utilizado: Indicar el link si es que fue online o si es local, cuál utilizaron. 

## Resumen

| Criterio             | Ponderación  | Bueno (3 pts) | Deficiente (0 pts) |    Justificación y/o comentario | 
|:-----------------|:--------------:|:-------------:|:-------------------:|:----------------------------------:|
|     Instrucciones de jugar  |    5  %           |         X                  |                              |  Ejemplo de comentario          |
|     Visualizacion turnos|    5  %           |         X                  |                              |          |
|   Termino de juego    |    10  %           |         X                  |                              |        |
|  Rondas de partida     |    5  %           |         X                  |                              |        |
|   Alternacion de jugadores    |    5  %           |         X                  |                              |        |
|   Reglas de juego    |    5  %           |         X                  |                              |        |
|   Opción para rendirse    |    5  %           |         X                  |                              |        |
|   Programa robusto   |    5  %           |                         |              X                |       El programa no funciona si ingreso 'a' |
|   Se mantiene información de jugador en Task 2   |    5  %           |         X                  |                              |        |
|   Al terminar el juego se muestran los resultados en Task 2  |    5  %           |         X                  |                              |        |
|   Nivel Facil   |    6  %           |         X                  |                              |        |
|  Nivel Medio   |    10  %           |         X                  |                              |        |
|   Aleatoriedad     |    2  %           |         X                  |                              |        |
|   Implementación de Task 1 y 2   |    2  %           |         X                  |                              |        |
|   Registro de movimientos   |    9  %           |                          |                 X            |        |
|   Visualización de movimientos    |    9  %           |                           |          X                 |        |
|   Implementación de Task 1, 2 y 3    |    2  %           |                          |                X              |        |

## Utilización del sistema

+ Breve explicación de lo realizado. Mostrar cómo comienza el juego y cuales son las opciones a ingresas y si es que se consideraron algunos supuestos. 

## Explicación de código 

+ Explicación de algunas secciones del código que ayuden a la revisión. Si es que separó en módulos o algunas funciones que haya realizado. 

# ¿Como incorporarlo?

Si es que copian el siguiente código, lo podrán agregar sin problemas a su README

```
# Laboratorio 01

Nombre estudiante:   nombre apellido
Nro alumno: 123456j
Sistema operativo utilizado: Windows 10, macOS Big Sur, etc.
Compilador utilizado: Indicar el link si es que fue online o si es local, cuál utilizaron. 


## Resumen

| Criterio             | Ponderación  | Bueno (3 pts) | Deficiente (0 pts) |    Justificación y/o comentario | 
|:-----------------|:--------------:|:-------------:|:-------------------:|:----------------------------------:|
|     Instrucciones de jugar  |    5  %           |         X                  |                              |  Ejemplo de comentario          |
|     Visualizacion turnos|    5  %           |         X                  |                              |          |
|   Termino de juego    |    10  %           |         X                  |                              |        |
|  Rondas de partida     |    5  %           |         X                  |                              |        |
|   Alternacion de jugadores    |    5  %           |         X                  |                              |        |
|   Reglas de juego    |    5  %           |         X                  |                              |        |
|   Opción para rendirse    |    5  %           |         X                  |                              |        |
|   Programa robusto   |    5  %           |                         |              X                |       El programa no funciona si ingreso 'a' |
|   Se mantiene información de jugador en Task 2   |    5  %           |         X                  |                              |        |
|   Al terminar el juego se muestran los resultados en Task 2  |    5  %           |         X                  |                              |        |
|   Nivel Facil   |    6  %           |         X                  |                              |        |
|  Nivel Medio   |    10  %           |         X                  |                              |        |
|   Aleatoriedad     |    2  %           |         X                  |                              |        |
|   Implementación de Task 1 y 2   |    2  %           |         X                  |                              |        |
|   Registro de movimientos   |    9  %           |                          |                 X            |        |
|   Visualización de movimientos    |    9  %           |                           |          X                 |        |
|   Implementación de Task 1, 2 y 3    |    2  %           |                          |                X              |        |



## Utilización del sistema

+ Breve explicación de lo realizado. Mostrar cómo comienza el juego y cuales son las opciones a ingresas y si es que se consideraron algunos supuestos. 

## Explicación de código 

+ Explicación de algunas secciones del código que ayuden a la revisión. Si es que separó en módulos o algunas funciones que haya realizado. 
```

**Comment by jnopazo** [comment]
Hola, una duda... la parte de la rúbrica no debemos llenarla (la tabla de evalucion) o es para ver que cosas se implementaron y que cosas no. Saludos

**Comment by tomaspinochetv** [comment]
Hola @jnopazo, deben llenarla para ver que consideran que se implementó y que no.
