### ISSUE TITLE
scanf en Git Bash se comporta extraño

### ISSUE THREAD

**Issue by Incruen** [IEE2463/classroom#3]
Hola!

En un código que escribí tengo al inicio unos cuantos printf seguidos por un scanf. Usando Git Bash mi programa se compila correctamente pero al ejecutar el archivo .exe creado las líneas de texto que deberían aparecer antes del texto asociado a la función scanf no aparecen. De hecho todo el texto impreso por mi código no aparece en pantalla hasta que mi programa se termina de ejecutar. Intenté usando la línea de comandos de Windows y no tengo problemas en compilar ni ejecutar mi programa.

Investigué un poco y encontré esto: 
https://stackoverflow.com/questions/49132861/c-scanf-print-in-gitbash-and-windows-cmd?rq=1
https://stackoverflow.com/questions/44758121/prompt-coming-before-print-statement-when-executing-a-c-program-in-git-bash

No me queda claro si hay realmente una solución para Git Bash o simplemente trabajar con la línea de comandos de windows.

Jorge

**Comment by loky32** [comment]
Estimado Jorge, no es necesario que corra por el Git Bash, si tu programa compila y se muestra correctamente mediante la línea de comandos de Windows es suficiente para esta experiencia. Saludos! , Loky32
