### ISSUE TITLE
Programa en un solo código

### ISSUE THREAD

**Issue by Arturovidalr** [IEE2463/classroom#3]
En la guía del Lab 1 sale que el programa final debe ser realizado en un sólo código. ¿Esto significa que no puedo modularizar o tener, por ejemplo, archivos .h para declarar estructuras y .c para definirlas?

**Comment by felipesanchezvaras** [comment]
Es posible modularizar el programa, la idea es que solo tengan una función main en el flujo del programa, de forma que no sea necesario compilar varias veces programas distintos para visualizar cada Task.
