### ISSUE TITLE
Avr-gcc - Problema al compilar librerías 

### ISSUE THREAD

**Issue by JavierBZ** [IEE2463/classroom#30]
Hola, estoy teniendo problemas al incluir las librerías para comunicarse con las tarjeta SD. Al usar el compilador avr-gcc mediante terminal en MacOs-Mojave, no me reconoce las librerías del `PetitFatFilesystem` , por lo que no reconoce las funciones del main. Como plan B, opté por usar Atmel Studio en una maquina virtual con Windows 10 y ahí me compila sin problemas, aunque me gustaría seguir usando la versión por terminal. 
Al parecer es un problema poco común y no logro dar con algo en la web.

Gracias de antemano.

PD: Mi código de Task1 esta subido en github por si el problema se encuentra ahí.

**Comment by akaminetzkyp** [comment]
Hola Javier!

Acabo de revisar tu repositorio y veo que está la carpeta `SPI`, `USART` y el archivo `SDcardtest.c`. Sin embargo, no está la carpeta `PetitFatFilesystem`. Podría ser ese el problema?

Saludos!

**Comment by JavierBZ** [comment]
Hola! No subi esa carpeta porque no habia nada que modificar (supongo). Solo subi los archivos que se debían modificar.

Saludos

**Comment by akaminetzkyp** [comment]
Y esa carpeta sí está en tu computador? Podrías subir todo lo que tienes porfa?

**Comment by JavierBZ** [comment]
Si si, esta en mi computador.
Ahi subi todo lo que ocupe para el Task1 (excepto la carpeta de Files for the SD card)

**Comment by akaminetzkyp** [comment]
Perfecto. Javier, me podrías mostrar qué errores te muestra al compilar? Estás compilando los archivos de la carpeta `PetitFatFilesystem`?

**Comment by JavierBZ** [comment]
`avr-gcc -Wall -Wextra -Wpedantic -Os -DF_CPU=16000000UL -mmcu=atmega328p -c SDcardtest.c -o SDcardtest.o
avr-gcc -Wall -Wextra -Wpedantic -Os -DF_CPU=16000000UL -mmcu=atmega328p -o SDcardtest.elf SDcardtest.o
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.o: in function `main':
SDcardtest.c:(.text.startup+0xa4): undefined reference to `pf_mount'
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.c:(.text.startup+0xc8): undefined reference to `pf_open'
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.c:(.text.startup+0xfe): undefined reference to `pf_read'
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.c:(.text.startup+0x160): undefined reference to `pf_open'
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.c:(.text.startup+0x180): undefined reference to `pf_lseek'
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.c:(.text.startup+0x1cc): undefined reference to `pf_write'
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.c:(.text.startup+0x1e8): undefined reference to `pf_write'
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.c:(.text.startup+0x20a): undefined reference to `pf_open'
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.c:(.text.startup+0x22a): undefined reference to `pf_lseek'
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.c:(.text.startup+0x27a): undefined reference to `pf_write'
/usr/local/opt/avr-binutils/bin/avr-ld: SDcardtest.c:(.text.startup+0x292): undefined reference to `pf_write'
collect2: error: ld returned 1 exit status
make: *** [build] Error 1
`

**Comment by JavierBZ** [comment]
<img width="692" alt="Screen Shot 2019-05-23 at 6 35 14 PM" src="https://user-images.githubusercontent.com/48395654/58290948-895bd800-7d89-11e9-8e39-1b2dad848d99.png">

Este es el mensaje de error. En los laboratorios pasados (Con el `USART_implement_me`)tenía un error parecido y lo solucionaba cambiando la extensión .h a .c, lo que no parecía tan legal... El problema es que ahora no existe un `PetitsSH.c`, y no he logrado compilar las librerias de `PetitFatFilesystem`

**Comment by facortes1** [comment]
Hola, yo estoy teniendo el mismo problema con avr-gcc en Mac. Agregué todos los archivos `.c` al comando de compilación. El archivo que tira el error, `avr_mmcp.c`, es el único que no tiene header, y tal vez por eso no reconoce las funciones.

**Comment by aamacaya** [comment]
Hola yo estoy en el mismo problema que @facortes1 , agregue todos los archivos.c al comando de compilación y me tira error al compilar avr_mmcp.c, que es el unico archivo sin su respectivo header. En particular dice que la "rcv_spi"  no esta definido, adjunto imagen del error

<img width="570" alt="Captura de Pantalla 2019-05-25 a la(s) 11 09 41" src="https://user-images.githubusercontent.com/48355987/58371285-1e6fe580-7ede-11e9-8026-4b9d7436bd9f.png">

**Comment by aamacaya** [comment]
[SOLUCION]

Hola! Tengo la solución, hay que agregar la siguiente linea de código al archivo  avr_mmcp.c:

BYTE rcv_spi (void);		/* usi.S: Send a 0xFF to the MMC and get the received byte */

de esta forma funciona como header y se compila y me permite realizar el task1 sin problemas

No se olviden de compilar todos los archivos con extensión ".c" en la carpeta PetitFat...

<img width="706" alt="Captura de Pantalla 2019-05-25 a la(s) 14 11 01" src="https://user-images.githubusercontent.com/48355987/58373123-ff318200-7ef6-11e9-8313-cb0fa2b9d01f.png">
