### ISSUE TITLE
LAB 03 - Espacio colaborativo y melodías

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#30]
Está Issue podrá ser utilizada para compartir melodías a utilizar en el laboratorio.  Si crean alguna, les pedimos que la compartan acá, recuerden que les entregamos solo 3 y necesitan al menos 4.

Las melodías no serán evaluadas y pueden utilizar cualquiera que se encuentre en esta Issue.

Se aceptan cualquier tipo de melodía siempre y cuando no promuevan la violencia, discriminación, ideologías políticas ni sean ataques a otras personas. Mantengamos un clima de respeto entre todos.

**Comment by felipesanchezvaras** [comment]
## Marcha Imperial
https://www.youtube.com/watch?v=ChPxfo2R-pA

```
  int melody[] = {
      N_A4, N_A4, N_A4, N_F4, N_C5,  // 0,1,2,3,4
      N_A4, N_F4, N_C5, N_A4,  // 5,6,7,8
      // first bit
      N_E5, N_E5, N_E5, N_F5, N_C5,  // 13
      N_GS4, N_F4, N_C5, N_A4,  // 17
      // second bit...

      N_A5, N_A4, N_A4, N_A5, N_GS5, N_G5,  // 23
      N_FS5, N_F5, N_FS5,  // 26

      // delay(125)

      N_AS4, N_DS5, N_D5, N_CS5,  // 30

      // start of the interesting bit

      N_C5, N_B4, N_C5,  // 33

      // delay 125

      N_F4, N_GS4, N_F4, N_A4,  // 37

      N_C5, N_A4, N_C5, N_E5,  // 41

      N_A5, N_A4, N_A4, N_A5, N_GS5, N_G5,  // 47
      N_FS5, N_F5, N_FS5,  // 50

      // delay(125)

      N_AS4, N_DS5, N_D5, N_CS5,  // 54

      N_C5, N_B4, N_C5,  // 57

      // delay

      N_F4, N_GS4, N_F4, N_C5,  // 61
      N_A4, N_F4, N_C5, N_A4  // 65

  };

  int noteDurations[] = {500, 500, 500, 350,  150, 500, 350, 150, 1000,

                         500, 500, 500, 350,  150, 500, 350, 150, 1000,

                         500, 350, 150, 500,  350, 125, 125, 125, 250,

                         250, 500, 350, 125,  125, 125, 250,

                         250, 500, 375, 125,

                         500, 375, 125, 1000,

                         500, 350, 150, 500,  350, 125, 125, 125, 250,

                         250, 500, 350, 125,

                         125, 125, 250, 250,  500, 375, 125,

                         500, 375, 125, 1000};
```

## Megalovania
https://www.youtube.com/watch?v=QyTUgvMRNek

```
 int melody[] = {
      N_D3,  N_D3,  N_D4,  N_A3,  0,     N_GS3, N_G3,  N_F3,  N_D3, N_F3, N_G3,
      N_C3,  N_C3,  N_D4,  N_A3,  0,     N_GS3, N_G3,  N_F3,  N_D3, N_F3, N_G3,
      N_B2,  N_B2,  N_D4,  N_A3,  0,     N_GS3, N_G3,  N_F3,  N_D3, N_F3, N_G3,
      N_AS2, N_AS2, N_D4,  N_A3,  0,     N_GS3, N_G3,  N_F3,  N_D3, N_F3, N_G3,
      N_D3,  N_D3,  N_D4,  N_A3,  0,     N_GS3, N_G3,  N_F3,  N_D3, N_F3, N_G3,
      N_C3,  N_C3,  N_D4,  N_A3,  0,     N_GS3, N_G3,  N_F3,  N_D3, N_F3, N_G3,
      N_B2,  N_B2,  N_D4,  N_A3,  0,     N_GS3, N_G3,  N_F3,  N_D3, N_F3, N_G3,
      N_AS2, N_AS2, N_D4,  N_A3,  0,     N_GS3, N_G3,  N_F3,  N_D3, N_F3, N_G3,
      N_D4,  N_D4,  N_D5,  N_A4,  0,     N_GS4, N_G4,  N_F4,  N_D4, N_F4, N_G4,
      N_C4,  N_C4,  N_D5,  N_A4,  0,     N_GS4, N_G4,  N_F4,  N_D4, N_F4, N_G4,
      N_B3,  N_B3,  N_D5,  N_A4,  0,     N_GS4, N_G4,  N_F4,  N_D4, N_F4, N_G4,
      N_AS3, N_AS3, N_D5,  N_A4,  0,     N_GS4, N_G4,  N_F4,  N_D4, N_F4, N_G4,
      N_D4,  N_D4,  N_D5,  N_A4,  0,     N_GS4, N_G4,  N_F4,  N_D4, N_F4, N_G4,
      N_C4,  N_C4,  N_D5,  N_A4,  0,     N_GS4, N_G4,  N_F4,  N_D4, N_F4, N_G4,
      N_B3,  N_B3,  N_D5,  N_A4,  0,     N_GS4, N_G4,  N_F4,  N_D4, N_F4, N_G4,
      N_AS3, N_AS3, N_D5,  N_A4,  0,     N_GS4, N_G4,  N_F4,  N_D4, N_F4, N_G4,
      N_F4,  N_F4,  N_F4,  N_F4,  N_F4,  N_D4,  N_D4,  N_D4,  N_F4, N_F4, N_F4,
      N_G4,  N_GS4, N_G4,  N_F4,  N_D4,  N_F4,  N_G4,  0,     N_F4, N_F4, N_F4,
      N_G4,  N_GS4, N_A4,  N_C5,  N_A4,  N_D5,  N_D5,  N_D5,  N_A4, N_D5, N_C5,
      N_F4,  N_F4,  N_F4,  N_F4,  N_F4,  N_D4,  N_D4,  N_D4,  N_F4, N_F4, N_F4,
      N_F4,  N_D4,  N_F4,  N_E4,  N_D4,  N_C4,  0,     N_G4,  N_E4, N_D4, N_D4,
      N_D4,  N_D4,  N_F3,  N_G3,  N_AS3, N_C4,  N_D4,  N_F4,  N_C5, 0,    N_F4,
      N_D4,  N_F4,  N_G4,  N_GS4, N_G4,  N_F4,  N_D4,  N_GS4, N_G4, N_F4, N_D4,
      N_F4,  N_F4,  N_F4,  N_GS4, N_A4,  N_C5,  N_A4,  N_GS4, N_G4, N_F4, N_D4,
      N_E4,  N_F4,  N_G4,  N_A4,  N_C5,  N_CS5, N_GS4, N_GS4, N_G4, N_F4, N_G4,
      N_F3,  N_G3,  N_A3,  N_F4,  N_E4,  N_D4,  N_E4,  N_F4,  N_G4, N_E4, N_A4,
      N_A4,  N_G4,  N_F4,  N_DS4, N_CS4, N_DS4, 0,     N_F4,  N_D4, N_F4, N_G4,
      N_GS4, N_G4,  N_F4,  N_D4,  N_GS4, N_G4,  N_F4,  N_D4,  N_F4, N_F4, N_F4,
      N_GS4, N_A4,  N_C5,  N_A4,  N_GS4, N_G4,  N_F4,  N_D4,  N_E4, N_F4, N_G4,
      N_A4,  N_C5,  N_CS5, N_GS4, N_GS4, N_G4,  N_F4,  N_G4,  N_F3, N_G3, N_A3,
      N_F4,  N_E4,  N_D4,  N_E4,  N_F4,  N_G4,  N_E4,  N_A4,  N_A4, N_G4, N_F4,
      N_DS4, N_CS4, N_DS4,
  };
  int noteDurations[] = {
      16, 16, 8,  6,  32, 8,  8,  8,  16, 16, 16, 16, 16, 8,  6,  32, 8,  8,
      8,  16, 16, 16, 16, 16, 8,  6,  32, 8,  8,  8,  16, 16, 16, 16, 16, 8,
      6,  32, 8,  8,  8,  16, 16, 16, 16, 16, 8,  6,  32, 8,  8,  8,  16, 16,
      16, 16, 16, 8,  6,  32, 8,  8,  8,  16, 16, 16, 16, 16, 8,  6,  32, 8,
      8,  8,  16, 16, 16, 16, 16, 8,  6,  32, 8,  8,  8,  16, 16, 16, 16, 16,
      8,  6,  32, 8,  8,  8,  16, 16, 16, 16, 16, 8,  6,  32, 8,  8,  8,  16,
      16, 16, 16, 16, 8,  6,  32, 8,  8,  8,  16, 16, 16, 16, 16, 8,  6,  32,
      8,  8,  8,  16, 16, 16, 16, 16, 8,  6,  32, 8,  8,  8,  16, 16, 16, 16,
      16, 8,  6,  32, 8,  8,  8,  16, 16, 16, 16, 16, 8,  6,  32, 8,  8,  8,
      16, 16, 16, 16, 16, 8,  6,  32, 8,  8,  8,  16, 16, 16, 8,  16, 8,  8,
      8,  8,  4,  16, 8,  16, 8,  8,  8,  16, 16, 16, 16, 16, 8,  8,  16, 8,
      8,  8,  8,  8,  8,  8,  8,  16, 16, 16, 2,  8,  16, 8,  8,  8,  8,  4,
      16, 8,  16, 8,  8,  8,  8,  8,  16, 8,  16, 8,  8,  8,  8,  8,  8,  8,
      16, 8,  15, 8,  8,  2,  3,  16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
      16, 8,  2,  16, 8,  16, 8,  16, 16, 16, 16, 16, 16, 8,  8,  8,  8,  8,
      8,  16, 16, 16, 2,  8,  8,  8,  8,  4,  4,  4,  4,  4,  4,  2,  8,  8,
      8,  8,  2,  2,  3,  16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 8,
      2,  16, 8,  16, 8,  16, 16, 16, 16, 16, 16, 8,  8,  8,  8,  8,  8,  16,
      16, 16, 2,  8,  8,  8,  8,  4,  4,  4,  4,  4,  4,  2,  8,  8,  8,  8,
      2,  1};
```

## Eight days a week 

```
  int melody[] = {N_E5, N_D5, N_C5, N_D5, N_D5, N_A4, N_A4, N_C5, N_F5, N_F5,
                  N_E5, N_E5, N_D5, N_C5, N_D5, N_D5, N_A4, N_A4, N_C5, N_F5,
                  N_F5, N_E5,

                  // Hold me love me
                  N_E5, N_C5, N_D5, N_A4, N_E5, N_C5, N_D5, N_A4,

                  // Aint got nothing but love babe
                  N_E5, N_D5, N_C5, N_C5, N_D5, N_D5, N_A4,

                  // Eight days a week
                  N_F5, N_F5, N_F5, N_E5, N_D5, N_C5};

  int noteDurations[] = {500,  500,  500,  500,  1000, 1000, 500,  500,
                         500,  500,  2000, 500,  500,  500,  500,  1000,
                         1000, 500,  500,  500,  500,  1000,

                         1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000,
                         500,  500,  250,  250,  500,  1000, 1000,

                         500,  500,  500,  250,  250,  1000};
```

**Comment by Polar951** [comment]
void Despacito(void){

    int melody[] = {
      N_D5, N_CS5, N_B4, N_FS4,
      N_FS4, N_FS4, N_FS4, N_FS4, N_B4, N_B4, N_B4, N_B4, N_B4, N_A4, N_B4, N_G4,
      N_G4, N_G4, N_G4, N_G4, N_B4, N_B4, N_B4, N_B4, N_B4, N_CS5, N_D5, N_A4,
      N_A4, N_A4, N_A4, N_A4, N_D4, N_D4, N_D4, N_D4, N_D4, N_E4, N_E4, N_CS4,
      0,
      N_D5, N_CS5, N_B4, N_FS4,
      N_FS4, N_FS4, N_FS4, N_FS4, N_B4, N_B4, N_B4, N_B4, N_B4, N_A4, N_B4, N_G4,
      N_G4, N_G4, N_G4, N_G4, N_B4, N_B4, N_B4, N_B4, N_B4, N_CS5, N_D5, N_A4,
      N_A4, N_A4, N_A4, N_A4, N_D4, N_D4, N_D4, N_D4, N_D4, N_E4, N_E4, N_CS4
    };
    int noteDurations[] = {
      2, 2, 4, 4,
      8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 4,
      8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 4,
      8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 2,
      8,
      2, 2, 4, 4,
      8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 4,
      8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 4,
      8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 2,
    };

//https://ardusongs.blogspot.com/

**Comment by tomaspinochetv** [comment]
Thunderstruck
{N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4,
                  N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4,
                  N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4,
                  N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4,
                  N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4,
                  N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4, N_B3, N_DS4, N_B3, N_FS4,
                  N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4,
                  N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4, N_B3, N_E4, N_B3, N_G4, N_B3,
                  N_B4, N_B3, N_A4, N_B3, N_GS4, N_B3, N_A4, N_B3, N_GS4, N_B3, N_FS4, N_B3, N_GS4, N_B3, N_E4, N_B3,
                  N_FS4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3,
                  N_B4, N_B3, N_A4, N_B3, N_GS4, N_B3, N_A4, N_B3, N_GS4, N_B3, N_FS4, N_B3, N_GS4, N_B3, N_E4, N_B3,
                  N_FS4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3,
                  N_B4, N_B3, N_A4, N_B3, N_GS4, N_B3, N_A4, N_B3, N_GS4, N_B3, N_FS4, N_B3, N_GS4, N_B3, N_E4, N_B3,
                  N_FS4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3,
                  N_B4, N_B3, N_A4, N_B3, N_GS4, N_B3, N_A4, N_B3, N_GS4, N_B3, N_FS4, N_B3, N_GS4, N_B3, N_E4, N_B3,
                  N_FS4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3, N_E4, N_B3, N_DS4, N_B3};
Duración de nota: 124ms 
Tiempo entre notas: 1ms
Los tiempos los puse directo en beep.
