### ISSUE TITLE
Aclaración TASK 1

### ISSUE THREAD

**Issue by GutiJos** [IEE2463/classroom#31]
Hola a todos!
Una aclaración sobre el **task 1** del laboratorio 2. Si la lectura de su botón funciona correctamente (el programa reconoce de forma instantánea que el botón es presionado) no será necesario implementar un método de debounce.
Por el contrario, si su programa tiene problemas al leer el botón (ya sea que el botón debe ser mantenido para que el programa reconozca el pulso **o** la lectura es producida una vez que el botón es soltado) recomendamos realizar algún método de debounce para solucionar el problema.

En resumen, **no estará permitido** que la correcta lectura del botón se realice:
- mientras se mantiene presionado el botón.
- después de un delay.
- cuando el botón es soltado.

Saludos y ánimo!

**Comment by moquezada** [comment]
Si bien siempre es bueno implementar un método de debounce para pulsadores externos, ¿existe información respecto a que el push button de Tinkercad simule ese efecto? Me tinca más que los problemas que alguien puede tener respecto al funcionamiento del pulsador pueden ser las siguientes:

- No utilizar interrupciones para verificar el estado del pulsador y estar verificando constantemente este mismo en el _main code_.
- En el caso de utilizar interrupciones no estar especificando bien qué gatilla la interrupción (_positive edge_ o  _negative edge_)

Siento que a menos de que se pueda confirmar la existencia de _bounce_ en el botón simulado el aplicar un método de _debounce_ puede que no ayude a las personas que tienen algún tipo de problema. Aclaro que de verdad no tengo idea de si el botón simula este efecto o no, pero al menos no se me ha hecho necesario aplicar un _debounce_ para que mi pulsador funcione correctamente.
