### ISSUE TITLE
Lab8: estructura de datos de USART

### ISSUE THREAD

**Issue by atroncoso2** [IEE2463/classroom#31]
Hola, 
En el enunciado del task 1 del lab8 dice que para la librería USART, se puede utilizar el buffer que nosotros prefiramos. ¿Se puede utilizar entonces un simple string como buffer?

Pregunto porque el enunciado sugiere que utilizemos lineal, circular o linked list.  
Además sé que han habido confusiones respecto de requerimientos de este tipo en laboratorios anteriores. 

Saludos, 
Axel Troncoso

**Comment by felipesanchezvaras** [comment]
Hola ! 
Es decisión tuya el tipo de buffer que utilices para la recepción, lo importante es que si enviamos un string finalizado con "\n" y de un largo dado (que nos puedes informar tú), este pueda ser escrito en la tarjeta SD. Ahora bien, tu buffer debe ser capaz de enfrentarse a situaciones en que podría recibir un string de un largo menor o mayor al tamaño que tu impusiste, ya sea cortando el mensaje (lineal), guardando siempre los último *n* elementos (circular de tamaño *n* ) o que no tenga límite (linked list). 

Si tu string como buffer cumple estas características, está todo ok.

Saludos  !
