### ISSUE TITLE
LAB 04 - Dudas ADC 

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#32]
Espacio destinado a dudas de ADC

**Comment by JavieraSanMartin** [comment]
Hola, espero que se encuentren bien. No he podido encontrar qué es la señal SHI en el ADC. Espero puedan ayudarme. Gracias de antemano. Saludos

**Comment by aamacaya** [comment]
@JavieraSanMartin  ELflanco positivo de la señal SHI inicia el sampling del ADC. Si el modo de captura es "extended sample mode" el flanco de bajada también indica el fin del tiempo de sampling y el comienzo sel tiempo de conversión del valor sampleado a su forma digital.

La señal SHI se puede activar de dos formas. Poniendo un 1 en el bit ADC12SC o con alguno de los 3 timers conectados al ADC (hay que configurar el ADC apropiadamente para seleccionar cuál usar).

Todo esto está explicado en el punto 28.2.5 del Users's Guide (pag 736). Hay gráficos que te pueden ayudar a entender lo que ocurre.

Espero que quede claro

**Comment by chineseJack564** [comment]
Hola, espero que se encuentran bien todos.
Tengo una duda respecto al escalamiento de valores leido desde el adc, yo hize algo similar con el escalamiento que vimos en ayudanta, cuando el joystick esta en su posicion origial, me manda un valor cercano a -110, y cuando va al extremo son como valores mas chicos tipo 10.
Segun yo ese escalamiento puede estar malo, pero intente hacer un printf para ver cual eran los valores originales pero no pude visualisar el resultado del print en ccs, entonces no se si me pueden guiar un poco en esta parte.
Ademas tengo la duda que para el task3, como deberia ser el esacalmiento?
Por ejemplo supongo que el punto no puede mover si el joystick esta en su posicion central, entonces no se puede si le mandamos "X000Y000" o si le mandamos "X125Y125"?
Saludos!!!

**Comment by aamacaya** [comment]
@chineseJack564 Lo que puedes hacer para ver directamente el valor entregado por el ADC es poner CCS en modo debug y marcar la línea del código justo después de la conversión. El código se va a pausar en esa linea y vas a poder revisar directamente el valor que hay en el registro del adc. Puedes hacer esto varias veces con el joystick en distintas posiciones para poder saber los valores que toma y después hacer el escalamiento.

Sobre la segunda duda. SI el joystick está en el centro debería enviar el valor 127 aproximadamente

**Comment by chineseJack564** [comment]
Hola,
De nuevo soy yo, tengo una dura sobre el escalamiento de acelemetro ahora, ya que el rango de valor de este varia muy diferente, tambien se considera como en posicion neutro 127 aprox y 0 si le inclino mucho hacia izquierda y 255 inclinando mucho hacia derecha?

**Comment by GutiJos** [comment]
@chineseJack564 
si!, los resultados son equivalentes a los del joystick.
De todas formas, es bueno que compruebes lo que haces y veas los resultados por tu cuenta. Lo puedes hacer mandando los resultados por UART, o utilizando leds que se prenden de acuerdo a la lectura del ADC, por ejemplo.
