### ISSUE TITLE
tema lab 3

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#32]
Hola, mientras se publica el lab 3 podrían adelantarnos los temas sobre los que va a tratar (¿ADC Y PWM?) para adelantar el estudio de los mismos. 

Saludos

**Comment by CamilaTurrieta** [comment]
Hola @diegomarusic , sí correcto. Aún no esta 100% definida la actividad debido a Tinkercad, pero los grandes temas son esos. 

Saludines!
