### ISSUE TITLE
Recorrección LAB03 SEP

### ISSUE THREAD

**Issue by fnrubio** [IEE2463/classroom#32]
@IEE2463/recorrecciones-sep 

# Items a recorregir

| Item a recorregir | Puntaje obtenido | Puntaje Solicitado | 
| ----- | ---- | ---- |
| Debounce Boton | 0 pt | 1 pt | 
| Código no corre | 0 pt | 1 pt | 
| Código Ordenado | -1 pt | 0 pt | 
 
## Justificación Item 1

- Estimados ayudantes. La idea de mi debounce es que el programa entra a la interrupción cuando se detecta que el botón es apretado y existe una bandera que avisa si es primera vez que se aprieta el botón después de un largo periodo y es fuente de los bouncing que están siendo detectados por imprecisiones mecánicas. 
- Las lineas dónde se hace esto son en el archivo main_task_1, lineas 117 a la 143.
- La explicación es la siguiente: cuando el botón es detectado por la interrupción por primera vez, ingresa a la lineas 120 y la variable "push" es 0 inicialmente. Luego, el programa entra al ciclo y le da a la variable push=1 y la variable reset para indicar arriba en el main que hay una detección de reset.  Cuando hay bounce del boton, se detecta otra interrupción inmediatamente después, pero esta vez, como push es 1, no se entra a este ciclo, y esta vez, se entra al "else" de la línea 125. En ese ciclo, la expresión push=1 no tiene mucho sentido (pero se puso por precaución), pero la instrucción TB0CTL |= TBCLR lo que hace es que resetea el TimerB0. Mientras hayan muchos bounce, el Timer B0 se estará reseteando continuamente y no podrá aumentar su valor a valores muy grandes. Pero cuando no se detecte bounce y la interrupcion del TimerB0 llegue al case 14 (CCR0) en la linea 139 (que en la linea 74 de buzzer.c se explicita que TB0CCR0 = 13000, es decir, aproximadamente 400 ms de espera ya que se usó ACLK (13000/32768)), la variable push tomará el valor 0 (push=0), y así, cuando nuevamente se detecte la interrupción del botón, se entrará en el primer ciclo if de la linea 120 para que la variable reset pueda ser detectada nuevamente con seguridad de que no se trata de un bounce. ¿Se entiende mejor la idea?

## Justificación Item 32

- No sé porque no corre el código cuando a mi me corrió perfecto, de hecho, me preocupé de que no se generen warnings. El sistema operativo que utilicé fue MacOs y el compilador CodeComposerStudio. 

## Justificación Item 3 

- No entendí porque me descontaron puntaje por el código desordenado si está indentado correctamente, le puse subtítulos pertinentes para un mejor entendimiento (//librerías, //funciones, //interrupciones, preámbulo con el autor, etc.), generé los archivos propuestos por enunciado (taskx.c, buzzer.c, buzzer.h) y en las carpetas como lo sugiere la clase 1 del curso, incluso con la carpetas de Librerías 1. Saludos y que tengan buena semana.

**Comment by fffonceca** [comment]
# Resolución de la solicitud


## Item 1 
En esta primera parte entendí a lo que te refieres y tienes razón dentro de tu implementación. Por lo que este punto será otorgado, muchas gracias por esclarecer este punto.

## Item 2 
Esto no es un ítem válido dentro de los de la rúbrica, es decir, no existe el ítem "Código no corre". Quizás te referías a "Código Robusto". Este punto fue descontado por una implementación mal hecha de la PWM, y fue descontado dentro de este ítem, ya que descontarlo dentro del ítem "Configuración de timer con interrupciones" no era correcto debido a la gravedad de la falta. El problema reside en la siguiente línea de código:
```
#pragma vector = TIMER1_A1_VECTOR
__interrupt void TIMER1_A1_ISR(void)
{
        switch(TA1IV){
        case 0: break;
        case 2: P2OUT |= BIT5;  //Flanco subida
                break;
        case 14:P2OUT &=~ BIT5; //Flanco bajada
                break;
        default:break;
    }
}
```
El problema aquí es que tratas de fijar el voltaje de la salida, siendo que configuras el timer con la PWM en _OUTMOD3_. Esto es un problema, ya que es una mala práctica dentro de la implementación de la PWM.

## Item 3
El descuento se hizo por varios motivos:
- En primer lugar, el código no viene en el formato necesario. La task número 3 viene sin el formato _.c_. Además, hay un error de compilación que lo adjuntaré a continuación:

![imagen](https://user-images.githubusercontent.com/48364596/122636658-601ceb80-d0b8-11eb-91ed-ad41eb3f1759.png)

Esto es utilizando el último commit que subiste, osea, el número: `a6788606ee6345dfcd233ff7830bf9941ce294a2`. Esto se arregló incluyendo correctamente la librería `buzzer.h` que estaba dentro de la carpeta `Libreria1`. 

## Resumen
| Item a recorregir | Puntaje anterior | Puntaje solicitado |  Puntaje final | 
| ----- | ---- | ---- | ---- |
| Debounce Botón | 0 pt | 1 pt | 1 pt | 
| Código no corre (Código Robusto) | 0 pt | 1 pt | No aplica | 
| Código Ordenado | -1 pt | 0 pt | -1 pt |

**Comment by fnrubio** [comment]
Perfecto. Muchas gracias.


Saludos

Enviado desde mi iPhone
