### ISSUE TITLE
LAB 04 - Dudas UART

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#33]
Espacio destinado para dudas UART

**Comment by ftoyarzun** [comment]
Hola! Que significa que el parity bit en el struct sea 0? Hacemos que 0 sea none, 1 impar y 2 par? Gracias 😄

**Comment by GutiJos** [comment]
Exacto!, parity bit igual a cero indica que está deshabilitado. Lo importante que seas consistente con lo que hagas y lo tengas bien comentado para que sea entendible!.

Saludos.

**Comment by ftoyarzun** [comment]
Hola! Realterm no me funciona :( lo tengo configurado con todas las cosas que deberia y puedo ver con un pequeño osciloscopio que la señal de UART es la correcta, pero RealTerm no recibe nada

**Comment by fffonceca** [comment]
@ftoyarzun Seguiste el tutorial para conectar efectivamente la consola?

**Comment by ftoyarzun** [comment]
Conecté un arduino y funcionó RealTerm, luego programé en energia un pequeño codigo para ver si la msp mandaba señal usando el serial.print y tambien funcionó, pero cuando lo hago desde ccs no funciona :( y si reviso el pin de Tx con el osciloscopio se puede ver la señal. Puede ser que internamente el pin (P3.3) no esté conectado al periferico UART? (al principio de mi codigo tengo puesto P3SEL |= BIT3+ BIT4)

**Comment by valeria-adasme** [comment]
Hoy en la clase un compañero hizo notar que la comunicación UART de la MSP430 era hacia los pines P3.3 y P3.4, pero que como nosotros queríamos comunicarnos con el computador debíamos hacerlo por medio del USB. No me queda muy claro, revisando el manual el USB no menciona comunicación UART (pero, asumo, se puede) ¿Entonces la sección UART del manual no la usamos de nada?

**Comment by felipesanchezvaras** [comment]
@ftoyarzun @valeria-adasme 
Les respondo para aclarar algunos puntos que les pueden ayudar. 

Efectivamente, el MSP tiene comunicación UART con los puertos P3.3 y P3.4, que si vemos en el User Guide del Launchpad  estos se conectan a USCI_A0, que es el que controla la comunicación serial:

![image](https://user-images.githubusercontent.com/7042467/97306066-b1801e00-183c-11eb-8b4b-3659911c0f83.png)

Sin embargo, lo que ahora que ustedes quieren realizar, es utilizar la comunicación serial hacia y desde un computador, pero a través del USB. Por lo que es necesario realizar una conversión de las señales para que puedan ser reconocidas e interpretadas correctamente, lo que es realizado en el Launchpad con el eZ-FET. 

![image](https://user-images.githubusercontent.com/7042467/97306625-7f22f080-183d-11eb-8193-79a5e563f6e5.png)

Para esto, les recomiendo leer la sección [2.2.6 Application (or "Backchannel") UART](https://github.com/IEE2463/classroom/blob/master/Material%20de%20apoyo/MSP430F5529/TI%20Launchpad.pdf) del User Guide del Launchpad, que habla acerca de cómo este proceso es realizado e indica que para realizar la comunicación UART via USB, es necesario usar **USCI_A1** y no USCI_A0.

**Comment by valeria-adasme** [comment]
En la línea 32 del USART.c que está en la carpeta 'MSP' aparece:
/struct USART_configuration config_57600_8N1 = {57600, 8, 0, 1};  // You can use it

Esa sería la configuración para el uart, ¿no? ¿Qué indica cada uno? Imagino es algo como baudrate, número de bits de la palabra, paridad y...?

**Comment by fffonceca** [comment]
@valeria-adasme Tu interpretación es acertada. Cada parte de ese USART_configuration indica cada cosa, y esto se puede ver en USART.h:
```
/* You can use it, but it isn't mandatory*/
struct USART_configuration
{
	uint16_t baudrate;
	uint8_t databits;
	uint8_t parity;
	uint8_t stopbits;
};
```

**Comment by valeria-adasme** [comment]
gracias! otra duda entonces que me surge es que con 16 bits no se alcanzaría a representar el entero 115.200 que piden en el enunciado ¿Podemos cambiar el tamaño de eso o lo vemos 'cortado'?

**Comment by valeria-adasme** [comment]
Tengo más dudas, no entiendo bien la utilidad de las funciones USART_Transmit_char() ni USART_Receive_char()... Pensando que en caso de que haya información por transmitir y recibir se va a activar la interrupción y es en UCA1IV donde voy a enviar/recibir ¿Qué deberían entonces hacer esas funciones? ¿Las voy a poner dentro de la interrupción, o son esas las que suben el flag para que haya una interrupción? ... O quizás esas son para no tener que usar el vector de interrupción necesariamente? ¿Cuál era el objetivo al ponerlas en el archivo que nos entregaron?

**Comment by fffonceca** [comment]
@valeria-adasme Hacen justamente eso, son una forma de darles nombre a las acciones de enviar y recibir. No son las que suben o bajan el flag, tendrás que crear una función o buscar el registro correcto que haga eso. De ponerse en las interrupciones depende de ustedes, porque la interrupción se gatilla por X motivo, algunas veces será necesario usar estas funciones o quizás no y simplemente limpiar el buffer o cargarlo (todo esto depende del datasheet).

A que me refiero con esto, a que las funciones de transmitir y recibir deben esperar una cierta cantidad de tiempo a que se pueda hacer la acción que hacen. Esto es necesario (datasheet). Espero haya resuelto tu duda.

**Comment by valeria-adasme** [comment]
Gracias! En la parte 2.4.2 del enunciado 'Recepción con interrupciones' ¿Se debe implementar la comunicación UART con interrupciones o sólo quieren que agreguemos el buzzer simultáneamente con la comunicación serial que habíamos hecho en las partes anteriores (con un while)?

**Comment by fffonceca** [comment]
Hola @valeria-adasme . No entendí muy bien la parte del while (y si es posible, ojalá no tener un while en una interrupción), pero queremos que implementen UART por interrupciones y al mismo tiempo el buzzer para usarlo posteriormente. Espero que haya resuelto tu duda.

**Comment by jcgajardo** [comment]
Hola!!
Tengo un problema, al utilizar cualquier terminal y con el codigo de la ayudantía de transmitir un char, si poner la función en el while se transmite todo el rato, intente transmitir una 'h' y el terminal me muestra 'h' repetidamente. @IEE2463/ayudantes-sep pueden ayudarme?

**Comment by fffonceca** [comment]
@jcgajardo No entendí muy bien tu duda, ya que está funcionando como debería o no? Pusiste un transmit_char en un while infinito, por lo que debería de mandar ese "h" todo el tiempo y lo hace, por lo que qué debería estar malo?

**Comment by jcgajardo** [comment]
Perdon, es fuera del while. Pongo transmitir char en el main pero fuera de un while y lo transmite muchas veces

**Comment by Slothzilla328p** [comment]
@jcgajardo ¿Qué modificación hiciste con respecto al código entregado? ¿Solo buscas transmitir un char o estás utilizándolo en conjunto con el timer A0? Si tu modificación consistió en borrar todo dentro del while y solo dejar un Transmit_char despues del set up de los pines, podrías intentar borrar el set_up del timer y la línea de habilitación general de interrupciones.

**Comment by jcgajardo** [comment]
Hola!! @Slothzilla328p no se que paso pero hoy en la mañana funciono bien jajaja . Habia borrado todo el codigo del juego y comente el timer, solo puse un transmit_char y no funcionaba, ahora resulto. Gracias!!

**Comment by JavieraSanMartin** [comment]
Hola;

Espero que estén bien. Estoy con problemas, CCS no reconoce muchos de los registros utilizados para UART (y para ADC igual) lo que no me permite avanzar, porque me arroja error. Saben a qué se puede deber esto? Me he guiado muy fielmente de las ayudantías para trabajar. 
Me quedo atenta, gracias de antemano. Saludos

**Comment by Slothzilla328p** [comment]
@JavieraSanMartin ¿Te aseguraste que el dispositivo seleccionado en la carpeta de proyectos corresponde efectivamente al MSP430F5529 y de incluir la librería msp430.h al inicio del código? En caso de de ser así, adjunta algun pantallazo **únicamente de la pestaña de errores**, a modo de tener una idea de qué puede estar sucediendo.

**Comment by JavieraSanMartin** [comment]
Efectivamente el error estaba en lo que decías, muchísimas gracias

**Comment by chineseJack564** [comment]
Hola, Tengo una duda con la configuracion de paridad de uart, en mi codigo tengo que si es 0 no se usa el bit, si es 1 se usa paridad impar y si es 2 es paridad par. La transmision me funciona bien para el caso de 0, pero llegando el caso de 1 y 2 empieza a mandar informacion no completa, entoces quisiera saber si hize algo mal ?
Tengo subido el codigo en mi repositorio, para no mandar esa parte por aqui!
Saludos y muchas gracias, quedo atento!
