### ISSUE TITLE
Duda 7 Segmentos LAB 2

### ISSUE THREAD

**Issue by iaastete** [IEE2463/classroom#33]
Hola!
Al momento de hacer el LAB 2 ¿Debemos simular el 7 segmentos del kit, con los individuales de tinkercad (osea cortocircuitando los leds de los 3 7 segmentos entre ellos) o se pueden usar por separado usando más pines?
Saludos.

**Comment by felipesanchezvaras** [comment]
Hola ! 

La idea es que los segmentos sean cortocircuitados simulando el display del kit, es decir, solo ánodos podrán ser cables separados.
