### ISSUE TITLE
Encendido de LED y profundidad de bits de BMP

### ISSUE THREAD

**Issue by tomasladrix** [IEE2463/classroom#33]
Hola!
En el AVR el pin B5 es tanto MOSI como el LED que viene en el Atmega, por lo que se prende cada vez que se envía datos a la SD. ¿Sirve ese LED como para indicar cuándo se está utilizando la tarjeta y así no desconectarla?
Lo otro, cuando tengamos que usar el archivo BMP de otro compañero, podemos asumir que la profundidad de bits es 24 por pixel? Es decir 8 bits para cada color y sin un alpha?

**Comment by felipesanchezvaras** [comment]
Hola ! 
Lo ideal es que ocupen otro led para indicar que se está usando la SD para no desconectarla. 

Respecto al archivo BMP de otro compañero, puedes asumir que la profundidad de colores es de 24 bits por pixel, para mantener un estándar, guíate por las imágenes de ejemplo que subimos, es decir, que las imágenes que ustedes crearon sigan esa misma estructura.

Saludos, 
Felipe
