### ISSUE TITLE
LAB 04 - Dudas y bugs Interfaz

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#34]
Espacio destinado para dudas relacionadas con la interfaz de interfaz. Si encuentran algún bug o error favor reportarlo indicando sistema operativo y etiquetando a @felipesanchezvaras . 

Si tienen sugerencias de mejoras pueden hacerlo aquí mismo.

**Comment by angelux666** [comment]
@felipesanchezvaras 
![Captura](https://user-images.githubusercontent.com/53802464/97610199-53496b80-19f3-11eb-8748-e55dd62bbb54.PNG)

 Hola tuve el error anterior al momento de correr la task 1 y task 2 ,ya intente crear un nuevo proyecto, crear un nuevo espacio de trabajo ,revise que launchpad fuera el correcto ,en el código no hay errores y también corrí el lab 3 y funciono.
la única vez que funciono el código fue cuando hice debug.
¿Qué puede ser?

**Comment by fffonceca** [comment]
Hola @angelux666 .  Añadiste los archivos del buzzer que vienen aparte del main?

**Comment by angelux666** [comment]
@fffonceca si también

**Comment by fffonceca** [comment]
@angelux666 encuentro interesante lo que está pasando. Es muy probable que tu problema se relacione a [esto](https://e2e.ti.com/support/tools/ccs/f/81/t/162331?MSP430-GEL-Encountered-a-problem-loading-file-) al copiar tu proyecto no lo guardaste completamente. Lo otro es que es probable que hayas cambiado el nombre del proyecto sin quere. Me avisas si esto te ayuda!.

**Comment by angelux666** [comment]
Hola tuve el siguiente problema al ejecutar el interfaz, instale todas las librerías.
![error 2](https://user-images.githubusercontent.com/53802464/97910243-3d57e580-1d28-11eb-883d-299d69dd8556.PNG)

**Comment by flcardenas** [comment]
![gamepy](https://user-images.githubusercontent.com/48418789/98024845-aa7e8000-1de7-11eb-802f-bba9f5527f6e.PNG)
Hola a todos! tengo un problema con la interfaz, primero no se mueve el cuadrado azul (ya verifiqué y por uart mando en el formato solicitado), segundo al presionar Start el juego entero se queda pegado "No responde". Si pudieran ayudarme a saber qué pasa se los agradecería. Saludos.

**Comment by Rafoxxa** [comment]
Hola! @felipesanchezvaras tengo el mismo problema que señala flcardenas sobre que la ventana de juego se me pega. Nosé si esto le ha pasado a otros alumnos, en ese caso cómo lo han resuelto?

**Comment by bernisuazo** [comment]
tengo el mismo problema de Rafa :(

**Comment by felipesanchezvaras** [comment]
@flcardenas @Rafoxxa @bernisuazo 

Acabo de subir una nueva versión de la interfaz que imprimirá un posible error al intentar conectarse con el microcontrolador. 

Para todos las recomendaciones son:

- Revisar que el puerto serial y baudrate coinciden tanto en interfaz como en código
- Revisar que estén instalados las librerías en python necesarias

`pip install pyserial pygame matplotlib`

Si pueden además adjuntar una captura de pantalla de Realterm con el formato de mensaje que están enviando, podría ayudar a determinar qué sucede y también de qué error aparece en la ventana de comandos al ejecutar la interfaz.

Finalmente, si no logran hacer funcionar la interfaz, dado que se puede atribuir a un problema de instalación, no hay problema. El microcontrolador no sabe si está o no conectado a una interfaz, por lo que es mucho más importante que reaccione como corresponde a las instrucciones que se le envían y que envíe los datos en formato correcto (en otras palabras, pueden reemplazar momentáneamente la interfaz con RealTerm).
