### ISSUE TITLE
Duda con el informe

### ISSUE THREAD

**Issue by Incruen** [IEE2463/classroom#35]
Hola!

Para el informe que debemos entregar este lunes basta con adjuntar imágenes del diagrama de software más la máquina de estados y explicar al ayudante corrector nuestro informe? O debemos escribir en el informe toda la explicación de nuestro diagrama de software y máquina de estados?

Jorge

**Comment by akaminetzkyp** [comment]
Hola! No es necesario que escribas la explicación en el informe. Presentarlo en el laboratorio está perfecto. Saludos!
