### ISSUE TITLE
duda general 7 segmentos

### ISSUE THREAD

**Issue by ffelbol** [IEE2463/classroom#35]
hola! leí el datasheet del display de 7 segmentos y la verdad es que no se como conectarlo ni como programarlo, ¿me podrían dar recomendaciones de que investigar para lograrlo?
Porque no me gustaría tener que buscar un código de otra pesona y entenderlo para luego poder hacer mi propio código, sino que obviamente quiero hacerlo yo mismo desde cero.
gracias!

**Comment by CamilaTurrieta** [comment]
Hola @ffelbol, uff salió un poco largo.... En el datasheet la parte que más nos interesa para saber cómo conectar el display de 7 segmentos, por ejemplo de ánodo común, son las que muestro a continuación. Además agrego la distribución estándar de los segmentos. 
![image](https://user-images.githubusercontent.com/48395528/77502738-721ec880-6e3a-11ea-8735-6f5dca749465.png)
![image](https://user-images.githubusercontent.com/48395528/77502775-8bc01000-6e3a-11ea-89eb-764a1e15bf70.png)

Entonces, la idea general es, por ejemplo supongamos que queremos dibujar el número 3, prender los segmentos correspondientes al **a**, **b**, **c**, **g** y **d**, tal como se muestra en la siguiente foto: 
![image](https://user-images.githubusercontent.com/48395528/77503818-5c5ed280-6e3d-11ea-88a0-e0ac44f78de7.png)

Entonces, ahora si vamos al circuito de sólo un display, hay que pensar qué voltajes poner en cada pin. En particular, qué voltaje pongo en el pin naranja, cuál en los rojos (que son los que quiero prender) y en los restantes. 
![image](https://user-images.githubusercontent.com/48395528/77503480-6fbd6e00-6e3c-11ea-9734-34a27723b610.png) 

Entonces, los display de ánodo común siempre llevan un voltaje positivo en el ánodo; es decir, en el pin marcado con naranja iría un voltaje alto (¿por qué? por la posición del diodo). Entonces, ahora la pregunta es **¿qué voltaje debo poner en los pines marcados con rojos para que exista corriente que circule por el led (diodo) y este pueda brillar?** En el caso de los que quiero qué estén apagados **¿que voltaje debo setear en dichos pines para que no circule corriente por el diodo?**  Al responder esto, tienes la lógica de conexión y programación para un display. En resumen, si quiero prender un segmento debo colocar un voltaje bajo y si quiero apagar dicho segmento, debo seleccionar un voltaje alto en dicho pin.  La idea entonces es que, cada pin del display se conecte a un puerto de salida del avr (Arduino de Tinkercad) y controlando el nivel de voltaje de cada uno seas capaz de prender o apagar los segmentos. 

Luego, qué hago si tengo un display como el del datasheet y quiero tener 2 prendidos con números distintos. Pues la respuesta es **switchear** entre los **COM**. Lo que tu realmente vas a programar son los siguientes pasos (adjunto fotos) donde los cuadros rojo y negro representan el voltaje alto y bajo que va en el puerto COM respectivamente: 
![image](https://user-images.githubusercontent.com/48395528/77504892-66360500-6e40-11ea-8a05-3c807daa2d29.png)
Entonces, imagina que en el while(1) das las instrucciones al microcontrolador para que durante un tiempo funcione la primera situación; luego, inmediatamente después de esas, das las instrucciones para que funcione la segunda situación durante otro tiempo. 

Entonces, imagina que esos tiempos son cortos (pero los suficiente para verlos) y que esto se repite muy rápido todo el rato. A nuestra vista, ambos estarán prendidos al mismo tiempo, pero realmente no es así. 

Espero te haya servido las explicaciones. De todas formas, busca material alternativo, habla con amigos y juega con Tinkercad! Ánimo y si algo no quedo claro, puedes volver a preguntar. 

Saludos!
