### ISSUE TITLE
LAB 04 - Dudas Task Final

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#35]
Espacio destinado a dudas de la implementación final.

**Comment by angelux666** [comment]
Para la task 3 se deben usar las interrupciones de UART y pin o solo las interrupciones de UART?

**Comment by aamacaya** [comment]
@angelux666 EL task 3 debería poder hacerse sólo con interrupciones de UART.

**Comment by valeria-adasme** [comment]
No me quedó muy claro cómo funcionan los avisos del choque con la pared. Pensando en si la persona se mantiene tocando la pared, el programa seguirá enviando 'C'? o sólo lo hará una vez?

Otra duda que me surge es si las letras que indican la cantidad de golpes son sumatoria de los golpes de todos los niveles, de ese único nivel o de esa única instancia, como si estuviera pegado a la pared como en el ejemplo anterior que acabo de dar.

Otra duda ( 😞 ) es cómo funciona el sistema de puntajes. En las imágenes aparecen números positivos en el puntaje, pero nunca ocurre un evento que 'sume' puntaje, sólo descuentos por tocar las paredes ¿Se supone que al comer la fruta se gana puntaje? ¿Al pasar de nivel? ¿O hay un puntaje base con el que se inicia?

**Comment by felipesanchezvaras** [comment]
@valeria-adasme 
Los choques de pared funcionan enviando una 'C'. Si la persona se mantiene chocando la pared, continuará enviando 'C'. Sin embargo, la interfaz tiene una pequeña animación de "rebote" que evita que eso suceda, ya que deja de enviar 'C' por un periodo de tiempo (aprox 300 ms) , por lo que no pasaría que te llega una gran cantidad de 'C' juntas. De lo único que hay que preocuparse, es que si llega una 'C' por UART, el MSP emita el sonido por el tiempo indicado en el enunciado. 

La letra de cantidad de golpe es solo una forma de enviar como un "warning" al microcontrolador, pero nada más.  Ya que para este, no tiene idea de la existencia de una interfaz gráfica ni de un juego, solo realiza las acciones que se le envía. 

Todo lo relacionado con el puntaje se mantiene y procesa en la interfaz, el puntaje suma 10 cuando pasas de nivel. Pero no hay que hacer el procesamiento en el micro. Piensa que si esto fuese una consola de juegos , el MSP con el Booster Pack serían un Joystick / Control :video_game:, que envía o recibe instrucciones desde la consola :joystick:, pero todo el juego y el procesamiento del mismo, se mantiene ahí. 

La idea es que sea Plug & Play. Es decir, si en algún minuto (otro semestre) realizamos otro juego :jack_o_lantern: :cucumber: :corn: :zombie:  :zombie_woman: , y utiliza las mismas instrucciones, se pueda conectar y jugar :artificial_satellite:
