### ISSUE TITLE
Duda Bonus Lab 2

### ISSUE THREAD

**Issue by CristobalMery** [IEE2463/classroom#37]
Buenas tardes!
Respecto del bonus que consiste en leer un voltaje analógico con el ADC para luego mostrar su valor en un display de 7 segmentos. Que tan precisa debe ser la medida?

Me explico: estaría correcto utilizar solamente 1 display de 7 segmentos? Y por ejemplo que los voltajes leidos entre 0 y 0.9 se muestren con un 0; los voltajes entre 1 y 1.9 se muestren con un 1, y asi sucesivamente?

O para obtener la totalidad del puntaje es necesario utilizar 2 displays y de esta manera mostrar también el valor decimal?

**Comment by jdiaztoledo** [comment]
Hola!

Efectivamente, para obtener la totalidad del puntaje en ese bonus debes mostrar al menos dos dígitos del valor de voltaje leído con el ADC, es decir, debes utilizar al menos 2 displays.

Saludos:)
