### ISSUE TITLE
Tinkercad no me deja editar mis proyectos

### ISSUE THREAD

**Issue by fjpessot** [IEE2463/classroom#38]
Desde ayer que no puedo seguir trabajando en tinkercad porque la plataforma deshace cualquier cambio que yo realice. No puedo añadir o eliminar componentes ni borrar, agregar o modificar lineas de código. No se que hacer.

**Comment by GutiJos** [comment]
Podrías crear una issue privada donde nos compartas tu proyecto de tinkercad?

saludos.

**Comment by fjpessot** [comment]
Acabo de hacerlo

**Comment by fjpessot** [comment]
La vieron?

**Comment by fffonceca** [comment]
Solo en caso de que exista la posibilidad, estás tratando de cambiar en modo código? Recuerda que en simulación no te deja hacer ni un cambio.
