### ISSUE TITLE
LAB 05 - Dudas implementación I2C

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#39]
Dudas relacionadas con la implementación de I2C.

**Comment by valeria-adasme** [comment]
Hola! En la guía dice que debemos usar un clk para la comunicación I2C que sea de 400kHz. Pensaba que para eso se necesitaba un clock externo (UCLKI en el UCB1CTL0), pero no sé qué pin es ése. En la figura 41-1 aparece que es 'eUSCI_B SPI clock input pin' ¿Eso es el pin UCB1CLK del P4.3? no estoy muy segura...

**Comment by valeria-adasme** [comment]
En la guía dice que la velocidad del I2C debe ser de 400kHz, y en la página 1011 del manual sale que la f_bitclk se define con el clk/UCBRx, pero si queremos 400kHz eso no se puede hacer con un número entero ¿Qué se hace en esos casos? ¿Se usa BR0=2.5? Asumiendo que es el clk de 1MHz

**Comment by valeria-adasme** [comment]
Lo otro que se me ocurre es añadirle un clk externo, usar UCLKI en vez de ACLK o SMCLK, pero no estoy segura de cuál pin es donde debe ir el clock. En la guía sale que que es el 'Externally provided clock on the eUSCI_B SPI clock input pin', pero no encuentro el pin en el datasheet ¿Es el P4.3? ése dice 'UCB1CLK'...

**Comment by felipesanchezvaras** [comment]
@valeria-adasme Dado que no se puede con un número entero, puedes utilizar un valor cercano que no supere los 400 kHz. Por lo que con `BR0 = 3` será más que suficiente.

**Comment by valeria-adasme** [comment]
Hola de nuevo! Estaba pensando que el registro UCB1I2CSA (Slave address) recibe los 7bits del address (habiéndolo configurado así con el UCSLA10), ¿en qué registro entonces defino el bit R/W? ¿Baste con cambiar el Master mode? (Con el registro UCTR)

**Comment by fffonceca** [comment]
Hola @valeria-adasme . No existe un registro para eso, el direccionamiento que se hace sobre los dispositivos I2C ya viene con eso implementado. Digamos que un sensor de humedad tiene una dirección de 0x40. El bit menos significativo define si es **R** o **W**. Osea:
0x40 para escribir
0x41 para leer
Espero que te haya solucionado la duda, mando una foto de google para que se aclare un poco más la idea:
![imagen](https://user-images.githubusercontent.com/48364596/99200768-0a7d0b00-2786-11eb-8731-1a543332ceee.png)

**Comment by valeria-adasme** [comment]
Es que en esa imagen hay 7 bits de la dirección (Que en caso del TMP es 40) +  un octavo de R/W. Lo que recibe el Slave Address son sólo 7 bits, dices que se superponen el último bit de la dirección y el de R/W?

**Comment by bdelsolar** [comment]
El R/W que agrega automáticamente depende del bit UCTR?

**Comment by fffonceca** [comment]
@valeria-adasme y @bdelsolar justamente con el bit UCTR.

**Comment by valeria-adasme** [comment]
Lo siento, creo que aún no entiendo bien. Entonces el orden debería ser:
1) Genero una condición de start
2) Envío los 7bits del address del TMP
3) Cambio el UCTR dependiendo de si es bit R/W low o high

¿Es eso?

**Comment by jcgajardo** [comment]
Hola!! no entiendo bien la recepción de datos, ¿Puede I2C recibir datos sin estar sincronizado correctamente? lo pregunto porque implementandolo los valores obtenidos por el sensor son muy extraños.

**Comment by fffonceca** [comment]
@valeria-adasme El UCTR lo puedes configurar antes de enviar el byte. Ya que UCTR cambia el modo y la MSP adapta el bit R/W dependiendo de cómo este configurado ese bit del registro UCBxCTL1. Después del primer _frame_ que es de transmisión, deberás cambiar este estado del registro para empezar a recibir la información del TMP006. Este cambio lo puedes hacer antes de empezar el segundo _frame_  (antes del siguiente i2cSendStart claro). Y el bit R/W simplemente será el indicado para recibir. Espero esto haya resuelto tu duda para que puedas recibir la info.

Hola @jcgajardo . Pueden ser 2 los problemas que tengas. **Lo primero**, que es más probable es que no estás convirtiendo los valores correctamente para enviarlos al UART. Hay un proceso que debe sufrir la información antes de poder mandarla por un string por UART, ya que recibirás un arreglo más grande de 8 bits, unos más significativos (msb) y otros menos significativos (lsb) que deberás manejar para guardar en una variable. Y posterior a esto, dejarlos en el formato "string" para poder enviarlos correctamente. Asegúrate que estás haciendo bien esta conversión. **Lo segundo**, podría ser la misma comunicación I2C. Revisa que estés definiendo bien las funciones de comunicación. Revisar el datasheet, en la sección 38.3.4.2.1 del User Guide. También las funciones del _I2C_implement_me.c_ no son muy específicas, por lo que deben estar desarrolladas algunas en pocas líneas de código, fíjate de no estar definiendo redundancias (por ejemplo, llamar un _polling_ de espera cuando en el _main.c_ ya existía uno, etc...). Espero que esto haya resuelto tu pregunta. 

Si siguen teniendo dudas los invito a la sesión de preguntas hoy a las 10:00AM
