### ISSUE TITLE
duda bono lab 2

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#39]
Si supiera explicar a la perfección todo el código que subieron del lab 3, ¿lo puedo usar como bono? (ya que es una PWM controlada por contadores y que utiliza interrupciones de timer)

**Comment by fjhuanca** [comment]
Lamentablemente **no podemos permitir eso**. La idea es que haya algo de construcción propia en sus códigos justamente para fomentar el aprendizaje, y hacer lo que mencionas no cumple ese objetivo. Recuerda que la idea de los bonos es destacarse y demostrar autoaprendizaje.

**Comment by diegomarusic** [comment]
oka
