### ISSUE TITLE
Lab 1: Task 1 y 2

### ISSUE THREAD

**Issue by SebaMoralesG** [IEE2463/classroom#4]
Hola!!

En el archivo del Lab 1 aparecen los tasks de ambos MCUs para distintas fechas( en una fecha que era del primer semestre), ¿las dos pruebas deben ser entregadas el lunes 26?

Saludos!!

**Comment by felipesanchezvaras** [comment]
Hola ! 
Efectivamente, ambas tareas deben ser entregadas el dia lunes 26 de agosto. El enunciado sera corregido a la brevedad.

Saludos
