### ISSUE TITLE
Duda Lab01

### ISSUE THREAD

**Issue by fnberrios** [IEE2463/classroom#4]
Hola, en el enunciado en pdf del laboratorio en el apartado 2.1.2 dice que en la carpeta ATmega328P encontraremos el archivo hello world atmega.c. Sin embargo, en esta carpeta no existe dicho archivo ¿Se referirán tal vez al archivo blink_led_atmega.c ?

**Comment by akaminetzkyp** [comment]
Hola! Es ese mismo. Lo arreglo de inmediato. Gracias!
