### ISSUE TITLE
Ganador del juego

### ISSUE THREAD

**Issue by benjareinoso** [IEE2463/classroom#4]
Hola! El ganador del juego es el que gana más rondas? por enunciado sale que se debe mostrar quien gana cada ronda, pero no menciona si al finalizar las 3 se termina el juego o se debe como considerar al que ganó más rondas y que ese sea el ganador final por así decirlo

**Comment by aolivares12** [comment]
Hola! Efectivamente, el ganador del juego es el jugador que luego de las 3 rondas gana más rondas. Como sale en el enunciado, se debe indicar el ganador de la ronda, y al final del juego también debe mencionar el ganador de la partida.

Saludos, y comenta si es que aún hay más dudas!
