### ISSUE TITLE
aclaración evaluación de este lunes

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#4]
Hola, entonces si entiendo bien este lunes no serán evaluadas las preguntas sobre el microcontrolador msp ni tampoco el testeo de pines en la atmega. ¿estoy en lo correcto?

**Comment by fffonceca** [comment]
Efectivamente Diego con respecto a la MSP430. El testeo de pines será necesario una vez tengan sus kits, todo lo demás es evaluado entorno al atmega328p (es decir, Arduino UNO) tal como lo dice los archivos nuevos que se mandaron. Saludos!
