### ISSUE TITLE
Duda Lab1 Robustez Programa

### ISSUE THREAD

**Issue by mwoolvett** [IEE2463/classroom#4]
¿Mi programa tiene que ser robusto a cualquier input o solo a los mencionados en el enunciado? En el README que se subió la plantilla sale como ejemplo que un problema sería que el programa no funciona si ingreso "a", entonces si pido que el usuario ingrese un int, podría asumir que no va a entrar un char o tengo que ponerme en los dos casos.
Gracias!

**Comment by CamilaTurrieta** [comment]
Hola @mwoolvett. El programa robusto apunta a la idea de que el programa sea capaz de manejar un cierto nivel de errores que son probables que cometa el usuario. Entonces, si este programa es para funcionar con los input que puede entregar un teclado, es probable que el usuario se equivoque e ingrese números o letras en los inputs que se pida. Se espera entonces que ustedes apliquen ese concepto, se pregunten ¿qué podría hacer fallar mi software? ¿qué podría hacer el usuario que podría complicar el flujo del programa? y busquen un modo de manejar esos posibles errores o complicaciones para mantener el programa funcionando de una manera correcta. No es la idea que sean todas las posibles combinaciones, eso sería imposible, pero sí algunas bien típicas y que es recomendable que sean destacadas, como algo positivo de su solución, en el readme. 

Con respecto al ejemplo que mencionas, creo que es muy esperable que si pides un int el usuario ingrese un char. Se me ocurre que puedes controlarlo con un switch case o unos if. If es el número o rango de número que esperas, sigue con el programa, else pides al usuario que ingrese una opción válida porque tiene que ingresar un número entre tal intervalo dado. 

Espero haya quedado más claro. Si no, nos avisas. Este es un tema bien complejo. 

Saludos.

**Comment by mwoolvett** [comment]
Muchísimas gracias por responder!
Creo que no alcanzaré a cambiarlo, pero de todas formas muchas gracias, quedo super claro.
Saludos
