### ISSUE TITLE
LAB 05 - Dudas TMP006 y OPT3001

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#40]
Dudas relacionadas con el uso de los sensores TMP006 y OPT3001

**Comment by jcgajardo** [comment]
Hola!! tengo dudas sobre el funcionamiento de los sensores, usando i2c comencé a recibir datos pero no tienen  sentido, lo que me hace preguntarme si el i2c puede recibir valores sin estar sincronizado bueno como funciona el sensor de temperatura, dado que sin alteraciones tira valores más altos que cuando pongo la mano. @IEE2463/ayudantes-sep , lo de i2c lo pregunto mejor en i2c jajsdja

**Comment by fffonceca** [comment]
Hola @jcgajardo . Esta duda la respondí en https://github.com/IEE2463/classroom/issues/39#issuecomment-727770164 . Espero esto haya resuelto tu duda.

Ánimo con la programación.
