### ISSUE TITLE
ojo-piojo lab 3

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#40]
En el código subido para el lab 3, en el comentario hablan del timer 2, pero siempre usan los registros del timer 0, me explico:
..."
// Modo de operacion Timer 2
  	// Rellenar modo de operación : _____________
	TCCR**0**A &= ~(1<<WGM00);
	TCCR**0**A |= (1<<WGM01);
	TCCR**0**B &= ~(1<<WGM02);
..."
Mi duda es: ¿cambiamos el comentario a timer 0?

**Comment by felipesanchezvaras** [comment]
Hola!

Con “Timer 2” nos referimos a un segundo Timer, no es literal. Aunque si gustas puedes modificar el comentario a Timer 0, pero no afecta en la revisión.
