### ISSUE TITLE
Cantidad de uC para el proyecto

### ISSUE THREAD

**Issue by Incruen** [IEE2463/classroom#40]
Hola!

Está permitido usar la tarjeta de desarrollo AVR y además el chip ATmega328p para el proyecto? Y se aplicarían las décimas extras en caso de que sí?

Jorge

**Comment by akaminetzkyp** [comment]
Hola!

Puedes usar más de un microcontrolador para tu proyecto. Las décimas extras se otorgan al usar el ATmega328P sin la tarjeta de desarrollo, es decir, armando el circuito a partir del circuito integrado y los componentes necesarios. Si usas la tarjeta de desarrollo junto al chip, se otorgan las décimas extras.

Saludos!
