### ISSUE TITLE
Problema tratando de programar el chip

### ISSUE THREAD

**Issue by ngsuarez** [IEE2463/classroom#41]
Tengo configurado el programador con USBasp e instalé Avrdude, conecté los pines (y los revisé varias veces) pero cuando intento programar el atmega integrado, usando esta linea en consola "avrdude -c usbasp -p m328p" me arroja el siguiente error:

avrdude: warning: cannot set sck period. please check for usbasp firmware update.
avrdude: error: programm enable: target doesn't answer. 1
avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.

Leyendo en foros sale que el sck no es problema (y que el warning lo tira siempre al parecer) sino que el uC no está respondiendo. Cuando pongo en la linea de comando -F, me sale esto:

avrdude: warning: cannot set sck period. please check for usbasp firmware update.
avrdude: error: programm enable: target doesn't answer. 1
avrdude: initialization failed, rc=-1
avrdude: AVR device initialized and ready to accept instructions
avrdude: Device signature = 0x000000
avrdude: Yikes!  Invalid device signature.
avrdude: Expected signature for ATMEGA328P is 1E 95 0F

No he tocado las configuraciones del Fuse. Probé con y sin cristal (usando los capacitores a tierra).  Y también probé con una alimentación externa (usando una bateria de 9V con el regulador de voltaje que nos entregaron, con multimetro Vout = 5.05V). Usé dos drivers distintos para el USBasp , probé también con baudrates distintos (lentos) -B5 y -B10 ,pero nada, no paso del error. En avrfreaks dicen que puede ser problema de settings de fuse (no los he tocado) o que el chip está malo (improbable creo yo...). Alguien sabe que puede ser?

**Comment by loky32** [comment]
Hola, como estas subiendo el código?

**Comment by ngsuarez** [comment]
Estoy usando AVRDUDESS pero ya resolví el problema, al parecer los puertos usb de mi notebook se comportan raro, y a veces detectan el micro y otras veces no. Tengo que probar todos los puertos hasta q lo empiece a leer y de ahí anda OK. Yo creo que es el notebook y no el USBasp!
