### ISSUE TITLE
Bonus del mismo task

### ISSUE THREAD

**Issue by mlibarra** [IEE2463/classroom#41]
Hola, ¿se pueden hacer 2 bonus del mismo task? o el segundo tendría que ser de los bonus generales.
Saludos

**Comment by fjhuanca** [comment]
Hola! **No puedes hacer bonus del mismo task**, se te consideraría sólo 1 en tal caso. El segundo debe ser de los bonus generales.

**Comment by mlibarra** [comment]
ok, Gracias!

**Comment by fjhuanca** [comment]
Como complemento a lo anterior, si eventualmente en algún momento llegamos a revisar el task 2 (que por ahora no tenemos claridad de cuándo ni cómo) podrían presentar el bonus que corresponde a ese task en esa instancia.
