### ISSUE TITLE
LAB 05 - Dudas UART 

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#41]
Dudas relacionadas con UART y el modo de interrupción de Tx.

**Comment by chineseJack564** [comment]
Hola, una consulta, es muy necesario hacer la transmicion de UART por interrupcion?
Pq yo logre implementar transmitir pocos characteres en la interrupcion pero cuando se trata de un text string mas largo (En el caso de Help), no funciona muy bien, entonces quiero saber si es estricamente necesario este interrupcion, y no se si pueden tirarse algunos Tips para el uso de este?

**Comment by fffonceca** [comment]
Hola! como dijimos en la sesión de consultas, podrían iterar entre habilitar la interrupción de transmisión y deshabilitarla para transmitir un string de tamaño definido. Saludos!

**Comment by chineseJack564** [comment]
Hola @IEE2463/ayudantes-sep:
Espero que se encuentran bien, he descubrido 2 problema con el Realterm, y no se si es bug o es por la implementacion mia:
1. He observado que cuando mando al REALTERM, se me reemplza el tercer carater por un '\r', por ejemplo:
Haciendo eso:
![image](https://user-images.githubusercontent.com/69604944/99471393-34b8ff00-2925-11eb-8c53-eaf7f8235437.png)
En realTerm:
![image](https://user-images.githubusercontent.com/69604944/99471440-48fcfc00-2925-11eb-943e-2b0fc0ee2950.png)
Cabe destar que hay veces que me pasa y hay veces no, y no logro entender el razon. Cuando uso un sprintf sin el %s, no surge este problema:
![image](https://user-images.githubusercontent.com/69604944/99471530-7fd31200-2925-11eb-9dd6-e017547c003c.png)
![image](https://user-images.githubusercontent.com/69604944/99471564-8f525b00-2925-11eb-870c-286f0585e601.png)
Quedo atento a su respuesta!

**Comment by felipesanchezvaras** [comment]
@chineseJack564 

Esto ocurre solo cuando utilizas sprintf ? u ocurre en algún otro momento ?, puede que el problema esté con el uso de esta función o con la librería de UART. Te sugiero revisar si el problema se repite o es cuando haces uso de esa librería.
