### ISSUE TITLE
LAB 05 - Dudas estructuras de datos 

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#42]
Dudas relacionadas con estructuras de datos y el protocolo de comunicación solicitado.

**Comment by fffonceca** [comment]
Hola @IEE2463/2020-ii-estudiantes , había subido material complementario para entender buffer circular si es que llegaran a tener dudas con respecto a este, pero se los anuncio en caso de que no lo hayan visto y necesiten más información. Recuerden que exigiremos esta implementación de buffer y entendimiento sobre el tema, además del cómo se implementó. [Aquí](../blob/master/Ayudantias/I2C_Estructuras/Ring_Buffer_Ayuda.pdf) pueden encontrar la información que los podrá guiar.

Ánimo con su programación!.

**Comment by chineseJack564** [comment]
Hola, tengo un problema sobre el uso de Buffer circular:
Segun la guia de ayuda que subieron de buffer circular, Lo que uno hace es hacer que el puntero read manda hasta puntero de write, el puntero de read no sobreescribe , solo el puntero de write lo sobreescribe.(Yo lo tengo implementado de esta forma).
Sin embargo, segun la guia de enunciada, nos pide sobreescritura con ambos punteros, y no se si entendi o no, el puntero read no llega solo hasta puntero write, sino que manda todos los paquetes de datos que no ha sido mandado?
Entonces quiero saber si ambas forma de implementacion es valido? Pq ya no se si alcanzamos a cambiar.
Otro problema que tengo es sobre el formato cuando mando info desde buffer circular:
![image](https://user-images.githubusercontent.com/69604944/99605492-8e353280-29e6-11eb-804e-a9fef49504cc.png)
Cuando quiero mandar varios paquetes(P1,P2,P3), el formato es:
$P1P2P3\r\n?
o es:
$P1\r\n
$P2\r\n
$P3\r\n
Quedo atento a su respuesta!!!

**Comment by fffonceca** [comment]
Hola @chineseJack564 y gracias por tu pregunta. 
 - Con respecto a tu primera pregunta. Cuando lees un buffer, lo lees completo y en el proceso de lectura lees de forma que: read->write. Los datos que quedan apartados claramente no se leen porque es información **pasada** o **ya leída**. Si no queda muy claro te recomiendo leer [esto](../blob/master/Ayudantias/I2C_Estructuras/Ring_Buffer_Ayuda.pdf).

 - Con respecto a la segunda, los paquetes están compuesto como tu dices de $P1\r\n cierto?. Por lo que, esperamos que el buffer cuente con:
`Buffer = [Paquete1,Paquete2.....] = [$P1\r\n,$P2\r\n,$P3\r\n,...]`

Espero esto haya dejado clara tus preguntas. Ánimo con la programación.

**Comment by tomaspinochetv** [comment]
hola, me queda una duda al momento de la lectura del buffer para envío, cuando enviamos, tenemos que hacerlo caracter por caracter, por lo que pensaba ir leyendo de a 1 caracter y enviarlo siempre que pueda hacerlo, borrandolo como debe ser, hasta alcanzar al write. Pero nos piden que leamos todo el buffer y lo borremos. cuando dicen que lo leamos todo, ¿se refiere a leerlo en una sola llamada de read_buffer o que vallamos de manera secuencial leyendo-borrando hasta alcanzar al write?
¿Se puede escribir en el buffer a medida que lo voy leyendo? esto ultimo me parece lo mas lógico.
