### ISSUE TITLE
Señal de respuesta AM2302

### ISSUE THREAD

**Issue by Destloch** [IEE2463/classroom#43]
Hola!

He tenido problemas con el AM2302. No puedo obtener los datos de este, las señales de respuesta tanto como la LOW y HIGH para iniciar transferencia no las he podido coordinar con la lectura del uC. 

Los tiempos de espera que ocupado son los de la página:
[https://issuu.com/rduinostar/docs/dht22-am2302-datasheet-manual](url)
que son los que aparecen en varias páginas más.

He conectado una resistencia de 4,7k entre el SDA y 5V como recomiendan algunos foros, pero no influye al parecer. También, al realizar la lectura a través del uC es con pull-up.

Si alguien tiene alguna idea de que pude ser, se agradece su comentario :)

**Comment by akaminetzkyp** [comment]
Hola!

Primero intentaría echar a andar el sensor con alguna librería especializada, si prefieres usando Arduino. Si tampoco funciona, existe la posibilidad que el sensor no esté funcionando. En ese caso, probaría con el de un compañero.

Saludos!

**Comment by felipesanchezvaras** [comment]
@Destloch Complementando lo que decía Alejandro, si es que efectivamente es el sensor, y no logras con algún compañero, puedes contactarme y te podemos reemplazar el sensor. 

Saludos !
