### ISSUE TITLE
fotorresistor

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#43]
Hola, ¿el ADC que mide la salida del fotorresistor debo hacerlo con una medición de cambio en la resistencia o en el voltaje o yo elijo? (en el fondo la pregunta es si puedo conectar el fotorresistor a los 5V de la placa y medir los cambios de su voltaje)
Saludos!

**Comment by fjhuanca** [comment]
Hola @diegomarusic, mira si entiendo bien tu pregunta, la respuesta es que solamente puedes hacerlo mediante un cambio en voltaje. No tienes como medir un cambio en la resistencia del fotoresistor con el microcontrolador (al menos directamente). Ojo que debes considerar que el MSP funciona con 3.3V para tus cálculos.

Éxito!
Saludos

**Comment by diegomarusic** [comment]
solved
