### ISSUE TITLE
LAB 05 - Dudas y Bugs interfaz

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#43]
Cualquier duda o situación que se relacione con el uso de la interfaz.

**Comment by chineseJack564** [comment]
Hola @IEE2463/ayudantes-sep:
Tengo unos problemas sobre el interfase grafica:

1. Al precionar el boton start deberia mandar el comando `INI\r\n` y  `STP\r\n`,  sin embargo, el MSP no reacciona a esto, pero si lo hago en realterm si reacciona adecuadamente, le ajunto foto de la situacion:
mensaje que se manda al mandar `STP\r\n`:
![image](https://user-images.githubusercontent.com/69604944/99543171-a29b1000-2991-11eb-82cd-7d4a9e22d153.png)
Reaccion en Realterm:
![image](https://user-images.githubusercontent.com/69604944/99543309-ceb69100-2991-11eb-8c31-4b6fb1ac519a.png)
Reaccion en interfaz:
![image](https://user-images.githubusercontent.com/69604944/99543492-002f5c80-2992-11eb-95b2-43f8cdf31efd.png)
2. He descubrido que a veces se tira el siguiente mensaje de error al mandar un comando:
![image](https://user-images.githubusercontent.com/69604944/99543611-1e955800-2992-11eb-965f-a1269b7547b0.png)
Sin embargo, si mando el mismo comando de nuevo no hay problema.
3. No he podido encontrar como se manda el comando Help para probar su funciuonalidad.

**Comment by felipesanchezvaras** [comment]
@chineseJack564 
Te respondo punto a punto.

1. En la interfaz hay un cuadro en donde se puede enviar los instrucciones. ¿Ocurre el mismo problema que cuando presionas el botón ? Pregunto eso para poder saber donde estaría el problema. 

2. El error ocurre con algún comando en particular ? o es con cualquiera ? Buscaré una forma de encontrar el bug y tratar de solucionarlo. 

3. ¿Ocurre cuando quieres responder el mensaje de HELP ? o es en algún otro momento que ocurre que detecta solo el primer \n ? 

De todas formas, en caso de que estos problemas persistieran y no es posible solucionarlos. Es mejor que priorices el trabajo en el uC y visualizando los datos en RealTerm. A lo que voy es que mientras mantengas la estructura de los mensajes de la forma que se indicó en el enunciado y esto sea comprobable con el terminal, estará bien. La interfaz es un apoyo a esto para visualizar de mejor forma la información. 

Quedo atento en caso de cualquier cosa

**Comment by chineseJack564** [comment]
> @chineseJack564
> Te respondo punto a punto.
> 
> 1. En la interfaz hay un cuadro en donde se puede enviar los instrucciones. ¿Ocurre el mismo problema que cuando presionas el botón ? Pregunto eso para poder saber donde estaría el problema.
> 2. El error ocurre con algún comando en particular ? o es con cualquiera ? Buscaré una forma de encontrar el bug y tratar de solucionarlo.
> 3. ¿Ocurre cuando quieres responder el mensaje de HELP ? o es en algún otro momento que ocurre que detecta solo el primer \n ?
> 
> De todas formas, en caso de que estos problemas persistieran y no es posible solucionarlos. Es mejor que priorices el trabajo en el uC y visualizando los datos en RealTerm. A lo que voy es que mientras mantengas la estructura de los mensajes de la forma que se indicó en el enunciado y esto sea comprobable con el terminal, estará bien. La interfaz es un apoyo a esto para visualizar de mejor forma la información.
> 
> Quedo atento en caso de cualquier cosa

Hola, respecto al tercer punto de la pregunta, observamos lo siguiente, en RealTerm se imprime todo bien:
![image](https://user-images.githubusercontent.com/69604944/99690806-4b676f00-2a67-11eb-9c0c-14967e9cd262.png)
Sin embargo, en el interfaz grafica solo se imprime el primer dato obtenido, y tira un mensaje que es wrong value, la implementacion de lectura de buffer circular es tal como senalado en el enunciado, manda todos los valores no leidos en forma de:
$Paquete1\r\n
$Paquete2\r\n
$Paquete3\r\n
.
.
N
![image](https://user-images.githubusercontent.com/69604944/99691219-bf097c00-2a67-11eb-914a-a3541e1e7f6b.png)
Sospecho que es debido a que solo se lee hasta el primer \r\n

**Comment by felipesanchezvaras** [comment]
Ok! Gracias, realizaré una revisión a fondo para determinar qué podría estar sucediendo con la interfaz. Sin embargo el output que se observa en Realterm está perfecto!, así que pueden tener calma con eso.
