### ISSUE TITLE
Cable temperatura exterior 

### ISSUE THREAD

**Issue by mgquezada** [IEE2463/classroom#44]
Hola! 
Para el cable de al menos 2m:
¿Qúe tipo de cable recomendarían? y ¿Dónde lo podemos comprar?
Gracias!

**Comment by Incruen** [comment]
Este es un sensor de largo 3 m 

https://afel.cl/producto/sensor-temperatura-ds18b20-3-metros/?v=5bc574a47246

La tienda está cerca del metro Salvador

**Comment by mgquezada** [comment]
Entonces, estamos midiendo temperatura externa con el sensor y medimos la humedad dentro de la pieza?

**Comment by felipesanchezvaras** [comment]
@mgquezada La longitud del cable no debería ser un problema, dado que no es una señal de alta frecuencia, una opción son los cables telefónicos o cables paralelos, que se pueden encontrar en ferreterías o Sodimac/Easy, una opción que podría funcionar es esta [https://www.sodimac.cl/sodimac-cl/product/898961/Cable-telefonico-3-pares-24-AWG-metro-lineal-Blanco/898961](url).

La humedad relativa no está totalmente claro si se debe medir dentro o fuera de la pieza, así que la decisión la tomas tú, dando la justificación a la hora de presentar el porqué de tu decisión. Idealmente sería fuera. 

Para la temperatura, puedes utilizar alguno de los sensores que te entregamos (DHT22, NTC o TMP102) o adquirir alguno nuevo como el que menciona @Incruen .

Saludos !
