### ISSUE TITLE
Bonus ADC Lab 2

### ISSUE THREAD

**Issue by itserrano** [IEE2463/classroom#44]
Hola!

Al hacer el ADC como bonus en el lab 2, al mostrar los dígitos en el display, hay un error de 0.1V. Intenté arreglarlo usando tanto round() como int() pero ninguna de las dos funciones logra arreglarlo al 100%. ¿Es necesario que el voltaje mostrado sea específicamente el que muestra la fuente o se tolera ese error de 0.1V?

Gracias!

**Comment by GutiJos** [comment]
Hola @itserrano 
es tolerable!

**Comment by itserrano** [comment]
@GutiJos gracias!
