### ISSUE TITLE
Duda Lab2

### ISSUE THREAD

**Issue by IsabelJamett** [IEE2463/classroom#45]
Hola!
Tengo una duda del enunciado. Cuando inicio la simulación, ¿los displays deberían comenzar apagados y cuando apreto el boton encenderse y comenzar a contar? ¿O deberían partir mostrando 00 y cuando apreto el boton comenzar a contar?

**Comment by GutiJos** [comment]
Hola!
Cuando inicia tu programa deberían mostrar 00 y cuando presionas el botón comenzar a contar.

saludos.

**Comment by IsabelJamett** [comment]
Gracias
