### ISSUE TITLE
Error Device Signature con AVRdude

### ISSUE THREAD

**Issue by tomasladrix** [IEE2463/classroom#45]
Hola a todos, no he podido subir código usando avrdude y no sé si alguien le pasa lo mismo. Cada vez que trato de conectarlo (avrdude -c usbasp -p m328p) lo detecta pero con un device signature distinto al que debería ser y cada vez cambia a uno distinto. Cuando por coincidencia detecta el correcto sale que no se puede leer bien lfuse o hfuse. Revisé las conexiones y en foros y no he podido encontrar la falla.
¿Alguien le pasa lo mismo y logró solucionarlo?

**Comment by ngsuarez** [comment]
Prueba alimentando el microcontrolador  con una bateria de 9v con el regulador de tension, y asegurate de usar el resistor de 12k en el reset y de fijar tierras comunes para el regulador y el USBasp.  Así lo arreglé yo por lo menos, ya que con un voltimetro me sale que el Vcc del USBasp no es de 5v.

**Comment by tomasladrix** [comment]
Oh ya, lo intentaré. Muchas gracias!
