### ISSUE TITLE
Duda Lab 3

### ISSUE THREAD

**Issue by RafaelOrmazabal** [IEE2463/classroom#47]
El led tiene que estar apagado cuando el fotoresistor reciba la mínima cantidad de luz en el programa, o es correcto que cuando la luz que le llegue al fotoresistor sea mínima el led igual este prendido pero con menos intensidad?

**Comment by CamilaTurrieta** [comment]
Hola @RafaelOrmazabal! Veamos, en el enunciado se dice lo siguiente: 
![image](https://user-images.githubusercontent.com/48395528/77981474-72a6db80-72e0-11ea-8305-a17dc494aa78.png)

**La idea fundamental es que el cambio se vea lo más claro (que se note) y lo más suave posible (la escala no necesariamente tiene que ser lineal).** Entonces, si logras que el led este apagado cuando no reciba luz y en su máximo nivel de brillo cuando recibe la máxima luz, es lo más mejor del mundo. Pero, de igual modo, tampoco estaría malo si tiene una intensidad de luz muy mínima cuando la luz es nada. Lo importante, es el cambio y la progresión del estado de menos luz (o nada) a máxima. 

Saludos.
