### ISSUE TITLE
Duda sobre rellenar el modo de operación del Timer 1

### ISSUE THREAD

**Issue by moquezada** [IEE2463/classroom#48]
En el código que nos entregaron para el Lab 03 aparece la siguiente sección de código:

```c
  	// Modo de operación Timer 1
  	// Rellenar modo de operación : 
  	TCCR1A &= ~(1 << WGM10);		
	TCCR1A &= ~(1 << WGM11);
  	// Rellenar modo de operación : 
	TCCR1B |= (1 << WGM12);
	TCCR1B &=~ (1 << WGM13);
```

No me queda claro por qué deberíamos rellenar dos veces el modo de operación. Por lo que entendí, son estos 4 bits los que nos permiten seleccionar el modo en el que operará el Timer 1, ¿no deberíamos escribirlo solo una vez?  Mi pregunta surge ya que da la sensación de que cada par de bits se encargara de setear un modo distinto, independiente del otro.

**Comment by fffonceca** [comment]
Hola, tienes toda la razón! Aquí debes rellenar el modo de estos registros con el que tú consideres pertinente. Es el deber de cada persona en el curso leer el datasheet y darse cuenta de esto por sí mismo y rellenarlo.
