### ISSUE TITLE
LAB 06 - Dudas SPI y TFT

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#49]
Dudas relacionadas con el uso de SPI y la TFT

**Comment by ftoyarzun** [comment]
Hola! Quisiera saber si es que hay alguna manera mas rapida de actualizar la pantalla, ya que para cada frame (si se quiere actualizar todos los pixeles) se demora del orden de 5 segundos.
Muchas gracias!

**Comment by fffonceca** [comment]
Hola @ftoyarzun . Efectivamente hay una forma "más" rápida, pero compromete RAM. La idea es cargar un buffer previamente de un tamaño considerable para cargar la pantalla. Ahora el buffer lo debes implementar de la forma que más te acomode, pero esto debería resolver el problema de la demora. Si sigue estando lento lo más probable es que hayan _delays_ en alguna parte de tu código. Te recomiendo jugar un poco con la pantalla y que visualices este comportamiento. Espero que esto te haya ayudado.

**Comment by hagarces** [comment]
Y ese buffer como se carga a la pantalla?

**Comment by felipesanchezvaras** [comment]
@hagarces 
Te recomiendo mirar las funciones disponibles en [`graphic_shapes.h`](https://github.com/IEE2463/classroom/blob/master/Laboratorios/Laboratorio%2006/C%C3%B3digos%20base%20microcontrolador/display/graphic_shapes.h) y la descripción de cada una de ellas. Esto se comentó en la Issue #51 que podría ayudar a resolver el problema de cómo enviar datos a la pantalla.

**Comment by Pochoclo** [comment]
Holi, estuve hasta ahora programando la pantalla usando interrupciones para el SPI y resulta que por curiosidad decidi probar el codigo de la ayudantia usando whiles, la carga en la pantalla vuela. Pensé que interrupciones era mejor, creo que me siento perdido y confundido, en que casos es mejor la utilizacion de interrupciones? Un besito

**Comment by fffonceca** [comment]
Hola @Pochoclo AwA. Que vuele los gráficos en la pantalla depende de dos cosas: de como tienes implementado el código, de qué clock se usa para correr la MSP. Fíjate en esas dos cosas para llegar a tu respuesta. Espero te haya ayudado.

**Comment by Pochoclo** [comment]
Gracias @fffonceca C: 
En el formato de interrupts tenia un ring buffer donde iba guardando los datos para transmitir (tanto el cs_data como el dato a transmitir) y al haber datos, activo el IE. Luego al entrar en el ISR simplemente seteaba el cs correspondiente, escribía en UCB0TXBUF y finalmente desactivo el IE.  De frecuencia lo tengo en 4MHz usando el XT2, por lo mismo me había quedado con la duda :C
