### ISSUE TITLE
Duda PWM Laboratorio 3

### ISSUE THREAD

**Issue by CristobalMery** [IEE2463/classroom#49]
Hola! Tengo la duda de si es obligatorio utilizar el código de la PWM que nos entregan?

Lo digo puesto que para el Bonus del laboratorio 1 realizé la PWM, entonces me preguntaba si podía utilizar ese mismo código que diseñé.

**Comment by fffonceca** [comment]
Hola Cristóbal. Hablamos con los ayudantes y sí puedes hacer eso. Siempre y cuando entiendas las mismas preguntas que se plantean en el código ejemplo, entendiendo que hace cada registro y bit que se configura. Saludos!
