### ISSUE TITLE
Jugador 1 y 2 versus quién juega X y O

### ISSUE THREAD

**Issue by NikiHV** [IEE2463/classroom#5]
Hola equipo docente!
Tengo una duda respecto a los jugadores y las "figuras" que ocuparán para jugar (me refiero a la cruz X o el círculo O).
 
En el enunciado dice que en cada ronda se debe alternar qué jugador comienza, pero también dice que siempre se debe partir con X, entonces entiendo que los jugadores podrán tomar la X o el O dependiendo de la ronda que jueguen, ¿es así?

Me entra la duda porque en la realidad cuando uno juega al gato se "adueña" de una figura y siempre usa esa, entonces podría asignar al primer jugador X y al segundo O y que mantengan su figura todo el juego. Pero como deben alternarse en cada ronda entonces habrían rondas que partiría el O. ¿Puedo implementar este último método o debe ser de la primera manera que lo expliqué (si es que entendí bien el enunciado)?

**Comment by aolivares12** [comment]
Hola!

En efecto, puedes hacer el último método que mencionas al final , donde cada jugador se adueña de una ficha en particular, siempre y cuando en la primera ronda del juego comience el jugador con la ficha X. Igualmente, anota en el README como fue implementado esta parte de tu código.

Saludos!
