### ISSUE TITLE
Problema al cargar código / avr gcc MacOS

### ISSUE THREAD

**Issue by JavierBZ** [IEE2463/classroom#5]
Hola! 
Estoy intentando usar el avr gcc en Mac con el terminal para cargar los codigos al Atmega. Seguí los pasos del tutorial (dentro del enunciado del Lab 1), pero obtengo un error en el último paso:
***(Input)
avrdude -vvvv -p atmega328p -F -c stk500v1 -P /dev/tty.usbmodem14602 -b57600 -D -V -U flash:w:Lab1.hex:i
***(Output) 
Using Port                    : /dev/tty.usbmodem14602
         Using Programmer              : stk500v1
         Overriding Baud Rate          : 57600
avrdude: Send: 0 [30]   [20] 
avrdude: Send: 0 [30]   [20] 
avrdude: Send: 0 [30]   [20] 
avrdude: ser_recv(): programmer is not responding
avrdude: stk500_recv(): programmer is not responding

Busque en la web, pero no pude entender que es lo que esta pasando ni como solucionarlo.

https://www.avrfreaks.net/forum/cant-upload-atmega328p-breadboard
http://forum.arduino.cc/index.php?topic=48922.0

Me aseguré bien de estar en el puerto USB correcto.

Gracias de antemano

**Comment by felipesanchezvaras** [comment]
Este es un problema que se repite en otras ocasiones, la solución que hemos buscado es presionar el botón de Reset del AVR e inmediatamente ejecutar este último paso.

**Comment by JavierBZ** [comment]
Intente hacer eso, pero llegó al mismo error :( . Existe alguna razón por la que puede pasar esto?

**Comment by loky32** [comment]
Si despues de intentar muchas combinaciones de reset el problema persiste puede que necesites un ajuste en la placa AVR, si te encuentras en la universidad comunícate conmigo mediante el correo jecortes1@uc.cl con copia al ayudante coordinador @felipesanchezvaras. Quedo atento
