### ISSUE TITLE
Problema al compilar codigo

### ISSUE THREAD

**Issue by ftgomez** [IEE2463/classroom#5]
Hola, tengo un computador mac y al tratar de compilar el código en la terminal del lab 0 (que está en el enunciado) me sale el error de que no se encuentra el archivo stdio.h. Sabes por qué puede ser? Gracias

**Comment by mignaciavv** [comment]
Hola!
Podrías dar más detalles del proceso que estás realizando y el error que te arroja por favor? 
Saludos,
M. Ignacia
