### ISSUE TITLE
LAB 02 - Instalación CCS

### ISSUE THREAD

**Issue by kisco99** [IEE2463/classroom#5]
Hola! Resulta que no he podido descargar CCS debido a que mi nombre de usuario en el disco duro es "Francisco Valdés" (presenta espacio en blanco y tilde). Para arreglar esto he extraído la carpeta de instalación directamente en el disco duro, pero el programa sigue tirandome el mismo error (username has Unicode characters and CCS fails to install). Les agradecería mucho su ayuda @fffonceca@tomaspinochetv @fer-guzman  @contranton

**Comment by fffonceca** [comment]
Hola @kisco99 . CCS suele ser muy mañoso en estos casos, y de hecho he sufrido el mismo incidente. Ahora mismo tú tienes la solución, la cual es cambiar la carpeta de instalación del CCS con todos sus archivos a un _path_ sin caractéres unicode.

**Comment by kisco99** [comment]
![image](https://user-images.githubusercontent.com/53839911/114782233-b9c70980-9d47-11eb-96cd-784091a49ea5.png)

Hice esto, pero aún así no me funciona. Alguna idea de a qué se debe?

**Comment by jnopazo** [comment]
hola, tengo una duda... Al abrir un nuevo proyecto y querer seleccionar el tipo de microprocesador no me aparece en la lista el MSP430Fxxxx. ¿Qué debo hacer?
![duda](https://user-images.githubusercontent.com/62000792/114801485-c4929600-9d69-11eb-92e3-fa055208df10.png)

**Comment by felipesanchezvaras** [comment]
@jnopazo 
Primero debes seleccionar MSP430X5xx Family. En la pestaña derecha, donde actualmente te aparece "Generic Arm7 Device", debes buscar el MSP430F5529. 

![Screen Shot 2021-04-14 at 21 59 51](https://user-images.githubusercontent.com/7042467/114803084-d32e7c80-9d6c-11eb-8027-df68f454bd5a.png)

Saludos!

**Comment by fffonceca** [comment]
@kisco99 Fíjate en la dirección absoluta donde estés instalando el CCS, y no la carpeta donde descargaste la instalación, sino donde la instalaste.
