### ISSUE TITLE
dudas task 1 lab 2

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#5]
Hola, agradecería responder entre líneas
1) ¿El display **DEBE** partir apagado o puede partir en 00 y una vez que se apriete el botón empezar a contar?

2) ¿Puedo usar solo dos display de 7 segmentos o es necesario usar 3 como en la foto del enunciado?

3) ¿el botón a utilizar es el interno de la placa o el externo que se ve en la foto del enunciado?

saludos

**Comment by GutiJos** [comment]
Hola!
1. Puedes hacer que el display comience en el valor 00.

2. Con dos display 7 segmentos basta.

3. El botón disponible en el arduino corresponde a un botón de reset. Por lo tanto, **debes** utilizar un botón externo con una resistencia pullup o pull down según tu preferencia.

Slds.
