### ISSUE TITLE
bono lab 3

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#50]
Hola, para el bono..." Utiliza un segundo canal de ADC para controlar otro canal del Led RGB"...

¿Puedo usar el timer 2 para compararlo con el timer 1 (siguiendo la misma lógica usada entre timer 1 y 0) y sacar la pwm de un bit distinto a PD0?

Saludos

**Comment by fffonceca** [comment]
Por supuesto, siempre que sea funcional, referenciando correctamente si es necesario y entendiendo cada línea del código.
