### ISSUE TITLE
LAB 06 - Dudas generador de frecuencias

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#50]
Dudas con la pantalla de frecuencias

**Comment by angelux666** [comment]
Hola cuando se debe mostrar la frecuencia de la nota , se refiere a que hay que poner un numero grande en la pantalla en Hz o también se puede mostrar una onda?

**Comment by felipesanchezvaras** [comment]
Hola @angelux666 

Puedes mostrarla frecuencia o la forma de onda, si es qué haces este último, debe ser posible identificar cuál se está realizando. Aquí el diseño queda a libre elección de ustedes siempre y cuando sea posible identificarla.
