### ISSUE TITLE
Fotorresistor lab3

### ISSUE THREAD

**Issue by mlibarra** [IEE2463/classroom#51]
Hola!
Cuando muevo el fotorresistor hacia la parte de menor luz, la resistencia tiende a crecer demasiado, provocando un salto brusco entre valores pequeños de luz y valores más grandes. La conexión la hice según el datasheet, al igual que el cálculo de la resistencia pulldown, ¿Por qué ocurre esto?

Saludos

**Comment by fffonceca** [comment]
Puede pasar por 3 cosas. 
Primero es necesario que tu crees un código acorde para controlar estos cambios bruscos de luminosidad con tu código.
Segundo, puede ser producto de la curva de carga del fotorresistor que no es exactamente lineal, aunque dudo que sea esto.
![imagen](https://user-images.githubusercontent.com/48364596/78203705-09ed6980-746e-11ea-87c5-f74331a064b6.png)
Es probable que estés probando con luminosidades muy relativas que hagan precisamente ese cambio brusco, igual esto debe ser resuelto en el punto 1.
