### ISSUE TITLE
LAB 06 - Dudas Sticker Favorito e interfaz

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#51]
Espacio para dudas relacionado con el despliegue del sticker favorito

**Comment by chineseJack564** [comment]
Hola tengo 2 consultas respecto a este proceso:
1. El ACK\r\n se envia desde micro cada vez que se recive un char para poder recibir la siguiente?
2. el microcontrolador tiene que mandar RDY\r\n al llegar ultima fila de imagen, como sabe el micro si el imagen llego su ultima fila, por ejemplo un sticker de no de tamano 128*128.

**Comment by chineseJack564** [comment]
Hola, otra duda respecto a lo mismo, hize print al mensaje que me llega desde el interfaz, y es algo de este estilo:
![image](https://user-images.githubusercontent.com/69604944/100520625-734c8600-317d-11eb-9c21-821de8bf8ad2.png)
son como numeros bytes, entonces mi pregunta es cuando recibimos en el buffer de recepcion haciendo:
`data = UCA1RXBUF`, que cosa se almacena en data? Un int? Un Char?, pq el valor RGB de cada pixeles es un uint8 , entonces no se como procesar esos valores, 
hize
 `data = UCA1RXBUF
USART_Transmit_String(data)`
y lo que imprime son characteres muy raros.
Quedo atento a su respuesta!

**Comment by RafaelOrmazabal** [comment]
@chineseJack564 Hola! Te recomiendo revisar la representación de bytes con hexadecimales. Eso te debería indicar como procesar los datos.

**Comment by RafaelOrmazabal** [comment]
@chineseJack564 
1) Para responderte esta pregunta voy a citar en enunciado:
'El microcontrolador deberá graficar esta fila y enviarla a la pantalla TFT. Una vez
listo, deberá enviarle un **ACK\r\n** a la interfaz para indicar que puede volver a recibir
información.'
En otras palabras: se recibe una fila->se grafica->Se pide otra fila
2) Considera por mientras stickers de 128x128.

**Comment by chineseJack564** [comment]
> @chineseJack564 Hola! Te recomiendo revisar la representación de bytes con hexadecimales. Eso te debería indicar como procesar los datos.

Hola, 
Toda via estoy un poco confundido, si hago lo siguiente:
`uint8_t R;`
`R = UCA1RXBUF;`
Ese R puede usarlo como argumento de la funcion drawPixelRGB ?

**Comment by felipesanchezvaras** [comment]
@chineseJack564 Te recomiendo mirar la descripción de las funciones `drawPixel` que se encuentran en `graphic_shapes.h`, ya que esto te dará la respuesta para poder saber cómo utilizarlas.

```c
// Most basic of all graphics - set a single pixel to a certian value
// Color is in 565 format (65k colors / one 16bit value).

void drawPixel(int16_t x, int16_t y, uint16_t color);

// The same as above, but with 24bit RGB colors instead of 16bit (Color565)
void drawPixelRGB(uint8_t x, uint8_t y, uint8_t r, uint8_t g, uint8_t b);
```

Por otra parte

> hize
> 
> ```c
> data = UCA1RXBUF;
> USART_Transmit_String(data);
> ```
> y lo que imprime son characteres muy raros.

Los caracteres "raros" que ves, es la representación en [ASCII ](https://elcodigoascii.com.ar/codigos-ascii-extendidos/letra-alemana-eszett-ese-zeta-codigo-ascii-225.html)de un valor hexadecimal. Recuerda que un ASCII es finalmente un valor entre 0 y 127 que es visualizado como un símbolo del alfabeto latino. Pero también está la representación de 0 a 255 de ASCII extendido.
