### ISSUE TITLE
LAB 06 - Avance Proyecto

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#53]
Dudas relacionadas con la implementación de su avance de proyecto. Indicar cuál es su proyecto asignado al momento de preguntar

**Comment by fgarcia100** [comment]
En pou jump, solo hay que hacer que se mueva de un lado a otro con el acelerómetro? O también hay que hacer que salte?

**Comment by felipesanchezvaras** [comment]
Hola @fgarcia100, 
Para el Pou jump puede ser suficiente que se mueva de un lado a otro con el acelerometro. Por el momento no es necesario hacer que salte

**Comment by fgarcia100** [comment]
Ok, muchas gracias
