### ISSUE TITLE
LAB 06 - Dudas Bonus

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#54]
Dudas relacionadas con los distintos bonus disponibles.

**Comment by Polar951** [comment]
Hola!

Cuando hago el reloj con RTC no me deja llamar a la librería RTC, la llamó usando
#include "RTC.h"
Sin embargo, me aparece el siguiente error ¿a qué se debe?
![image](https://user-images.githubusercontent.com/69661120/100699337-7b711500-3379-11eb-80e7-b4176ca42384.png)

**Comment by fffonceca** [comment]
Hola @Polar951. Prueba haciendo `#include <RTC.h>`

**Comment by Polar951** [comment]
> Hola @Polar951. Prueba haciendo `#include <RTC.h>`

Sigo teniendo el mismo error

![image](https://user-images.githubusercontent.com/69661120/100761110-4690ac80-33d1-11eb-957b-0bc8e271ce9d.png)

**Comment by fffonceca** [comment]
Hola @Polar951 . Me había confundido, por un momento pensé que este archivo era parte de la biblioteca. Lo más probable es que estés usando un código de un externo y este tenga la librería en su carpera para llamarla a su disposición. Haciendo un poco de búsqueda encontré la librería [aquí](www.ti.com/lit/zip/slaa290). Viene con ejemplos para la implementación y la librería misma. Para la próxima te recomiendo hacer una búsqueda de estas librerías. Espero se haya solucionado tu inquietud.

**Comment by Polar951** [comment]
Muchas gracias!

Eso si quiero acotar que estaba leyendo el datasheet del rtc adjunto link: https://www.ti.com/lit/an/slaa290a/slaa290a.pdf?ts=1606780126695&ref_url=https%253A%252F%252Fwww.google.com%252F
En el código de ejemplo aparecía la librería muchas gracias por aclarar la duda
