### ISSUE TITLE
Pin AVcc

### ISSUE THREAD

**Issue by mlibarra** [IEE2463/classroom#54]
Hola,
Leí que para escoger un voltaje de referencia externo para el ADC, se debe conectar al pin AVcc mediante un filtro. No encuentro este pin en el arduino, es el pin Vin?
Saludos

**Comment by moquezada** [comment]
Hola, lo que aparece en el datasheed es lo siguiente:
![external](https://user-images.githubusercontent.com/43896576/78326164-121dd580-7550-11ea-95ec-507ba8590f87.PNG)

Debes colocar un capacitor externo en el pin AREF del Arduino con el fin de mejorar la inmunidad al ruido, no en AVcc 🤔
