### ISSUE TITLE
Tiempo de simulación TinkerCad

### ISSUE THREAD

**Issue by gonzalezconstanza** [IEE2463/classroom#55]
Hola,
me pasa que hice la configuración de mi ADC y lo probé aparte de modo de comprobar que estaba funcionando, pero el momento de hacerlo correr en el código junto a la PWM como que se queda pegado porque el tiempo de simulación empieza a contar muy lento, los milisegundos del tiempo de simulación de TinkerCad me corren como segundos. Como puedo solucionar esto?
Hice una issue privada y puse mi link de TinkerCad

**Comment by fjhuanca** [comment]
@gonzalezconstanza Hola! voy al tiro a tu repositorio a revisar. Espérame un poco.
