### ISSUE TITLE
LAB 06 - Otras Dudas

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#55]
Espacio para otro tipo de dudas.

**Comment by chineseJack564** [comment]
Hola,
Con mi compañero estamos estudiando para este lab pero cachamos que la ayudantia del miercoles no ha sido subido, no se si pueden subir la ayudantia para facilitar el estudio, Muchas gracias!
Saludos

**Comment by angelux666** [comment]
hola tengo una duda del archivo graphic_shapes, cuales son los máximos valores de las posiciones x e y para la pantalla?

**Comment by Rafoxxa** [comment]
Hola, tengo una duda respecto a la visualización del termómetro:
1. Si queremos poner una imagen tenemos que leerla desde la interfaz de python o hay una forma de abrir imagenes en c, porque busque y eran bastante complicadas.
2. En vez de utilizar una imagen de termómetro se puede dibujar una barra con las funciones dadas en la librería graphic_shapes?

**Comment by felipesanchezvaras** [comment]
@angelux666 
Las posiciones máximas de la pantalla están dadas por el tamaño de ésta, que es de 128 x 128 pixeles.

@Rafoxxa 
1. Posiblemente las formas que encontraste de cómo abrir una imagen es para C utilizado en computadores, lo que es un proceso distinto. Debes recordar que estamos trabajando en microcontroladores, por lo que hay acciones que se pueden y otras que no se pueden realizar.

Abrir una imagen significa tener una forma de acceder al archivo. En el caso del MSP la única vía de acceso a un archivo es mediante el cable USB, lo que lleva a 2 protocolos de comunicación:

+ USB
+ Puerto serial (UART)

El primero no lo estamos evaluando en el laboratorio. El segundo solo es capaz de recibir o enviar información en paquetes pequeños (bytes), por lo que hay que darles un sentido y aquí es donde entra en apoyo la interfaz gráfica en python que es la vía de comunicación entre la información existente en el PC (archivos,  imágenes u otros) y el microcontrolador, pudiendo así recibir información mediante un protocolo conocido. 

Esta es una de las tantas formas que existen de comunicarse con un microcontrolador, pero en este curso nos centramos en lo que está desde el USB hacia afuera, por esta razón les entregamos la interfaz y no es parte de lo evaluado, ya que se requieren otros conocimientos que no son abordados en SEP. 

2. Cito el enunciado:

> Corroborado lo anterior, deberá incorporar el envío de datos a la pantalla TFT. La forma de visualización será con una barra vertical numerada que crecerá o disminuirá en función de la temperatura medida. Para poder visualizar de mejor forma, se sugiere utilizar un rango pequeño de valores (entre 20 y 35 C u otro que justique la elección).

No dice que deben usar sí o sí la imagen del termómetro, ya que es solo un ejemplo.
