### ISSUE TITLE
Off Topic - Sticker Favorito

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#56]
Espacio para que publiquen sus stickers favoritos, comienzo yo :rocket: 🚁 :sweat_smile: 

![raccoon3](https://user-images.githubusercontent.com/7042467/99847960-b2fce780-2b57-11eb-9499-dc1e765cd0a2.jpg) ![raccoon4](https://user-images.githubusercontent.com/7042467/99847965-b3957e00-2b57-11eb-9f2f-2b77f864b6cf.jpg) ![raccoon5](https://user-images.githubusercontent.com/7042467/99847967-b3957e00-2b57-11eb-87aa-4e5b13abcfee.jpg) ![tomaawa](https://user-images.githubusercontent.com/7042467/99847969-b42e1480-2b57-11eb-9c65-7dcd074af0dd.jpg) ![amimir](https://user-images.githubusercontent.com/7042467/99847970-b42e1480-2b57-11eb-916a-bcd2418f6fd9.jpg)

**Comment by GutiJos** [comment]
MI TURNOOOOO!! 
![perro2](https://user-images.githubusercontent.com/53917450/100481878-5314bc80-30d4-11eb-8230-adc1bbcb4431.png)
![perro3](https://user-images.githubusercontent.com/53917450/100481879-53ad5300-30d4-11eb-82fc-918618395615.png)
![nino1](https://user-images.githubusercontent.com/53917450/100481881-5445e980-30d4-11eb-96c5-ed0bbd67d1fd.png)
![nino2](https://user-images.githubusercontent.com/53917450/100481882-54de8000-30d4-11eb-9da0-5d39ad4741ee.png)
![perro1](https://user-images.githubusercontent.com/53917450/100481885-55771680-30d4-11eb-8af9-ba1dcacaed09.png)

**Comment by GutiJos** [comment]
MI TURNO!!
![perro1](https://user-images.githubusercontent.com/53917450/100481991-ba327100-30d4-11eb-9368-f0d0ea3f81ca.png)
![perro2](https://user-images.githubusercontent.com/53917450/100481994-bb639e00-30d4-11eb-9218-551f5bb3a4d4.png)
![perro3](https://user-images.githubusercontent.com/53917450/100481995-bbfc3480-30d4-11eb-8294-b74201cdbb85.png)
![nino1](https://user-images.githubusercontent.com/53917450/100481997-bc94cb00-30d4-11eb-9a29-1c003d9d5675.png)
![nino2](https://user-images.githubusercontent.com/53917450/100481999-bd2d6180-30d4-11eb-96b3-2b0fd7b39345.png)
