### ISSUE TITLE
Problemas con tinkercad

### ISSUE THREAD

**Issue by JavieraSanMartin** [IEE2463/classroom#57]
Espero que estén bien. Estoy con problemas con tinkercad; cuando pongo un elemento (resistencia, protoboard, etc) desaparece, que puedo hacer? necesito avanzar con el laboratorio D:

**Comment by porellanau** [comment]
Hola! Si quieres te conectas a la sesión de dudas y te podemos ayudar con eso! 

Saludos!

**Comment by porellanau** [comment]
Aquí está el link: https://zoom.us/j/503016321
