### ISSUE TITLE
Sensibilidad Fotorresistor

### ISSUE THREAD

**Issue by sebapulgar** [IEE2463/classroom#58]
Hola, esperando que estén muy bien, tengo una duda con el fotorresistor ya que a niveles de baja luz este es muy poco sensible variando la resistencia en kilo ohms cada vez que movemos la luz que recibe, mientras que en la parte luminosa este solo varia ohms siendo mucho más sensible, esto produce que la respuesta analógica genere un saltos de valores enormes en la parte no luminosa, perdiendose la linealidad en la luminosidad del LED . ¿Esto debemos solucionarlo por medio de software o es producto del software de tinkerkad?.

muchas gracias!

**Comment by fjhuanca** [comment]
Hola! @sebapulgar, al parecer tu duda ya se encuentra resuelta en la issu #51, te remito para allá y si no es suficiente la respuesta por favor háznoslo saber.

Eso, saludos y ánimo!
