### ISSUE TITLE
MSP430

### ISSUE THREAD

**Issue by danielaguilera** [IEE2463/classroom#59]
Hola! Quisiera saber si esta esta es la placa MSP que usaremos para los labs pendientes, por si puedo adelantar ese trabajo.

![image](https://user-images.githubusercontent.com/41979332/78393249-d1f63b80-75bf-11ea-94db-8f2790b5e278.png)

Saludos,

Daniel

**Comment by fjhuanca** [comment]
@danielaguilera Hola Daniel! Me gusta la motivación que tienes así que investigué un poco para ti, el modelo que se usa en el laboratorio es el MSP430f5529 LaunchPad  y encontré estas diferencias en una búsqueda en Google:

**F5529:**
![image](https://user-images.githubusercontent.com/46943236/78408349-47bcd000-75dd-11ea-8911-2b0222fbeab5.png)


1. Increased storage 128KB Flash
2. 12 bit ADC for increased accuracy.
3. Increased RAM, if your application does lot of work+calculations.
4. Cost is very high compared to G2553

***

**G2553:**
![image](https://user-images.githubusercontent.com/46943236/78408373-56a38280-75dd-11ea-855c-0b6f6de4c979.png)


1. 16KB of flash smaller app footprint.
2. 10 bit ADC (depends how accurate the measurement is expected to be)
3. 512 bytes RAM just sufficient for functionas like measure and display the intensity.
4. Cost is very less compared to F5529.

***

En resumen, puede que tengas algunas limitaciones respecto a la que se usa en el laboratorio, pero te serviría bastante para tener una orientación de lo que es programar la MSP430, probablemente compartan varios registros o sean similares para su configuración pero al momento de usar la MSP430 que disponemos en el laboratorio tendrás que adaptar algo tu código. 

Si no me equivoco cuando yo di este ramo para algún distinguido usé una librería de la MSP430G2553 y la adapté para usarla en la MSP430F5529 y fue algo tedioso pero en general eran los mismos registros (funcionalmente) pero con otro nombre.

Eso! saludos y ánimos!
