### ISSUE TITLE
Lab2: "Volver al inicio"

### ISSUE THREAD

**Issue by vicentebelgeri** [IEE2463/classroom#6]
Hola! Quería saber si luego de desplegar la secuencia de los 4 colores, 4 veces, el "volver al estado inicial" se refiere a volver al color rojo? o a que? Gracias

**Comment by tomaspinochetv** [comment]
@vicentebelgeri, volver al color rojo es una buena opción como estado inicial. Lo importante es que puedas volver a pasar los colores de forma ordenada y seleccionando una nueva secuencia.
