### ISSUE TITLE
Repositorio nuevo

### ISSUE THREAD

**Issue by Arturovidalr** [IEE2463/classroom#6]
Hola! 
Como hago el repositorio nuevo para el laboratorio? En la guía salía que teníamos que ver en una lista de enlaces el que tenga nuestro numero de alumno, pero no encuentro esa lista

**Comment by felipesanchezvaras** [comment]
@Arturovidalr El link se encuentra en el README del repositorio. El que dice Haz Click! 
![image](https://user-images.githubusercontent.com/7042467/133018153-4f254bd3-82c6-4601-82e5-ef6aa0edc6ee.png)

El link directo es el siguiente: https://classroom.github.com/assignment-invitations/395a95f07b4d3d772a6d2026889382a5
Aquí deberás seleccionar tu nombre y estará creado. 

Saludos!
