### ISSUE TITLE
Posible bug en Tinkercad con UART

### ISSUE THREAD

**Issue by tito21** [IEE2463/classroom#60]
Intentando el bonus de enviar la luz medida por UART encontré un comportamiento extraño en el simulador.

Dentro de la función main tengo un loop infinito en donde constantemente leo el valor del ADC y después lo envió (junto con un mensaje de texto) por UART. Este loop se corta y no se envían los mensajes ni se lee el ADC. Por otro lado el mensaje SI se envía cuando está dentro de una interrupción de botón. Probando descubrí que el problema solo ocurre cuando llamo a la función que me lee el  ADC.

Sospecho de un bug en el simulador porque cuando cargo el mismo programa en un Arduino UNO físico el programa funciona como esperaba. Se envía el mensaje continuamente y con la interrupcion de botón.

**Comment by fffonceca** [comment]
Si lo probaste en el físico y te funciona claramente es un problema de simulación. De todas formas, podrías mandar tu código para hacer un análisis más profundo de este y poder darte un feedback de como optimizarlo. Optimizar en el sentido de aprovechar bien los tiempos de interrupción con el envió por UART para evitar problemas.

**Comment by tito21** [comment]
En mi repo privada deje el link

**Comment by RafaelOrmazabal** [comment]
@tito21 Como hiciste para cargar el programa en C en un Arduino UNO, usas Arduino IDE o usas otro software?

**Comment by tito21** [comment]
Usando la IDE de Arduino.  Intenté usar Atmel studio pero no me funciona.
