### ISSUE TITLE
[Pacman] Duda sobre la implementación de detección de pared en el proyecto

### ISSUE THREAD

**Issue by chineseJack564** [IEE2463/classroom#61]
Hola,@IEE2463/ayudantes-sep
Espero que esten teniendo un buen fin de semestre, a mi grupo nos tocó implementar pacman en el proyecto, sin embargo, estamos en problema de encontrar una implementación óptima de detección de pared, no se si nos pueden dar algun hint para iluminarnos un poco?
Saludos!

**Comment by felipesanchezvaras** [comment]
@RafaelOrmazabal podría apoyarnos en esta respuesta.

**Comment by RafaelOrmazabal** [comment]
Hola,
Me podrías guiar más o menos en lo que llevas para darte tips más útiles. Te recomiendo además ver el video que subimos al canal de youtube del curso con un ejemplo de un Pacman.

**Comment by chineseJack564** [comment]
> Hola,
> Me podrías guiar más o menos en lo que llevas para darte tips más útiles. Te recomiendo además ver el video que subimos al canal de youtube del curso con un ejemplo de un Pacman.

Hola, lo que pasa esque estoy intentando implementar la mapa de juego y asi detecion de pared, pero no se me ocurre una forma optima de implementarlo, osea ahora lo que se me ocurre es hacer la mapa en un excel de 128 x 128, y pasar esa mapa a un arry multidimensional de 128 x 128, y los lugares con pared le pongo un 1, entoces asi puedo verificar con el posicion de pacman donde hay pared, pero el cantidad de trabjo igual es harto, entonces queria saber si existe otra forma mas inteligente?
Saludos

**Comment by RafaelOrmazabal** [comment]
@chineseJack564  En primer lugar, efectivamente es bastante trabajo dibujar el mapa. Hacer dibujos en excel durante el proyecto es una buena idea y es algo que implementé en varios aspectos del diseño de las etapas y los personajes. No obstante, creo que podría ser un error hacer un array multidimensional de 128x128, en especial cuando implementen más niveles. La cantidad de bytes que usarías sería excesivo. Lo que podrías hacer es tener un array con las posiciones en x de las murallas y otro con las posiciones en y de las murallas. Esto te ahorrara tiempo y memoria. Más aún, si guardas estos datos en la EEPROM, podrías ahorrar aún más memoria. Luego, en cada frame del juego puedes revisar la posición de pacman con respecto a las murallas. Existen otras ideas que te podrían ayudar a optimizar la detección de las murallas. Una de estas podría ser segmentando el mapa o usando bloques que usen más pixeles para disminuir el tamaño de los arrays.

**Comment by chineseJack564** [comment]
> murallas. Esto te ahorrara tiempo y memoria. Más aún, si guardas estos datos en la

Hola, no entiendo muy bien a que te refieres con guardar posicion x y posicion y de las muralllas, por ejemplo si tengo una muralla que empieza de punto (5, 10) y de tamano rectangular (3 x 3) , como se recomendarias guardar eso?
