### ISSUE TITLE
[Proyecto - Space Invaders]

### ISSUE THREAD

**Issue by BelenEchenique** [IEE2463/classroom#62]
Hola! con mi compañero estamos haciendo el Space Invaders y tenemos algunas dudas:

- En el bonus sobre registrar el nombre o apodo del jugador, se debe hacer vía UART? nos surgió la duda porque se supone que el juego debe funcionar sin estar conectado al computador.
- Los dos niveles de dificultad los elegimos nosotros? 
- Qué tan igual se espera que sea el juego con respecto al real? por ejemplo, debemos hacer aliens con distintas formas? es necesario implementar el alien rojo que pasa muy pocas veces? el conteo debe verse en pantalla o podemos mostrarlo solo al final? 

Muchas gracias de antemano!

**Comment by felipesanchezvaras** [comment]
Hola @BelenEchenique ! 
Respondo punto a punto

+ Dado que el programa debe poder funcionar sin estar conectado a un computador, no sería posible ingresar el nombre por UART. Deben buscar una forma alternativa que permita ingresar el apodo del jugador. 
+ Los niveles de dificultad los seleccionan ustedes, la forma de variar uno a otro debe estar especificada en su informe e indicarlo en la presentación. 
+ Hay libertad en cuanto a qué tan parecido debe ser el juego, principalmente por las limitaciones de tamaño de pantalla y procesador. La idea es mantener la esencia del juego, por lo que al menos aparezca un tipo de alien y el alien rojo. Los cambios e implementaciones que realicen deben indicar la razón de porqué se hizo de esa forma (Si realizan o no más aliens, en dónde mostrar el puntaje, etc). La creatividad y elecciones de diseño van por ustedes.

Mucho ánimo !

**Comment by BelenEchenique** [comment]
@felipesanchezvaras  Muchas gracias!
