### ISSUE TITLE
Entrega circuito tinkercad

### ISSUE THREAD

**Issue by cefernandez1** [IEE2463/classroom#62]
Hola, no veo en canvas ningún link para compartir el circuito de tinkercad ¿ Cuándo va a estar disponible para subir la tarea?
Gracias de antemano.

**Comment by felipesanchezvaras** [comment]
Hola ! 

Como fue informado en el último anuncio de Canvas, debes compartir tu link del circuito de TinkerCad en el Readme de tu repositorio, junto con una captura de pantalla de tu circuito.

Saludos !

**Comment by assilva2** [comment]
y como ponemos una imagen en el codigo que subimos? traté con copy y paste, pero no funcionó.

**Comment by moquezada** [comment]
Con una rápida búsqueda en google encontré [esto](https://markdown.es/sintaxis-markdown/#imagenes). En primer lugar, puedes subir las imagenes a tu repositorio y luego utilizar el link de esas imágenes para referenciarlas en formato markdown :eyes:
