### ISSUE TITLE
[PACMAN] Acelerar aún más el clock

### ISSUE THREAD

**Issue by Polar951** [IEE2463/classroom#64]
Hola!

Tengo un problema con mi juego y es que mis fantasmas y pacman se mueven muy lento debido creo a la velocidad del clock (ya que cuando solo tengo mi pacman encuentro que se mueve a una velocidad aceptable) ¿Cuál es la forma en la que puedo poner a la msp para que saque su máximo rendimiento, algún capítulo del user guide que me pueda ayudar?

**Comment by RafaelOrmazabal** [comment]
Hola,
Lo más probable es que tu problema no tenga nada que ver con el clock. Cuando el programa se vuelve considerablemente más lento por cada personaje que agregar el problema se debe a que no estás reciclando suficientes pixeles de los personajes. Si ves que los fantasmas y pacman tintinean cuando se mueven, el problema definitivamente es el que te mencioné, te lo digo por experiencia propia. Aumentar la velocidad del clock no va a solucionar tu problema, porque el tema es la cantidad de pixeles que tienes que dibujar, y eso es un tema del spi y la pantalla.

**Comment by chineseJack564** [comment]
Hola,
Yo tengo el mismo problema, no esque los fantasmas y pacman se tintinean cuando se mueven, sino que como CCS no supporta multithreading, uno tendria que poner como la lectura de adc y la desicion de monstruo en cada ciclo de while, eso produce que el programma corre mas lento en cada cilo, por lo tanto moviendo mas lento. No se si hay alguna forma de resolver eso?
Saludos!

**Comment by fffonceca** [comment]
@chineseJack564 Hola! Voy a apoyar a mi compañero @RafaelOrmazabal aquí. Efectivamente no hay multithreading en este microcontrolador, pero la frecuencia a la cual se refresca debe ser suficiente para que el usuario vea la experiencia. Cómo podrían evitar esto? simplemente bajando la cantidad de procesamiento y recursos que ocupan los demás módulos. Podrían ocupar un timer con interrupciones para refresar la pantalla y así se aseguran de que cada cierto tiempo la pantalla se vea fluida. Si la lectura del ADC les produce problemas, pueden gatillar una conversión de datos a una tasa T de un timer también, y los demás módulos tienen carácterísticas que ayudan a bajar los recursos que se usan (clock scaler, ciclos de trabajo, etc...).
Espero esto haya ayudado un poco
