### ISSUE TITLE
[PACMAN] Multithreading de pacman con monstruo y comportamiento de monstruo

### ISSUE THREAD

**Issue by chineseJack564** [IEE2463/classroom#65]
Hola, 
Para la implementacfion de monstruo tengo 2 dudas:
1.  Yo queria implementar monstruo como un threading, sin embargo, ccs no esta incluido con la libereria de threading en c, entonces tendria que implementar de la forma que el pacman y mosntruo se mueve dentro de un while noma?
2. Tengo la duda sobre que tan inteligente tiene que ser el monstruo, hasta ahora tengo implementado un random que dedice 1 de los 4 direcciones, sin embargo , bajo este contexto, el monstruo no mueve como en el juego original, entonces queria saber cual es requerimiento sobre el comportamiento de monstruo.
Saludos!!

**Comment by RafaelOrmazabal** [comment]
Si reciclas pixeles, no se te debería atrasar el programa con los fantasmas. Mira el ejemplo que subimos de un pacman al canal de curso de youtube, ahi los fantasmas y pacman están en el while.
Los fantasmas deberían verse como en el video de Youtube o con más inteligencia. Eso es implementable con un random, pero tienes que decidir inteligentemente cuando ejecutar el random.
