### ISSUE TITLE
[PRESENTACIÓN] Duda de formato de presentación

### ISSUE THREAD

**Issue by Rafoxxa** [IEE2463/classroom#66]
Para la presentación del viernes ¿hay que mostrar ppt, pdf o algún recurso visual además de los diagramas?
También queríamos saber con mi compañera si podemos grabar un video con el ejemplo de implementación ya que puede ser un tanto incómodo mostrarlo en la cámara durante la sesión.

**Comment by felipesanchezvaras** [comment]
@Rafoxxa 

Un ppt y/o pdf son buenos recursos para realizar la presentación, ya que ayuda a mostrar lo implementado. Y si tienen un video grabado sería ideal. De todas formas, está la posibilidad que les pidamos mostrar el funcionamiento en vivo. 

En semestre pasado, para mostrar el proyecto utilizamos los celulares como una cámara de apoyo, así podíamos apuntar directamente el proyecto.

**Comment by Rafoxxa** [comment]
Muchas gracias!!
