### ISSUE TITLE
LAB 04 - Dudas Ring Buffer 

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#66]
Dudas relacionadas con Ring Buffer

**Comment by mlibarra** [comment]
Hola! Para este modo de juego, el puntaje máximo cómo sería? Me imagino que si hay una secuencia de 3 colores, al completarla el máximo es 3, pero luego aparece otra secuencia de 3 colores, si se completa el máximo es 6? Saludos

**Comment by fffonceca** [comment]
Hola! Para responder esta issue acabo de crear una explicación improvisada para eliminar cualquier duda sobre ring buffer o la implementación de esta que pueda surgir. Con respecto a tu pregunta, recuerda que el tamaño del buffer solo puede ser cambiado **antes de compilar**, y debe ser destacado dentro del código para poder ser cambiado para su evaluación.

Lo demás se responder en la siguiente imagen:

![RingBuffer_lab4](https://user-images.githubusercontent.com/48364596/83219592-bda56980-a13e-11ea-9a37-eb709c5cf358.png)

**Comment by mlibarra** [comment]
Si tengo dudas con la implementación que hice (respecto a si cumple lo pedido), puedo consultarlo en mi repositorio?

**Comment by rhastudillo** [comment]
Entonces, para ver si entendí, el máximo de datos a recordar (en el último nivel) siempre será n, solo que el elemento 1 pasa a ser el 2do del original, y el último pasa a ser el nuevo ?

**Comment by felipesanchezvaras** [comment]
@rhastudillo Así es !

**Comment by IsabelJamett** [comment]
Hola!
Entonces solo se deben mostrar los ultimos n colores en la interfaz y la persona debe presionar solo maximo n colores? O se deben mostrar todos igualmente?

**Comment by CamilaTurrieta** [comment]
Hola @IsabelJamett cuando seleccionas el modo Ring Buffer y el juego parte debería pasar lo siguiente:
1. Muestra un color.
2. Apretas correctamente el color
3. Muestra el mismo primer color y otro color.
4. Vuelves a apretar la secuencia correctamente

Así hasta alcanzar el tamaño del buffer, supongamos de tamaño n.

Cuando alcanzas ese punto y se sigue anotando correctamente. La secuencia a anotar será sólo de n elementos siempre . ¿Me explico? 

Recuerda que, cuando ya sólo se muestra secuencias de n elementos, luego de que hayas ingresado la secuencia correcta, la interfaz mostrará los últimos n-1 elementos de la secuencia anterior + un nuevo alemento generado aleatoriamente. 

Cuéntame si esto lo dejo más claro o dejo más dudas.
