### ISSUE TITLE
[Proyecto] Uso optimo de la Memoria

### ISSUE THREAD

**Issue by chineseJack564** [IEE2463/classroom#67]
Hola,
Nosotros estamos haciendo pacman, y nos estamos enfrentando problema de memoria del MSP con el siguiente mensaje de error:
Description	Resource	Path	Location	Type
<a href="file:/C:/ti/ccs1010/ccs/tools/compiler/dmed/HTML/10099.html">#10099-D</a>  program will not fit into available memory, or the section contains a call site that requires a trampoline that can't be generated for this section. run placement with alignment fails for section ".bss" size 0x4c.  Available memory ranges:	lnk_msp430f5529.cmd	/Proyecto_sep	line 139	C/C++ Problem

La cosa es que para cada nivel, tenemos 2 arry de coordenada x de los paredes y coordenada y de los paredes respectivamente, y son en total asi 3000 int por nivel. No nos producia problema para el nivel 1 , sin embargo, para agregar el nivel 2 saturo la momeria, intente definirlos como static int y tampoco funcionan. (Antes era int globales noma).

Entonces queria saber si tienen algun metodo para optimizar esto?
Saludos!

**Comment by fffonceca** [comment]
Hola @chineseJack564 Espero que estés bien. Para caracterizar un elemento del mapa no sería mejor usar un char para caracterizar varios pixeles?. Daré un ejemplo.... Digamos que tu usas un INT y que hay 4 tipos de objeto que los describes con los números [0, 1, 2, 3]. Por lo que tu podrías tener:
```
int MAPA;
MAPA = {1, 1 , 2 , 3 , 0 , 1, .......} ;
```
Pero podrías usar un arreglo de CHARS y que la mitad del char caracterize primera posición y que la segunda parte caracterize la segunda posición así:
```
char MAPA;
MAPA = {0x11, 0x23 , 0x01 , .......} ;
```
Así podrías ahorrar un poco de memoria, después inventar un tipo de función que juegue con los arreglos y vea el mapa completo!. Aquí también dejo un link para el uso de memoria, así ven en tiempo real cuando compilan código de cuanta RAM usan: [LINK](https://www.youtube.com/watch?v=LwxwJjq2IEg)

Espero esto te haya ayudado a optimizar tu código. Dime si esto resuelve tu problema.

**Comment by chineseJack564** [comment]
> Hola @chineseJack564 Espero que estés bien. Para caracterizar un elemento del mapa no sería mejor usar un char para caracterizar varios pixeles?. Daré un ejemplo.... Digamos que tu usas un INT y que hay 4 tipos de objeto que los describes con los números [0, 1, 2, 3]. Por lo que tu podrías tener:
> 
> ```
> int MAPA;
> MAPA = {1, 1 , 2 , 3 , 0 , 1, .......} ;
> ```
> 
> Pero podrías usar un arreglo de CHARS y que la mitad del char caracterize primera posición y que la segunda parte caracterize la segunda posición así:
> 
> ```
> char MAPA;
> MAPA = {0x11, 0x23 , 0x01 , .......} ;
> ```
> 
> Así podrías ahorrar un poco de memoria, después inventar un tipo de función que juegue con los arreglos y vea el mapa completo!. Aquí también dejo un link para el uso de memoria, así ven en tiempo real cuando compilan código de cuanta RAM usan: [LINK](https://www.youtube.com/watch?v=LwxwJjq2IEg)
> 
> Espero esto te haya ayudado a optimizar tu código. Dime si esto resuelve tu problema.

Hola, entiendo la solucion , pero implementarlo implica 2 dificultades:

1.  Al cambiarlo seria cambiar toda la funcionalidad de la funcion cheakear colision nuestro, no se si por tema de tiempo vamos a alzanzar, entonces queria saber cuando baja por tener solo 1 nivel funcional.
2.  Aunque dedidimos cambiar, hay pixeles donde la coordenada es de 1 digito, hay lugares con 2 digitos y con 3 digitos, entonces como podemos representar todo eso con char?

saludos!

**Comment by fffonceca** [comment]
Efectivamente requiere de un poco de complejidad la implementación, pero es el _trade-off_ para alcanzar optimización de RAM. Además, el MAPA debería tener un arreglo tal que tu sabes la posición del objeto solo viendo la posición del MAPA. Es decir, cuando el PACMAN llega a cierta posición de MAPA (a una posición (x,y) ) viene dado por el mismo arreglo.

Podrías usar un puntero para saber en qué posición de MAPA estás y ahorrar los bits de posición de cada parte de MAPA. Si pacman está en una posición:
```
void chekeo_next(struct Pacman *monito, char MAPA[], char mov_x, char mov_y){
Posx_next=monito->pos_x+mov_x;
Posy_next=monito->pos_x+mov_y;
elemento_en_mapa = MAPA[Posx_next+Posy_next*128];  //Le faltaria esto de achicar el arreglo para 0x.. 

if(elemento_en_mapa==0){ %Si no hay nada...
     monito->pos_x = Posx_next
     monito->pos_y = Posy_next
}
else if(elemento_en_mapa==1)... y asi
}
```
No se si esto te ayude sinceramente, pero es una implementación para no tener que complicarte con la posición.

**Comment by tomaspinochetv** [comment]
Hola, estaba probando lo del video, resulta que me dice que tengo solo un 10% a 12% utilizado de FLASH, y 29% de RAM, esto ultimo porque puse algunos mapas en ella. Mi problema es que llegando al 15% de la FLASH, razón por la que metí algunos mapas en la RAM, el programa compila, pero nunca corre, no hace absolutamente nada, si me voy al modo debug, se queda metido en "unas cosas raras de inicio", pero no entra siquiera al programa. Ya se nos dijo que estábamos bien con la cantidad de mapas, pero llevo todo el día intentando entender el porque llegando a 16 KB de FLASH, la msp deja de funcionar.
dejo un ejemplo donde agregue algunos mapas y la msp dejó de funcionar.

Saludos y agradezco su tiempo.
![image](https://user-images.githubusercontent.com/69913608/102562462-e038a900-40b5-11eb-8fe2-dbb94f9197e9.png)
