### ISSUE TITLE
LAB 04 - Dudas Linked List

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#67]
Dudas relacionadas con Linked List

**Comment by danielauu** [comment]
Hola, estoy un poco aproblemado con la inicialización en el main de mi linked list. Definí mi estructura tipo linked list y a la estructura del juego le incorporé 2 punteros del tipo linked list. En el main, intento asignar espacio en memoria para mis linked list llamando a malloc y el código ya no compila.  😢

**Comment by Michel1297** [comment]
Hola, tal como me lo propusieron @felipesanchezvaras   y @CamilaTurrieta  , el error se solucionó instanciando el nodo dentro de una función y  creándolo afuera de esta de la siguiente forma : "struct Nodo * Nodo1; " ( le quité el NULL) , y aunque siguen aparenciendo warnigs, el código funciona!
