### ISSUE TITLE
Juego Lab 4- tiempo y cantidad de laberintos

### ISSUE THREAD

**Issue by JavieraSanMartin** [IEE2463/classroom#68]
Hola!!

Espero que se encuentren bien. Les escribo porque con mi compañero tenemos algunas dudas que ojalá nos puedan resolver. Por un lado, para nuestro juego (laboratorio 4) tenemos un total de 4 laberintos, ¿es esto suficiente?.  Y por otro lado, queríamos saber si el tiempo (que toma cada persona en resolver un laberinto) debe ser mostrado constantemente (todo el tiempo) o solo al final del juego (al resolver el laberinto). Nos quedamos atentos. Gracias de antemano. 

Saludos

**Comment by fffonceca** [comment]
Hola @JavieraSanMartin . Estamos bien, espero que tú igual. Con respecto a los niveles es una buena cantidad, por lo que pueden quedar satisfechos (en la rúbrica salen 2 niveles). Con respecto al tiempo, lo pueden mostrar al final si es que tienen problemas de procesamiento, RAM, u otros... Saludos!
