### ISSUE TITLE
duda DIR/POUT

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#7]

**Comment by CamilaTurrieta** [comment]
No puedo ver tu duda. No se si la borraste y ya resolviste el problema. Por lo que puedo ver de lo que mostrabas antes, debería solo estar encendido el pin 1.2. Sin embargo, no se si ese es tu código completo y si tu ciclo while(1) es el que muestras como destacado.

**Comment by diegomarusic** [comment]
hola sii ya resolví el problema y lo borré para no molestar más de lo necesario :)

**Comment by felipesanchezvaras** [comment]
@diegomarusic en proximas ocasiones, cuando ya hayas resuelto el problema, puedes publicar tu solución para así ayudarnos a nosotros y a tus compañeros que tal vez tienen el mismo problema :) . Esto es preferible a borrar la duda, ya que no sabemos si es que está solucionada o no.

Saludos !

**Comment by diegomarusic** [comment]
okk
