### ISSUE TITLE
"Hora de simulador" tinkercad

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#7]
¿qué significa que al simular un programa en tinkercad, no me arroje ningun problema de código pero la hora de simulador no parta? (en específico estoy tratando de medir con el osciloscopio una pwm que generé, revisé 3 veces el código y debiese estar todo bien)

**Comment by CamilaTurrieta** [comment]
Hola @diegomarusic ! Cómo primer error probable es que esté mal conectado. Si el error sigue, puedes subir tú código a tu repositorio de GitHub y una foto de la simulación idealmente, para que veamos si podemos darte ideas. Me cuentas!

**Comment by diegomarusic** [comment]
subido!

**Comment by CamilaTurrieta** [comment]
@diegomarusic ¿Subido en dónde?

**Comment by diegomarusic** [comment]
IEE2463/laboratorio-01-diegomarusic Issues
https://github.com/IEE2463/laboratorio-01-diegomarusic/issues/1

te etiqueté nose si te llega la notificación

**Comment by CamilaTurrieta** [comment]
@diegomarusic  efectivamente hay un problema al simular PWM con código C en tinkercad. Por el momento te sugiero que realices las ideas de bonus que son un poco más simples (es decir, que puedan ser escritas en C en tinkercad y funcionen). Mil disculpas por no avisar antes y estamos viendo como podemos solucionar esto. 

Ánimo y paciencia en estos tiempos de crisis.

**Comment by diegomarusic** [comment]
oka no hay drama, gracias por responder todas mis preguntas jaja

**Comment by CamilaTurrieta** [comment]
Estamos para eso 😄! gracias a ti por la motivación y preguntar ! ❤️
