### ISSUE TITLE
Problema con LED RGB

### ISSUE THREAD

**Issue by NikiHV** [IEE2463/classroom#7]
Hola,
Tengo un problema con mi LED RGB del BoosterPack. No logro prender el **color azul**. He intentado de todo, he buscado por internet, mandé algunos correos y whatsapps, pero no lo he podido solucionar (me tiene muy desesperada).

Además, cuando intento jugar con el led **verde** a veces funciona y otras veces me prende en amarillo (cuando nunca he prendido el rojo!). 

Esto me ha tenido estancada muuucho tiempo y ya no sé qué hacer.

Código que he escrito en C para prender LED azul y NO funciona (no se prende nada):
```
#include <msp430.h> 

void main(void)
{
	WDTCTL = WDTPW | WDTHOLD;	    // stop watchdog timer
        
        // Asignar Pin 1.4 (Led rgb azul) como output
	//P1DIR = 0x0000;              // linea que he probado agregar, sin resultado
	P1DIR |= BIT4; 	           // también probe con P1DIR = BIT4; sin resultados

 	P1OUT |= BIT4;                 // Para prender el led, también probé P1OUT = BIT4; o con un ciclo while. Sin resultados
}
```

**Comment by felipesanchezvaras** [comment]
@NikiHV segun lo conversado e informado por el ayudante @aolivares12 , se concluyó que es un problema de hardware.
