### ISSUE TITLE
Lab 2: Task 1, cargar el archivo a la MSP

### ISSUE THREAD

**Issue by pabloftroncoso** [IEE2463/classroom#7]
Al momento que intento cargar el archivo hello world.c a la MSP me muestra la siguiente interfaz y se mantiene ahi por mas de 20 minutos
![image](https://user-images.githubusercontent.com/81479458/115265565-59e4b000-a105-11eb-86fe-a1943b562062.png)
Es primera vez que conectaba la MSP  mi computador y primera vez que intento cargar una archivo.
Si uso la msp y apreto el BTN1 se cambia el color del led de uno en uno, pero antes nunca habia implementado nada. Esto ocurre paralelamente me sale en la pantalla la imagen que subi

**Comment by felipesanchezvaras** [comment]
@pabloftroncoso 

Copio la respuesta entregada por correo, ya que podría ser útil para otros. 

Hola Pablo,
Dame algunos antecedentes para comprender mejor el problema.
+ Version de Code Composer que se instaló
+ Sistema operativo de tu computador (versión).
+ Cantidad de RAM.
+ Tienes algún antivirus funcionando ?
+ Captura de pantalla del error que te aparece.
+ Confirmar que el proyecto fue creado correctamente. 

Mientras tanto y tal vez puede ser la solución. Code Composer tiene una versión que funciona en la nube. A esta se accede a través de un navegador. El link directo es https://dev.ti.com/tirex/wizard y puedes verlo en la misma página desde la que se descarga Code Composer Studio.

Algunos pasos a seguir, sería 

+ Desintalar Code Composer e instalar una versión más antigua (nro 8 o 9). 
+ Cerrar todos los programas que tengas abiertos. Detener el antivirus y ver si el problema persiste.

**Comment by pabloftroncoso** [comment]
tengo instalada la version 10 de CCS
mi computador tiene windows 10
8 GB de ram
Tenia windows defender activado, no tengo nada externo, lo acabo de desactivar, tengo que instalar denuevo ccs?
la captura de pantalla la deje en las issues del curso

Voy a intentar lo de trabajar en la nube pero prefiero trabajar en el pc de manera estándar y solucionar este problema

**Comment by pabloftroncoso** [comment]
Ademas de desactivar el antivirus, actualice la version 10 de CCS desde el mismo programa ya que me ofrecía un update. Despues de eso volvi a correr el codigo, le hice build sin ningun problema, pero ahora al entro al modo debug y me sale esto
![image](https://user-images.githubusercontent.com/81479458/115572079-9216fa80-a28d-11eb-8c38-ef78af4b63aa.png)

**Comment by pabloftroncoso** [comment]
Acabo de descargar la version 9 y al momento de inciar el debug me sale lo mismo 
![image](https://user-images.githubusercontent.com/81479458/115578341-33547f80-a293-11eb-99fc-2cd351154f27.png)

**Comment by pabloftroncoso** [comment]
Y con respecto al programa en la nube, despues de seguir todos los pasos que me indica, llego hasta aqui y me sale un error similar al del programa en el pc
![image](https://user-images.githubusercontent.com/81479458/115579171-e4f3b080-a293-11eb-978f-6e16b4cbd35a.png)

**Comment by pabloftroncoso** [comment]
Acabo de probar la msp en el computador de un amigo y sigue con problemas similares, aqui adjunto pantallazos de los que salio al intentar entrar en modo debug.

En primer lugar 

![image](https://user-images.githubusercontent.com/81479458/115804198-81ab7080-a3b0-11eb-9fc7-125e307aed68.png)

Y despues salio este 

![image](https://user-images.githubusercontent.com/81479458/115804237-94be4080-a3b0-11eb-90d7-6d25d5c1a633.png)

Voy a intentar el segundo paso y borrar la memoria de la MSP

**Comment by pabloftroncoso** [comment]
Instale el programa y seguí los pasos hasta que en el paso 4 al apretar read target device me sale esto:
![image](https://user-images.githubusercontent.com/81479458/115804958-ff23b080-a3b1-11eb-93b2-1f0005bcae3e.png)

**Comment by pabloftroncoso** [comment]
Es el mismo error que se muestra en 2 de las interfaces que publique anteriormente

**Comment by felipesanchezvaras** [comment]
@pabloftroncoso 
Ojo que uno de los errores que indicaste:

![image](https://user-images.githubusercontent.com/7042467/115810301-b53fc800-a3bb-11eb-9ab7-202628f3a471.png)

Es porque seleccionaron mal la tarjeta. En ese proyecto es MSP430F5229, y la tarjeta del curso es MSP430F5529. Hay un 5 y un 2 de diferencia. 

Otra opción que podrías probar, es programar que al momento de programar la tarjeta, presiones constantemente el botón RST para tal vez saltarse el problema. 

Este es un error que antes no habíamos visto y estamos buscando cómo poder solucionarlo. (foros, TI, etc.)

**Comment by felipesanchezvaras** [comment]
@pabloftroncoso Puedes subir una foto de tu MSP ? Para corroborar la posición de los headers. También una foto del MSP conectado con un cable usb al computador, pero sin abrir Code Composer, para ver que Leds se encienden.

**Comment by pabloftroncoso** [comment]
> @pabloftroncoso
> Ojo que uno de los errores que indicaste:
> 
> ![image](https://user-images.githubusercontent.com/7042467/115810301-b53fc800-a3bb-11eb-9ab7-202628f3a471.png)
> 
> Es porque seleccionaron mal la tarjeta. En ese proyecto es MSP430F5229, y la tarjeta del curso es MSP430F5529. Hay un 5 y un 2 de diferencia.
> 
> Otra opción que podrías probar, es programar que al momento de programar la tarjeta, presiones constantemente el botón RST para tal vez saltarse el problema.
> 
> Este es un error que antes no habíamos visto y estamos buscando cómo poder solucionarlo. (foros, TI, etc.)

Corregi lo de elegir mal la msp en otro computador y efectivamente corrio el programa sin ningun problema, pero al momento de correrlo en mi computador el error se repite

**Comment by tomaspinochetv** [comment]
@pabloftroncoso Prueba instalando energia IDE en tu PC para ver si lo logras algo (solo a modo prueba ya que no se puede usar para desarrollar el laboratorio) https://energia.nu/download/.
Si eso no funciona, prueba entrando al administrador de tareas, pestaña inicio y bloquea todas las aplicaciones que no son esencial que se inicien al prender el pc.
Si eso no funciona, ¿Puedes resetear el PC? hay un modo donde solo se borran los programas y deja los archivos como fotos y otros. O si respaldas todo en el Drive (Acuérdate que tenemos espacio ilimitado asique igual es bueno tener un respaldo...) podrías hacer una restauración a fábrica.

**Comment by pabloftroncoso** [comment]
> @pabloftroncoso Puedes subir una foto de tu MSP ? Para corroborar la posición de los headers. También una foto del MSP conectado con un cable usb al computador, pero sin abrir Code Composer, para ver que Leds se encienden.

![image](https://user-images.githubusercontent.com/81479458/115935813-fb4f6700-a461-11eb-9f9c-d1aa0b99648a.png)

Aqui esta una foto de la msp, quedo el led prendido porque creo que quedo cargado el programa que probe ayer en el computador de un amigo, pero esa seria la foto sin abrir code composer

**Comment by pabloftroncoso** [comment]
> @pabloftroncoso Prueba instalando energia IDE en tu PC para ver si lo logras algo (solo a modo prueba ya que no se puede usar para desarrollar el laboratorio) https://energia.nu/download/.
> Si eso no funciona, prueba entrando al administrador de tareas, pestaña inicio y bloquea todas las aplicaciones que no son esencial que se inicien al prender el pc.
> Si eso no funciona, ¿Puedes resetear el PC? hay un modo donde solo se borran los programas y deja los archivos como fotos y otros. O si respaldas todo en el Drive (Acuérdate que tenemos espacio ilimitado asique igual es bueno tener un respaldo...) podrías hacer una restauración a fábrica.

voy a probar lo de restauracion de fabrica

**Comment by pabloftroncoso** [comment]
> > @pabloftroncoso Prueba instalando energia IDE en tu PC para ver si lo logras algo (solo a modo prueba ya que no se puede usar para desarrollar el laboratorio) https://energia.nu/download/.
> > Si eso no funciona, prueba entrando al administrador de tareas, pestaña inicio y bloquea todas las aplicaciones que no son esencial que se inicien al prender el pc.
> > Si eso no funciona, ¿Puedes resetear el PC? hay un modo donde solo se borran los programas y deja los archivos como fotos y otros. O si respaldas todo en el Drive (Acuérdate que tenemos espacio ilimitado asique igual es bueno tener un respaldo...) podrías hacer una restauración a fábrica.
> 
> voy a probar lo de restauracion de fabrica

Funciono, lo restaure de fabrica completamente y ahora puedo cargar el codigo gracias!

**Comment by felipesanchezvaras** [comment]
@pabloftroncoso Gracias por avisar !
