### ISSUE TITLE
[Mac High Sierra] Problema al instalar avr gcc

### ISSUE THREAD

**Issue by aamacaya** [IEE2463/classroom#7]
Estoy teniendo problemas al instalar avc gcc. Seguí los pasos de la guia de laboratorio, ningún problema en los primeros pasos, pero al ejecutar:

brew install avr-libc

Aparece el siguiente error:

$ brew install avr-libc
Error: No available formula with the name "avr-libc" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

Busque en internet y al parecer es un error relacionado con High Sierra. 

El problema es el "not formulae found in taps"

Recomiendan ejecutar la siguiente linea de código:

brew install avr-gcc

(https://github.com/osx-cross/homebrew-avr/blob/master/README.md 
https://stackoverflow.com/questions/53742369/using-brew-install-avr-libc-command-on-mac-produces-error-no-formulae-found-i)

Sin embargo esto también me produce error.

A alguien más le ha pasado eso? Alguna forma de solucionarlo?

**Comment by loky32** [comment]
Hola, que tal, te propongo que ejecutes el siguiente comando que procederá a instalar todo lo relacionado a avr:
brew install avr-gcc
Demora bastante así que paciencia, pero terminado el proceso ya podrás correr el compilador.
Para el toolchain avrdude utiliza el comando en la guía pero quita la parte de --with-usb
