### ISSUE TITLE
LAB 04 - Respuestas útiles.

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#70]
Las siguientes son respuestas útiles para algunos problemas detectados. 
Para usuarios Windows:

> > Lo siento, se borro mi comentario anterior. El gcc lo instale buscando en "[msys2/MSYS2-packages#293](https://github.com/msys2/MSYS2-packages/issues/293)" instalando pacman -S mingw-w64-x86_64-toolchain
> 
> 
> 
> > Buenas tardes. Escribo puesto que el archivo compile.script no me funciona correctamente. Cada vez que lo ejecuto, me lanza lo siguiente:
> > ![image](https://user-images.githubusercontent.com/61991953/82739474-c85e9980-9d0d-11ea-91ca-20c5e20261c1.png)
> > Por ende, no puedo ver reflejados los cambios que realizo en el código, en el comportamiento de la interfaz.
> 
> Logré solucionar mi problema realizando lo que @mlibarra mencionó previamente: instalando **pacman -S mingw-w64-x86_64-toolchain** en la consola de msys64. Creo que aquello no se menciona en el tutorial; por ende, podría ser de utilidad si alguien más tiene el mismo problema.
> Gracias igualmente!
> 
> _Originally posted by @CristobalMery in https://github.com/IEE2463/classroom/issues/64#issuecomment-633133720_

Para usuarios de Linux y Mac 

> Cambie todos los "\" los path del archivo main.glade por "/" y funciono.
> _Originally posted by @dabalada in https://github.com/IEE2463/classroom/issues/64#issuecomment-632929587

**Comment by danielaguilera** [comment]
Hola buenas! Seguí todos los pasos de la guía, me metí al path donde están los archivos del laboratorio e incluso instalé todos los paquetes indicados en el comentario anterior. Sin embargo, me sigue arrojando el mismo error:
![image](https://user-images.githubusercontent.com/41979332/83099900-8e2e2880-a07c-11ea-8006-09599350f6de.png)

**Comment by danielaguilera** [comment]
Además me arroja el siguiente error al intentar abrir

![image](https://user-images.githubusercontent.com/41979332/83103468-bfaaf200-a084-11ea-8417-ac2380abbef1.png)

**Comment by RafaelOrmazabal** [comment]
> Además me arroja el siguiente error al intentar abrir
> 
> ![image](https://user-images.githubusercontent.com/41979332/83103468-bfaaf200-a084-11ea-8417-ac2380abbef1.png)

Tengo exactamente el mismo error

**Comment by RafaelOrmazabal** [comment]
@danielaguilera Yo lo estaba corriendo desde mingw64 y me funcionaba más o menos, se demoraba mucho en imprimir. Ahora lo arregle agregando el segundo path que indico el profe, pensé que lo había hecho pero se me pasó.

**Comment by fjpessot** [comment]
> Hola buenas! Seguí todos los pasos de la guía, me metí al path donde están los archivos del laboratorio e incluso instalé todos los paquetes indicados en el comentario anterior. Sin embargo, me sigue arrojando el mismo error:
> ![image](https://user-images.githubusercontent.com/41979332/83099900-8e2e2880-a07c-11ea-8006-09599350f6de.png)

Me pasa lo mismo

**Comment by felipesanchezvaras** [comment]
@fjpessot @danielaguilera 
Les comparto otra forma que podría ver si el error va por acá.

En la carpeta C:\msys64\mingw64\lib deberían chequear que pkg-config y gcc estén instalados.

![image](https://user-images.githubusercontent.com/7042467/83575211-0b362380-a4fd-11ea-82d4-fda2fac68349.png)

Si están, el problema podría ser que no se encuentran.

En MSYS2 ejecuta la linea 
```
pkg-config --modversion gtk+-3.0
```
Esta debería repetir el error que te aparece a tí ,ya que no lo encontrará, en mi caso, obtengo esto:

![image](https://user-images.githubusercontent.com/7042467/83574857-4d129a00-a4fc-11ea-98e7-9998911f49a4.png)

Lo cual ocurre porque  PKG_CONFIG_PATH. encuentra la carpeta que contiene los archivos, esto se puede chequear haciendo 
```
echo $PKG_CONFIG_PATH
```
![image](https://user-images.githubusercontent.com/7042467/83575428-708a1480-a4fd-11ea-81ba-6a7a199ae6c0.png)


Que devuelve la carpeta que apunta. Es probable que esa configuración no esté, por lo que la forma de arreglarlo sería en  caso de que apunte a otra carpeta, seriá:
```
export PKG_CONFIG_PATH=/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig
```
Ahora, si el problema persiste, buscando en una Issue en Github (https://github.com/rust-lang/pkg-config-rs/issues/23) alguien lo solucionó un problema similar intercambiando el orden, es decir:

```
export PKG_CONFIG_PATH=/mingw64/share/pkgconfig:/mingw64/lib/pkgconfig
```
Por lo que al repetir la línea del principio, deberías poder ver la versión:

```
  pkg-config --modversion gtk+-3.0  
```
