### ISSUE TITLE
Dudas generales (kits)

### ISSUE THREAD

**Issue by jffarren** [IEE2463/classroom#74]
Con respecto a los kits (específicamente los microcontroladores), quería saber si tienen alguna lista de cosas con las que hay que tener particular cuidado antes de aventurarse en el ensayo y error (ya sea con el software o el hardware). Pregunto esto porque hace un tiempo Felipe mencionó que existe la posibilidad de dañar el computador, los componentes del kit o ambos. Entonces, ¿qué cosas puntuales recomiendan?  Es una pregunta bastante general, pero creo que es importante para garantizar continuidad de labs de aquí hasta el final del semestre. ¡Gracias de antemano!

**Comment by mlibarra** [comment]
Hola, quería saber si tienen algún diagrama de conexión de la pantalla LCD. No he podido encontrar un datasheet bueno. Además si es necesario conectarla a través de resistencias a la MSP. También quería pregunta si la librería para controlar la LCD la debemos buscar en internet o si ya tienen una librería sería de gran ayuda. Saludos!

**Comment by CamilaTurrieta** [comment]
Hola, @mlibarra el diagrama te lo puedo facilitar, pero sólo porque queremos evitar que alguien se pueda equivocar con las conexiones y quemar algo. En general, se espera que ustedes sean capaces de buscar este ese tipo de cosas. El diagrama es el siguiente: 
![image](https://user-images.githubusercontent.com/48395528/84335811-b5e4bc80-ab63-11ea-9d23-544d0d518295.png)

La pantalla es bastante estándar (LCD 16x2), te recomiendo buscar una librería que utilice el modo de 4 bits (ahorra conexiones :D). Espero esto sea de ayuda. O bien, si alguien tiene la fuente, la puede publicar aquí :D Motivemos el trabajo en equipo!! 👍  💯 🥇 🎊

**Comment by mlibarra** [comment]
Muchas gracias! Si encuentro alguna librería la compartiré

**Comment by mlibarra** [comment]
Quería saber si esta librería sirve: https://mrchunckuee.blogspot.com/2015/11/msp-exp430g2-ccs-008.html
Es para otro MSP pero se puede adaptar. Es algo de ese estilo la librería esperada? Saludos

**Comment by RafaelOrmazabal** [comment]
Hola, tengo un problema muy similar al que tuvo Cristobal Mery. Por alguna razón, si prendo 6 segmentos o más, algunos de los segmentos se prenden con menor intensidad. Este problema se manifiesta especialmente en el segmento g. Ahora bien, cuando prendo solo el segmento g, este se ve perfectamente. Yo en mi casa tengo un display de 7 segmentos muy similar al del kit, existe la posibilidad de poder usarlo para el laboratorio?

**Comment by fffonceca** [comment]
@RafaelOrmazabal Claro que sí! Es una buena idea si es que es una mejor opción. 

@mlibarra Si sirve esta librería, pero es necesario que entiendas parte de la mecánica de las funciones y el funcionamiento básico del SPI. Recuerda referenciar bien los códigos ajenos.

**Comment by CamilaTurrieta** [comment]
@mlibarra Si se ve bien la librería y bien comentada. Habría que seguir las conexiones que ahí señalan y debería resultar sin mayor problema. 

**Importante**, hay que **entender lo suficiente** el protocolo de comunicación de la pantalla LCD (propio de la LCD) y las funciones de la librería para poder usarla en la aplicación que nos interesa.

Muchas gracias por el aporte al curso!

**Comment by fffonceca** [comment]
@RafaelOrmazabal Si es mejor opción que el material actual úsalo, fíjate bien en el datasheet de tu propio 7segmentos.

**Comment by mlibarra** [comment]
Encontré también este canal: https://www.youtube.com/watch?v=TL_cV4vqevE&list=PLeDS-EF4AzX5d8saglBw2cpO-s11Noyhs, explican para 8bits y 4bits, ocupan otra MSP pero se puede adaptar. Creo que es más fácil de entender que la anterior, además la explicación es bastante detallada y comparten el proyecto de CCS. No hay problema en utilizarla? Enseñan como hacer conversiones de float o entero a string que creo es requisito para enviar a la pantalla.

**Comment by RafaelOrmazabal** [comment]
@fffonceca Muchas gracias por la ayuda. Cambie el display y funcionó perfecto. La única diferencia es que es de cátodo común, importa?

**Comment by CamilaTurrieta** [comment]
Hola, @RafaelOrmazabal, no hay problema. :D

**Comment by fffonceca** [comment]
@RafaelOrmazabal Hace la diferencia y es muy importante, ya que indica el sentido de los leds. Debes procurar someterlos a polarización directa. Te recomiendo fuertemente revisar el datasheet para que no cometas ningún error.
![imagen](https://user-images.githubusercontent.com/48364596/84427240-9e084980-abf2-11ea-9a1b-a14c4c38dec3.png)

**Comment by CamilaTurrieta** [comment]
@mlibarra claro, si explica más cosas, mejor aún. Mientras se den las referencias y entiendan lo que están usando. Todo bien! 

Muchas gracias por publicarlo aquí! 

Sobre las referencias, no tiene que ser nada muy formal. Con señalar el link es suficiente.

**Comment by RafaelOrmazabal** [comment]
@fffonceca @CamilaTurrieta Muchas gracias. Me refería en términos de corrección, ya me había funcionado. Gracias de todas formas!!

**Comment by mlibarra** [comment]
@CamilaTurrieta muchas gracias! Saludos
