### ISSUE TITLE
LAB 05 - Dudas AVR

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#75]
Espacio destinado a dudas de AVR. Hay algunos problemas conocidos en el uso de Atmel Studio. Para ello tenemos el siguiente documento:

https://github.com/IEE2463/classroom/blob/master/Material%20de%20apoyo/Tutoriales/Soluciones_AVR.pdf

**Comment by danielaguilera** [comment]
Hola! Estuve probando mi ATMega y luego de hacer el build correctamente, conecto la placa y no pasa nada. De hecho me voy a Device Programming y no me aparece ni mEDBG ni ISP. ¿Qué puedo hacer al respecto?

Gracias

**Comment by fffonceca** [comment]
Teniendo atmel studio abierto, te reconoce la tarjeta en el momento de conectarla por USB?

**Comment by PamelaRomero** [comment]
Hola tuve un problema e intenté solucionarlo con el paso 3 del documento Soluciones_AVR y no se me ha solucionado. Me aparece el siguiente error:
![error_1](https://user-images.githubusercontent.com/62120800/84539022-b3e44000-acc0-11ea-8242-7d61285683d8.png)

Y creo que por esto no puedo seguir con el siguiente paso:
![imag_1](https://user-images.githubusercontent.com/62120800/84539234-0faec900-acc1-11ea-9302-ef33856bea0e.PNG)

Muchas gracias de antemano

**Comment by PamelaRomero** [comment]
Al final tenía ese error por una mala conexión que hice! Ya está solucionado! :D

**Comment by JMiguelCathalifaud** [comment]
Hola! Para desconectar las placas debo presionar algo en específico (ya sea en el computador o en el ATMEL Studio)? Intenté expulsarla como si fuera un pendrive pero no me aparece. Quiero asegurarme de que no me le pase nada si la desconecto así no más.

**Comment by fffonceca** [comment]
@danielaguilera Pudiste resolver tu problema? 
@PamelaRomero Que bueno!, podrías contar exactamente cuál fue la conexión mala para guardarlo en los problemas, o tu solución?
@JMiguelCathalifaud No hay problema en desconectarlo directamente mientras no estés programando en el.

**Comment by mlibarra** [comment]
Hola! Al dejar de presionar el botón, la cuenta queda estática. Para volver la cuenta a 0 es posible apretar reset? O todo debe ser con el mismo botón? En mi programa cuando vuelvo a presionar, la cuenta continua desde donde quedó (como el cronómetro cuando vuelven a poner play)

**Comment by fffonceca** [comment]
@mlibarra Lo ideal es que sea el mismo botón, ya que de esta forma tu programación es más robusta. Pero si lo haces, debes justificar su decisión.

**Comment by mlibarra** [comment]
@fffonceca gracias! ultima duda respecto a eso. Al presionar el boton de nuevo y la cuenta vuelve a 0, parte altiro la cuenta? o queda en 0 (como si se hubiera reseteado)

**Comment by CamilaTurrieta** [comment]
@mlibarra lo ideal es que una vez que presionas por primera vez el botón y lo sueltas en un valor intermedio, muestre dicho valor donde lo soltaste. Luego, si vuelves a presionar el botón, el contador debe volver a cero y si lo sueltas puedas visualizar cuánto rato tuviste ahora presionado el botón.  

Así que, la idea es que la cuenta vuelva a cero y parta todo de nuevo. (Lo que se espera es que esto ocurra sin apretar el reset).
