### ISSUE TITLE
LAB 05 - Dudas MSP

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#76]
Espacio destinado para dudas MSP

**Comment by aigalvez** [comment]
Hola!
Tengo sistema operativo mac, y no logro hacer la instalacion del compilador completa para el MSP, despues de poner todos los codigos en el terminal intente compilar el pin_test del lab 1, pero me aparece: -bash: msp430-gcc: command not found.
Dentro de las lineas de instalacion la unica que tiene algun error es la ./addlinks.sh, el terminal me señala lo siguiente:
ln: lib/ldscripts/msp430.xn: File exists
find: /usr/local/opt/msp430-libc/msp430: No such file or directory
find: /usr/local/opt/msp430-mcu/msp430: No such file or directory

No he podido resolver el problema buscando por lo que pregunto si alguno sabe algo al respecto
Gracias!

**Comment by fffonceca** [comment]
@aigalvez Hola! Te recomendamos que descargues code composer para MAC y nos cuentes cómo te fue.

**Comment by danielauu** [comment]
Hola, soy usuario de Windows y tengo un problema al instalar CCStudio, con el path del programa. Me dice "your temp directory path contains unicode characters which can corrupt the installation" siendo que lo estoy tratando de instalar en la carpeta "C:\".

Intenté resolverlo cambiando el nombre de la carpeta a instalar y el nombre del archivo ejecutable pero no funcionó.

Por otro lado, mi usuario tiene espacios y la eñe de mi apellido, pero no estoy instalando el programa en la carpeta de usuario. También intenté cambiar el nombre de usuario siguiendo tutoriales pero no ha funcionado tampoco 😢 

En verdad no sé qué puede ser.
![Captura](https://user-images.githubusercontent.com/48301729/84577417-e0b05a00-ad89-11ea-9f1d-f6a4602d8c94.PNG)

**Comment by danielauu** [comment]
Ya lo solucioné: cree una nueva carpeta con caracteres normales y la registré como path temporal (TEMP). 😄

**Comment by CamilaTurrieta** [comment]
Hola @danielauu! Excelente!! muchas gracias por comentar como lo solucionaste. 

Comentario adicional, hay que tener ojo con los nombres, tener cuidado con los espacios, las "ñ", los tildes, etc.... Consejo, mejor prevenir que lamentar, tomen esa forma de escribir como buena práctica.

**Comment by Yairdv** [comment]
Hola, tengo un problema al intentar debuggear/cargar la MSP. Me arroja el siguiente error al intentar conectar/reconocer el usb (placa) con mi computador:

Error initializing emulator:
No USB FET was found

Estuve leyendo foros de TI y muchos sugieren un error en los drivers o de placas defectuosas. Alguien sabe como solucionarlo?

![image](https://user-images.githubusercontent.com/62082683/84581470-3e0ad200-adaf-11ea-9978-45e610ef258d.png)

![image](https://user-images.githubusercontent.com/62082683/84581479-61ce1800-adaf-11ea-9b43-bd9021e6bfb4.png)

**Comment by fffonceca** [comment]
@Yairdv Esos problemas ocurren cuando no están actualizados los drivers de la tarjeta, o simplemente cuando no se detecta esta al conectarse. Si cuentas con otro cable USB prueba cambiándolo. Lo otro es verificar las actualizaciones de CCS y varía también los puertos USB a los que conectas. Cuéntame como te va.

**Comment by Yairdv** [comment]
@fffonceca Probé distintos puertos y con otro cable USB que tengo; aún no funciona. Estuve leyendo en los foros de TI pero no encuentro donde actualizar/descargar los drivers, alguna sugerencia?

**Comment by fffonceca** [comment]
@Yairdv Estos "drivers" se actualizan en el momento en el que haces build y posteriormente cargas el programa, CCS te debería avisar que no están actualizados y ejecuta una actualización previa a cargar nuevamente tu main.c  .  Verifica "como" te aparece el dispositivo en "Adminstrador de Dispositivos".

**Comment by Yairdv** [comment]
@fffonceca al final @felipesanchezvaras logró resolver mi problema. 

La solución está en este link por si alguien más la necesita:

https://e2e.ti.com/support/microcontrollers/msp430/f/166/t/760201#pi320995=2

**Comment by dari0s** [comment]
Hola buenas ! , he tratado de instalar el Code Composer toda la tarde jeje me arroja el siguiente error (ya probé instalando dos versiones anteriores), tengo un OS Windows 7 de 64 bit. Ya no sé que más intentar.

![image](https://user-images.githubusercontent.com/20529092/84582793-939aab00-adbe-11ea-8f88-2a475470edfe.png)

**Comment by fjhuanca** [comment]
@dari0s Hola! Una pregunta, tienes algún antivirus? prueba desactivando la protección en tiempo real del mismo y nos cuentas. Saludos!

**Comment by dari0s** [comment]
Gracias Fernando por responder, al final instalé la versión 9 y tuve que descargar los driver de forma manual en https://www.ti.com/tool/download/MSPDS , también tuve cuidado de ejecutar desde la consola de Windows y realizar toda la instalación offline, por si a alguien más le sirve :)

gracias

**Comment by fjhuanca** [comment]
@dari0s Que bueno! y gracias por compartir tu solución 👍 :)

**Comment by JavieraSanMartin** [comment]
Hola, tengo una duda respecto a la ayudantía de ADC en la MSP,  while (!(ADC12IFG & BIT0)); no entiendo bien esta linea. Podrían ayudarme? Gracias de antemano. Saludos

**Comment by CamilaTurrieta** [comment]
Hola @JavieraSanMartin, ese while provoca un delay que espera que la conversión este lista, es decir, va a mantener el código en esa línea hasta que la conversión de los valores leídos por el ADC estén listos.  En particular:

- El ADC12IFG es el registro que posee las "_banderas de interrupción_". Cuando hay una interrupción pendiente, este registro cambia alguno de sus bit de 0 a 1, según el caso. Las interrupciones de dicho registro cambian a 1 (es decir, quedan como pendientes) cuando ADC12MEMx tiene el resultado de la conversión listo. En el caso del código de la ayudantía, los valores se cargan en ADC12MEM0 y este está asociado al bit número 0 del registro ADC12IFG. Entonces, cuando ADC12MEM0 tenga los valores listos, el primer bit (el bit 0) de ADC12IFG cambia a 1. Entonces, en el while pasa algo como: 

`while (!(ADC12IFG & BIT0));` = while (!( 1 & 1 ))  = while (!( 1 ))  = while (0) = no se cumple el while sigo con la siguiente linea. 

Al revés, si ADC12MEM0 no tiene los valores listos, 

`while (!(ADC12IFG & BIT0));` = while (!( 0 & 1 ))  = while (!( 0 ))  = while (1) = Se cumple el while y  sigo ahí estando pegada en esa línea.  

¿Me explico?

**En resumen! lo que hay que saber es:** 

Que no es necesario saberse exactamente todo esto. Lo importante es saber que uno no puedo llegar y trabajar los valores del registro encargado de guardarlos (en este caso es el ADC12MEM0), si estos no están listos. Estos valores estarán listos cuando el ADC haya terminado la conversión. 

Por ello, es importante, usar alguna forma que permita indicarle al micro "hey ahora si puedes usar los valores" o un "todavía no puedes usar los valores". Y eso se puede hacer mediante las interrupciones propiamente tal (para ello hay que activarlas y hacer otras cosas) o mediante un while y un registro de estado que me indique en qué está el ADC.  

Lo último es lo importante. ¿Eso se entiende?

**Comment by JavieraSanMartin** [comment]
Entendí súper bien, muchísimas gracias Cami

**Comment by jpcrisostomo** [comment]
> Hola!
> Tengo sistema operativo mac, y no logro hacer la instalacion del compilador completa para el MSP, despues de poner todos los codigos en el terminal intente compilar el pin_test del lab 1, pero me aparece: -bash: msp430-gcc: command not found.
> Dentro de las lineas de instalacion la unica que tiene algun error es la ./addlinks.sh, el terminal me señala lo siguiente:
> ln: lib/ldscripts/msp430.xn: File exists
> find: /usr/local/opt/msp430-libc/msp430: No such file or directory
> find: /usr/local/opt/msp430-mcu/msp430: No such file or directory
> 
> No he podido resolver el problema buscando por lo que pregunto si alguno sabe algo al respecto
> Gracias!



> Hola!
> Tengo sistema operativo mac, y no logro hacer la instalacion del compilador completa para el MSP, despues de poner todos los codigos en el terminal intente compilar el pin_test del lab 1, pero me aparece: -bash: msp430-gcc: command not found.
> Dentro de las lineas de instalacion la unica que tiene algun error es la ./addlinks.sh, el terminal me señala lo siguiente:
> ln: lib/ldscripts/msp430.xn: File exists
> find: /usr/local/opt/msp430-libc/msp430: No such file or directory
> find: /usr/local/opt/msp430-mcu/msp430: No such file or directory
> 
> No he podido resolver el problema buscando por lo que pregunto si alguno sabe algo al respecto
> Gracias!



> Hola!
> Tengo sistema operativo mac, y no logro hacer la instalacion del compilador completa para el MSP, despues de poner todos los codigos en el terminal intente compilar el pin_test del lab 1, pero me aparece: -bash: msp430-gcc: command not found.
> Dentro de las lineas de instalacion la unica que tiene algun error es la ./addlinks.sh, el terminal me señala lo siguiente:
> ln: lib/ldscripts/msp430.xn: File exists
> find: /usr/local/opt/msp430-libc/msp430: No such file or directory
> find: /usr/local/opt/msp430-mcu/msp430: No such file or directory
> 
> No he podido resolver el problema buscando por lo que pregunto si alguno sabe algo al respecto
> Gracias!

Hola, pudiste solucionarlo?
Tampoco puedo subir a la tarjeta.
Gracias!
