### ISSUE TITLE
LAB 05 - Otras Dudas

### ISSUE THREAD

**Issue by felipesanchezvaras** [IEE2463/classroom#77]
Espacio destinado para otras dudas relacionadas con la entrega.

**Comment by Yairdv** [comment]
Hola, hasta que hora se puede entregar este lab? Como el enunciado dice que no se recibirán trabajos después del módulo de presentación, asumo que el primer módulo de presentación (8:30) es el tope para todos?

**Comment by felipesanchezvaras** [comment]
Formalmente tienen hasta las 10:00 AM (hora oficial de laboratorio) para entregar, pero es decisión del alumno si es que trabaja hasta la hora de su revisión. Lo que no se permite es entregar después del horario asignado.

Sin embargo, dada la modalidad de revisión online, tenemos que agregar horarios extras y es por esto que se producen estos desfases al momento de entregar.

**Comment by aigalvez** [comment]
Hola!
Conecte ambos micros para revisar que estaban funcionando bien antes de presentar, y el codigo del msp que me funciono bien toda la mañana ya no funcionaba, fui revisando el codigo y achicandolo y al parecer uno de los botones se esta manteniendo presionado constantemente. 
Que deberia hacer ? en la presentacion mostrar el funcionamiento con un solo boton? (por ejemplo que el boton bueno cambie el eestado (rojo-verde-azul), y que se actualicen siempre (sin tener que confirmar)

Gracias de antemano

**Comment by felipesanchezvaras** [comment]
@aigalvez Intentar ver si se puede destrabar el botón, puede que sea un problema mecánico. Sino, intenta presentar lo mejor que se pueda, y de todas formas muestra tu código del botón.
