### ISSUE TITLE
Librerias LAB6

### ISSUE THREAD

**Issue by CristobalMery** [IEE2463/classroom#79]
Buenas tardes. Escribo para consultar si es necesario en el laboratorio 6 utilizar los archivos entregados USART_implement_me.c, USART_implement_me.h? O bien podría desarrollar todo mi código en un mismo archivo main.c?

**Comment by GutiJos** [comment]
Hola @CristobalMery 
La idea es que aprendan a utilizar librerías, por lo tanto, no se acepta que desarrolles las funciones de UART en tu archivo main.c.
Otra cosa, el código entregado es sólo una guía para que desarrollen las funciones de UART. Por lo que si quieres desarrollar una librería propia puedes hacerlo.

saludos.
