### ISSUE TITLE
Apagar BackLight LCD en BoosterPack

### ISSUE THREAD

**Issue by javifunk** [IEE2463/classroom#8]
Hola!

Al conectar el BoosterPack noté que la pantalla LCD se enciende (BackLight). Busqué en el datasheet (tanto del BoosterPack como del LCD) y -según entiendo- es posible apagarla enviando una señal `LOW `al **pin J4.39**. El problema inicial era que no podía mantenerla apagada al mismo tiempo que encender el canal rojo del led RGB, puesto que como indica el datasheet ambos se encuentran multiplexados por el **jumper J5** . En otras palabras, si quería manipular la luz roja debo "aguantar" que esté encendido el BackLight del LCD.

Improvisé una solución  generando un `LOW` en un pin _NC_ y conectandolo externamente con un cable Dupont F-F al pin del BlackLight (etiquetado como "3", ubicado arriba del joystick).

Mis dudas son:

1. Existe una manera "interna" de apagar el BackLight del LCD al mismo tiempo que manipulo el canal rojo del led RGB?
2. De no existir, es necesario que incluya esta conexión externa en el ReadMe y en el código genere la respectiva señal `LOW`? O en verdad "da lo mismo" si el BackLight del LCD está o no encendido para esta actividad?

De antemano muchas gracias :)

**Comment by fffonceca** [comment]
Efectivamente estás apagando el backlight del LCD. El problema es que la pantalla está mostrando los pixeles programados, o por defecto. Este problema se solucionará cuando lleguemos a la parte de comunicación SPI necesaria para manipular la pantalla TFT del booster pack mkii. 

Lo otro que podrías hacer, es ejecutar energia para mostrar una pantalla en negro en el TFT y seguir programando tus _task_ normalmente. 

Espero esto haya resolvido tu duda. Estoy atento.

**Comment by javifunk** [comment]
Ah entiendo, entonces, solo para confirmar:

Está OK que incluya esto en mi ReadMe y código? O es irrelevante el asunto de la pantalla para la evaluación?

Lo digo para poder tener apagada la BackLight sin tener que meterme con SPI (todavía)  ni Energía (no se usarlo...)

**Comment by fffonceca** [comment]
Es irrelevante. Todo lo que tenga que ver con el código y la rúbrica debe ser implementado en el readme, en caso contrario, no es necesario y solo hace más larga la evaluación.

Ahora, debes tener cuidado con usar energia, ya que está prohibido usarlo para completar el laboratorio. Procura solo usar energia para apagar el BackLight.

**Comment by javifunk** [comment]
Dale, veré que tal con Energía.

Muchas gracias :)
