### ISSUE TITLE
¿Es posible que el arduino de tinkercad no tenga la tierra de Atmega?

### ISSUE THREAD

**Issue by diegomarusic** [IEE2463/classroom#8]
En todo los pinout que he encontrado la tierra está en un componente "sobre el arduino", sin embargo en tinkercad dicho componente no aparece. Entonces ¿con qué pin puedo usar la tierra de la atmega en el arduino de tinkercad?

**Comment by moquezada** [comment]
No soy ayudante ni tampoco entiendo tanto tu pregunta lol Pero aquí te dejo un pin mapping del ATmega328P respecto a las salidas del arduino:

![267f60a5f7973c27e2bdc2b08b1fb845](https://user-images.githubusercontent.com/43896576/77083942-07eec980-69dd-11ea-9f63-038da2c8172f.png)

De todas formas, el Arduino de Tinkercad tiene como dos o tres pines de tierra disponibles, no sé porqué no podrías usar uno de esos 🤔

**Comment by CamilaTurrieta** [comment]
Hola @diegomarusic tampoco entiendo muy bien tu pregunta :( .... ¿Podrías explicar más cuál es el problema? porque, tal como dijo @moquezada, no deberías tener problemas al usar las tierras que proporciona la placa de desarrollo del Arduino (que están unidas al atmega).

**Comment by diegomarusic** [comment]
jajaj si gracias @moquezada, duda resuelta. Pensé que estaba conectando mal la tierra para medir una PWM con el osciloscopio, pero el problema es otro.
