### ISSUE TITLE
paso en el tutorial donde indica dar aviso [windows 10]

### ISSUE THREAD

**Issue by vaalvarado** [IEE2463/classroom#8]
una vez instalado atmel studio 7, segui el tutorial subido, y en el paso donde aparece build succeded y conecto la targeta (atmega...) al pc, esta no me arroja nada. En el tutorial dice que si me ocurre lo anterior debo avisar a los ayudantes. Sigo intentandolo?

**Comment by felipesanchezvaras** [comment]
@vaalvarado Continua el tutorial y ve si es que puedes realizar device programming, comenta qué resulta

**Comment by vaalvarado** [comment]
luego de reiniciar el pc y probar denuevo funciono!
gracias de todas maneras
