### ISSUE TITLE
RealTerm

### ISSUE THREAD

**Issue by mlibarra** [IEE2463/classroom#80]
Hola! Cuando muevo el potenciometro y pido su valor desde RealTerm, este no se actualiza a noser que apague el puerto desde la consola y lo encienda de nuevo. Ya he revisado el código varias veces y no sabría que está mal. Alguien tiene alguna idea de qué puede ser?

**Comment by fffonceca** [comment]
Prácticamente cuando cortas el puerto desde la consola y lo vuelves a conectar, reinicias el programa. Lo que esperamos en el laboratorio es que puedas mandar un mensaje desde la consola a la placa con tal de pedir el voltaje en ese instante **sin tener que apagar la consola forzadamente**. Espero que te guíe @mlibarra Saludos!

**Comment by mlibarra** [comment]
@fffonceca Sii si entiendo que no debo reiniciar, sé que está mal, por eso pregunto, porque ya he revisado hartas veces el código y no sé que tengo malo. Según yo estoy actualizando el ADC, el valor de UART (la recepción con interrupciones), tengo variables volátiles, etc, entonces no sabría que ocurre. Es posible subir el código a mi repositorio? Saludos!

**Comment by felipesanchezvaras** [comment]
@mlibarra Sube tu código al repositorio. Crea una Issue indicando el problema que tienes y después comentala añadiendo a los ayudantes de la forma @IEE2463/ayudantes-sep

**Comment by mlibarra** [comment]
@felipesanchezvaras muchas gracias!
