### ISSUE TITLE
Entrega LAB6

### ISSUE THREAD

**Issue by CristobalMery** [IEE2463/classroom#83]
Buenas noches! 
Hay un aspecto que no me quedó muy claro respecto de la entrega del lab 6.

Si es que logro realizar el Task 3; bastaría simplemente con entregar los códigos de este task y mostrar su funcionamiento? Es decir, los códigos del task 1 y 2 no son necesarios de entregar?

**Comment by CamilaTurrieta** [comment]
Hola @CristobalMery ! Siempre se sube todo a github... Pero si logras realizar el task 3, en la presentación sólo muestras el task 3. Esto por temas de tiempo y porque el task 3 engloba las ideas anteriores.  ¿Se entiende más la idea? 

Y bueno, si alguien no alcanzó a hacer el task 3, presenta el task 1 y 2.
