### ISSUE TITLE
Compilar librerias en MAC

### ISSUE THREAD

**Issue by sebapulgar** [IEE2463/classroom#89]
hola! inicialmente desarrollé un código en windows para la parte 1 de la tarea, sin embargo ya no cuento con ese computador y a la hora de compilar el código desde la terminal del mac como se enseñaba en el task 1 dice que las funciones declaradas en la libreria no existen a pesar de que están declaradas y se llama a la misma librería en el main
No se si debo compilar también las librerías por separado, sin embargo es el mismo código que desarrollé en atmel y funcionó por lo que no se cual es el error.

![Captura de Pantalla 2020-06-21 a la(s) 12 34 48](https://user-images.githubusercontent.com/62195837/85230069-9e0b0500-b3bb-11ea-942c-79a701f69fe6.png)

**Comment by jpcrisostomo** [comment]
Hola, a mi me pasa exactamente lo mismo. No he podido compilar aún.
Buscando en internet vi que probablemente es porque el makefile/comandos para compilar terminal solo llaman al archivo UART.c, pero no se llaman a las librerías implement_me.h ni su código  implement_me.c

**Comment by felipesanchezvaras** [comment]
@sebapulgar @jpcrisostomo pueden subir una foto de la carpeta en que se vean los archivos? Que comando están utilizando para compilar ?

**Comment by jpcrisostomo** [comment]
Hola, esta es la carpeta en la que tengo mis códigos y el makefile
![Screen Shot 2020-06-21 at 14 23 15](https://user-images.githubusercontent.com/62001546/85232144-e67def00-b3ca-11ea-9b44-5732192582f0.png)
Y uso este makefile para compilar
![Screen Shot 2020-06-21 at 14 25 47](https://user-images.githubusercontent.com/62001546/85232201-30ff6b80-b3cb-11ea-9e47-ee582fc3d4d7.png)

**Comment by sebapulgar** [comment]
@felipesanchezvaras  hola! tengo exactamente lo mismo, he tratado compilando desde el terminal con un bash y directamente con los comandos . La única diferencia es que tengo los ficheros dentro de una carpeta llamada UART
Por ahora para no atrasarme pasé los ficheros dentro de la misma documento main.c como funciones pero no sé que más hacer.

Los comandos usados son los que se encontraban en el task1

![Captura de Pantalla 2020-06-21 a la(s) 14 51 45](https://user-images.githubusercontent.com/62195837/85232674-bdf7f400-b3ce-11ea-9423-007ea39040cf.png)
![Captura de Pantalla 2020-06-21 a la(s) 14 52 05](https://user-images.githubusercontent.com/62195837/85232683-c9e3b600-b3ce-11ea-9161-8fa4dca00089.png)

**Comment by felipesanchezvaras** [comment]
@sebapulgar 

En tu caso, lo que está faltando es agregar la librería de uart para la compilación, si lo tienes en una carpeta te debería quedar algo como:

```
avr -gcc -Wall -Wextra -Wpedantic --std=gnu99 -mmcu=atmega328p -Os -o main.elf main.c USART/USART_implement_me.c
```

Las siguientes lineas, que tienen el `avr-objcopy` y `arvdude` se deben mantener iguales, ya que en la línea anterior, le estas diciendo al compilador que considere también el USART_implement_me.c

No es lo ideal tener todo en un mismo archivo, pero por temas de tiempo está bien si es seguiste avanzando manteniendolo ahí, aunque te sugiero tener listo lo demás. 

@jpcrisostomo En tu caso es algo muy similar, a tu compile: debes agregarle la ruta del USART_implement_me.c, es decir, luego del  `$(FILENAME).c` le puedes agregar `USART_implement_me.c` y eso reconocerá el archivo.

**Comment by sebapulgar** [comment]
@felipesanchezvaras Muchas gracias funcionó perfecto!
