### ISSUE TITLE
Entrega de archivos

### ISSUE THREAD

**Issue by benjareinoso** [IEE2463/classroom#9]
Hola! Tengo una duda respecto a la entrega. Se deberían subir 3 archivos cierto? (loop de colores en c, loop de colores en assembly y seleccionador de secuencia)

**Comment by felipesanchezvaras** [comment]
Hola @benjareinoso 

Exacto, se deben subir 3 archivos. Idealmente separados en carpeta. Su repositorio podría verse de la siguiente forma:

```
Readme.md
/Task 1
--- main_c.c
--- main_assembly.asm
/Task 2
--- main_c.c
```

Saludos,
