### ISSUE TITLE
[MacOS Mojave]  Problema al instalar msp430gcc

### ISSUE THREAD

**Issue by JavierBZ** [IEE2463/classroom#9]
Hola! estoy intentando instalar el compilador de msp430 para macOS Mojave versión 10.14.3  siguiendo las instrucciones del enunciado, pero al momento de ejecutar:
`brew install msp430-libc`
Me entrega el siguiente error (una parte de él):
`Makefile:4283: recipe for target 'doc/gcc.info' failed 
make[2]: *** [doc/gcc.info] Error 1
/bin/sh ../../gcc/../move-if-change tmp-mlib.h multilib.h
echo timestamp > s-mlib
rm gcc.pod
make[2]: Leaving directory '/private/tmp/msp430-gcc-20190327-18910-1vjj06l/gcc-4.7.0/build/gcc'
Makefile:3838: recipe for target 'all-gcc' failed
make[1]: *** [all-gcc] Error 2
make[1]: Leaving directory '/private/tmp/msp430-gcc-20190327-18910-1vjj06l/gcc-4.7.0/build'
Makefile:856: recipe for target 'all' failed
make: *** [all] Error 2`

Los siguientes pasos del enunciado los puedo hacer, pero al momento de compilar con msp430-gcc falla. En la web encontré que la solución era usar otros repositorios que no fuera el de sampsyo/homebrew-mspgcc, pero termine con errores similares.
También al ejecutar:
`./addlinks.sh`
No encuentra los siguientes archicos:
`find: /usr/local/opt/msp430-libc/msp430: No such file or directory
find: /usr/local/opt/msp430-mcu/msp430: No such file or directory`

Estaré atento y gracias de antemano.

**Comment by loky32** [comment]
Hola, que tal? En efecto hay un problema al compilar en la última versión de OSX, para solucionarlo debes hacer lo siguiente:
brew tap tgtakaoka/mspgcc
brew install libc-msp430 gdb-msp430
Luego una vez instalado el compilador procedemos a instalar mspdebug:
brew install mspdebug
Posteriormente descarga el driver de la repo del enunciado y dirígete por terminal a la carpeta de la repo, una vez dentro escribes:
cp libmsp430.so /usr/local/lib/
Y ahora estarás listo para correr MSP430 ;)
Saludos!

**Comment by JavierBZ** [comment]
Hola! gracias por la ayuda, pero tengo problemas para llegar a la carpeta de la repo. ¿Donde la puedo encontrar exactamente?

**Comment by loky32** [comment]
A que te refieres con la carpeta de la repo? El comado brew tap tgtakaoka/mspgcc es directo, o te refieres a la repo que contiene el driver (https://github.com/loky32/msp430_OSX)?

**Comment by JavierBZ** [comment]
Hola, yo me confundí al hacer lo que me dijiste en el cuarto paso. Debia abrir terminal en la carpeta que se descarga y no en la que crea el brew tap. Hice todo, pero ahora me sale otro error al compilar msp430-gcc u.u

`fatal error: stdint.h: No such file or directory compilation terminated.`

Hay varias páginas que hablan de este error, pero no encontre especificamente para msp.

**Comment by loky32** [comment]
Hola Javier, estas en la Universidad? Escríbeme un mail a jecortes1@uc.cl para coordinar ahora al almuerzo una reunion express

**Comment by aamacaya** [comment]
Hola! 
Estoy exactamente con el mismo problema. Incluso descargúe e instalé el software directamente desde Texas Instruments.
Hice los mismos pasos que este Issue y llegué a los mismos errores.

Ahora estoy en

fatal error: stdint.h: No such file or directory compilation terminated.

Lograron resolver el problema?

**Comment by loky32** [comment]
Hola!, he llegado a la solución del problema, en primer lugar será necesario desinstalar algunas cosas previas instaladas desde las repos referentes a msp430-gcc, luego instalar el siguiente paquete mas antiguo del compilador 
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/osx-launchpad/MSP430-Launchpad-toolchain-20111001.pkg.zip
Con esto comprobamos en terminal que tengamos la version 4.5.3 de msp430-gcc con msp430-gcc --version.
Las ubicaciones a eliminar pueden ser encontradas mediante el siguiente comando:
open /usr/local/cellar
En esta carpeta borrar gcc-msp430 y msp430-binutils. 
Quedo atento  y espero les haya servido 👍

**Comment by aamacaya** [comment]
Gracias!, me sirvió la instalación y el compilador, solo me queda una ultima duda:

Para subir el programa a la placa, según la guia del lab hay que usar el comando:

mspdebug tilib "prog nombre . bin "

sin embargo me da un error diciendo:

Unknown driver: tilib. Try --help for a list.

Instalé y actualicé mspdebug, pero tilib sigue sin aparecer en la lista de drivers de mspdebug. Como se puede arreglar esto para subir el código a la placa vía terminal?

**Comment by loky32** [comment]
No olvides posteriormente descargar el driver de la repo del enunciado y dirigete a la siguiente ruta:
open /usr/local/lib/
copias el archivo libmsp430.so 
Y ahora estarás listo para correr MSP430 ;)
Saludos!
