### ISSUE TITLE
Error al ejecutar "Hello World" compilado, windows lo detecta como amenaza

### ISSUE THREAD

**Issue by Pochoclo** [IEE2463/classroom#9]
Al compilar el "Hello world" usando MinGW, windows me detecta el .exe generado como una amenaza al sistema y no me permite ejecutarlo, me indica que el archivo es un troyano. En la consola me sale el siguiente error:

`Error al ejecutar el programa 'a.exe': No se pudo completar la operación porque el archivo contiene un virus o
software potencialmente no deseado En línea: 1 Carácter: 1
+ ./a.exe
+ ~~~~~~~.
En línea: 1 Carácter: 1
+ ./a.exe
+ ~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed`

ya segui los pasos del tutorial al pie de la letra, tengo añadido el compilador al Path y todo. Que debo hacer para que Windows no me lo tome como amenaza y poder ejecutar el programa?

**Comment by Pochoclo** [comment]
Para que funcionara el poder ejecutarlo tuve que permitir el archivo desde windows defender.

**Comment by fffonceca** [comment]
@Pochoclo Mantenemos la issue abierta para que otras personas puedan apoyarse de tu solución. Cuando cambiemos de laboratorio cerraremos todas estas issues. 👍
