### ISSUE TITLE
Consulta de formato de entrega

### ISSUE THREAD

**Issue by jnopazo** [IEE2463/classroom#9]
Hola, tengo varias dudas:

- Para Task 2 y Task 3 ¿Los códigos van en distintos archivos? (uno .asm para task 1 assembly, uno .c para task 1 en C y uno en .c para task 3)
- ¿La estructura de las carpetas como debe ser? (dado que son 2 ó 3 códigos y un README) 
-  ¿Qué  nombre se le pone a cada archivo?

**Comment by felipesanchezvaras** [comment]
Hola @jnopazo , 

El orden de los archivos lo haremos de la siguiente forma:

- Códigos
    - Task 2 C
        - main.c 
    - Task 2 Assembly
        - main.asm
    - Task 3
        - main.c
- README.md

**Comment by PedroDP99** [comment]
Hola.

Entonces, ¿no se deben subir los archivos que se generan al inicializar un proyecto? Es decir, ¿en la carpeta de códigos no van las carpetas que genera CCS?, ¿ni tampoco en las carpetas de cada Task?

**Comment by felipesanchezvaras** [comment]
Hola @PedroDP99 ,
Exacto, no se deben subir los archivos que se generan al inicializar un proyecto, solo se deben adjuntar los códigos .c y .h que hayas utilizado. Mediante un archivo .gitignore puede agregar las extensiones de todos los archivos que genera CCS y evitar que sean subidos en GitHub.
