### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by IsabelJamett** [IEE2463/classroom#90]
Hola, en la parte en donde la MSP debe transformar el valor a voltaje para mostrarlo en el LCD en el task 3, debe ser con respecto a 3.3V o con respecto a 5V?

**Comment by CamilaTurrieta** [comment]
Hola @IsabelJamett, el micro que esta tomando los datos es la avr, entonces, va a depender de que voltaje de referencia tomaste en la avr. Si en la avr definiste que el voltaje de referencia es 5V, entonces, debe ser con respecto a 5V, porque la idea es que sepamos cuanto es el voltaje que esta realmente midiendo el adc.
